#coding=utf-8

from argparse import ArgumentParser
import sys

def parse(path: str, begin: int = 0, stop: int = 0, thres: int = 0):
    with open(path, "r") as fsrc:
        items = []
        for line in fsrc.readlines():
            data = [d.replace("\t", "@").strip() for d in line.split('|')]
            if len(data) >= 6:
                item = {
                    "name": data[0],
                    "base": int(data[1], 16) if len(data[1]) else 0, 
                    "class": data[2], 
                    "type": data[3], 
                    "size": int(data[4], 16) if len(data[4]) else 0, 
                    "line": int(data[5]) if len(data[5]) else 0, 
                    "lib/section": data[6]
                }
                if item["size"] > thres and item["base"] >= begin and item["base"] + item["size"] <= stop:
                    items.append(item)
        items.sort(key = lambda x: x['size'], reverse = True)
        return items
    return None

def save(items: list, path: str):
    with open(path, "w+") as fdst:
        fdst.write(','.join([str(v) for v in items[0].keys()]))
        fdst.write('\n')
        for item in items:
            item = [hex(v) if str(v).isdigit() else str(v) for v in item.values()]
            item[4] = "%d" % int(item[4], 16) # size
            fdst.write(','.join(item))
            fdst.write('\n')

if __name__ == '__main__':
    if len(sys.argv) == 2: sys.argv.extend(sys.argv.pop(1).split(';'))
    parser = ArgumentParser(description='castor adx symbol parsing script, powered by xhtan@listenai.com')
    parser.add_argument('--begin', "-b", dest="begin", default=0
        , nargs=1, metavar="ADDR", help='the begin address for parsing')
    parser.add_argument('--end', "-e", dest="end", nargs=1
        , metavar="ADDR", help='the end address for parsing')
    parser.add_argument("--thres", "-t", dest="thr", default=0
        , nargs=1, metavar="SIZE", help="the thres for parsing")
    parser.add_argument("--csv", dest="csv", type=str, nargs=1
        , metavar="CSV", help="the output path of csv file")
    parser.add_argument("path", metavar="PATH", type=str
        , help="path of the symbol file generated by nm")

    if 1 == len(sys.argv):
        parser.parse_args(["-h"])
    else:
        args = parser.parse_args()
        outs = parse(path = args.path, begin = int(args.begin[0], 0), 
            stop = int(args.end[0], 0), thres = int(args.thr[0], 0))
        if outs:
            save(outs, args.csv[0])
