; 聆思科技 VENUS 资源打包配置文件

[Info]
; 本段中主要包含了系统配置信息，除特殊说明可以修改外，请勿擅自改动

FirmwareName=null.bin
; 输入的固件文件

NewFileName=respak.bin
; 输出的资源包文件，由本打包工具生成

ResStartAddr=0
; 资源偏移位置，固定值

ResHeaderTag=IFLY
; 资源头标记信息，必须是“IFLY”，不能修改

[List]
; 本段中包括文件列表，需要注意左侧的关键字，必须是4个字符（0-9，A-Z，
; 不区分大小写），并且唯一，右侧可以是相对路径或绝对路径，支持多个唤醒
; 资源，这些资源文件在您购买定制唤醒引擎时，由科大讯飞提供，用户可参考
; 如下格式进行修改，增加，删除等操作
INFO=info.txt
CONF=null.bin
TOTP=otptab.bin
MCNN=algo/mlp.bin
UNET=null.bin
KEYS=algo/main.bin
CMDS=algo/cmds.bin
VOIC=algo/voice.bin
0008=null.bin
0009=null.bin