//  ----------------------------------------------------------------------
//  File Name   : GenCFold/aon_iomux_reg_mars.h
//  Description : C header file generated by Python script.
//  Script Ver  : LS.AUTO_REG.2024.03.01
//  Create Time : 2024-03-20 14:46:55
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __AON_IOMUX_REGFILE_H__
#define __AON_IOMUX_REGFILE_H__

#include <stdint.h>

#define AON_IOMUX_PAD_AON_GPIOB_00_OFFSET           0x000
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_00_PAD_AON_GPIOB_00_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_01_OFFSET           0x004
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_01_PAD_AON_GPIOB_01_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_02_OFFSET           0x008
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_02_PAD_AON_GPIOB_02_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_03_OFFSET           0x00C
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_03_PAD_AON_GPIOB_03_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_04_OFFSET           0x010
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_04_PAD_AON_GPIOB_04_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_05_OFFSET           0x014
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_05_PAD_AON_GPIOB_05_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_06_OFFSET           0x018
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_06_PAD_AON_GPIOB_06_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_07_OFFSET           0x01C
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_07_PAD_AON_GPIOB_07_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_08_OFFSET           0x020
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_08_PAD_AON_GPIOB_08_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_09_OFFSET           0x024
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_09_PAD_AON_GPIOB_09_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_10_OFFSET           0x028
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_10_PAD_AON_GPIOB_10_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_11_OFFSET           0x02C
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_11_PAD_AON_GPIOB_11_FSEL_Msk    0x7

#define AON_IOMUX_PAD_AON_GPIOB_12_OFFSET           0x030
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_DRV_Pos    25
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_DRV_Msk    0x2000000
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_OEN_FRC_Pos    22
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_OEN_FRC_Msk    0x400000
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_OEN_REG_Pos    21
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_OEN_REG_Msk    0x200000
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_PULL_FRC_Pos    18
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_PULL_FRC_Msk    0x40000
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_PULL_UP_Pos    17
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_PULL_UP_Msk    0x20000
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_PULL_DN_Pos    16
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_PULL_DN_Msk    0x10000
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_OD_EN_Pos    9
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_OD_EN_Msk    0x200
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_ANA_SEL_Pos    5
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_ANA_SEL_Msk    0x1e0
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_FSEL_Pos    0
#define AON_IOMUX_PAD_AON_GPIOB_12_PAD_AON_GPIOB_12_FSEL_Msk    0x7

struct AON_IOMUX_REG_PAD_AON_GPIOB_00_BITS
{
    volatile uint32_t PAD_AON_GPIOB_00_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_00_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_00_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_00_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_00_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_00_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_00_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_00_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_00_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_00 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_00_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_01_BITS
{
    volatile uint32_t PAD_AON_GPIOB_01_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_01_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_01_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_01_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_01_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_01_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_01_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_01_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_01_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_01 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_01_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_02_BITS
{
    volatile uint32_t PAD_AON_GPIOB_02_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_02_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_02_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_02_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_02_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_02_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_02_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_02_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_02_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_02 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_02_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_03_BITS
{
    volatile uint32_t PAD_AON_GPIOB_03_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_03_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_03_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_03_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_03_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_03_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_03_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_03_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_03_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_03 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_03_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_04_BITS
{
    volatile uint32_t PAD_AON_GPIOB_04_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_04_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_04_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_04_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_04_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_04_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_04_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_04_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_04_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_04 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_04_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_05_BITS
{
    volatile uint32_t PAD_AON_GPIOB_05_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_05_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_05_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_05_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_05_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_05_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_05_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_05_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_05_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_05 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_05_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_06_BITS
{
    volatile uint32_t PAD_AON_GPIOB_06_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_06_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_06_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_06_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_06_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_06_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_06_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_06_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_06_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_06 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_06_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_07_BITS
{
    volatile uint32_t PAD_AON_GPIOB_07_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_07_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_07_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_07_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_07_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_07_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_07_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_07_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_07_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_07 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_07_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_08_BITS
{
    volatile uint32_t PAD_AON_GPIOB_08_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_08_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_08_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_08_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_08_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_08_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_08_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_08_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_08_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_08 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_08_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_09_BITS
{
    volatile uint32_t PAD_AON_GPIOB_09_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_09_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_09_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_09_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_09_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_09_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_09_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_09_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_09_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_09 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_09_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_10_BITS
{
    volatile uint32_t PAD_AON_GPIOB_10_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_10_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_10_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_10_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_10_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_10_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_10_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_10_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_10_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_10 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_10_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_11_BITS
{
    volatile uint32_t PAD_AON_GPIOB_11_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_11_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_11_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_11_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_11_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_11_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_11_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_11_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_11_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_11 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_11_BITS      bit;
};

struct AON_IOMUX_REG_PAD_AON_GPIOB_12_BITS
{
    volatile uint32_t PAD_AON_GPIOB_12_FSEL         : 3; // bit 0~2
    volatile uint32_t RESV_3_4                      : 2; // bit 3~4
    volatile uint32_t PAD_AON_GPIOB_12_ANA_SEL      : 4; // bit 5~8
    volatile uint32_t PAD_AON_GPIOB_12_OD_EN        : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t PAD_AON_GPIOB_12_PULL_DN      : 1; // bit 16~16
    volatile uint32_t PAD_AON_GPIOB_12_PULL_UP      : 1; // bit 17~17
    volatile uint32_t PAD_AON_GPIOB_12_PULL_FRC     : 1; // bit 18~18
    volatile uint32_t RESV_19_20                    : 2; // bit 19~20
    volatile uint32_t PAD_AON_GPIOB_12_OEN_REG      : 1; // bit 21~21
    volatile uint32_t PAD_AON_GPIOB_12_OEN_FRC      : 1; // bit 22~22
    volatile uint32_t RESV_23_24                    : 2; // bit 23~24
    volatile uint32_t PAD_AON_GPIOB_12_DRV          : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AON_IOMUX_REG_PAD_AON_GPIOB_12 {
    volatile uint32_t                               all;
    struct AON_IOMUX_REG_PAD_AON_GPIOB_12_BITS      bit;
};

typedef struct
{
    union AON_IOMUX_REG_PAD_AON_GPIOB_00            REG_PAD_AON_GPIOB_00; // 0x000
    union AON_IOMUX_REG_PAD_AON_GPIOB_01            REG_PAD_AON_GPIOB_01; // 0x004
    union AON_IOMUX_REG_PAD_AON_GPIOB_02            REG_PAD_AON_GPIOB_02; // 0x008
    union AON_IOMUX_REG_PAD_AON_GPIOB_03            REG_PAD_AON_GPIOB_03; // 0x00C
    union AON_IOMUX_REG_PAD_AON_GPIOB_04            REG_PAD_AON_GPIOB_04; // 0x010
    union AON_IOMUX_REG_PAD_AON_GPIOB_05            REG_PAD_AON_GPIOB_05; // 0x014
    union AON_IOMUX_REG_PAD_AON_GPIOB_06            REG_PAD_AON_GPIOB_06; // 0x018
    union AON_IOMUX_REG_PAD_AON_GPIOB_07            REG_PAD_AON_GPIOB_07; // 0x01C
    union AON_IOMUX_REG_PAD_AON_GPIOB_08            REG_PAD_AON_GPIOB_08; // 0x020
    union AON_IOMUX_REG_PAD_AON_GPIOB_09            REG_PAD_AON_GPIOB_09; // 0x024
    union AON_IOMUX_REG_PAD_AON_GPIOB_10            REG_PAD_AON_GPIOB_10; // 0x028
    union AON_IOMUX_REG_PAD_AON_GPIOB_11            REG_PAD_AON_GPIOB_11; // 0x02C
    union AON_IOMUX_REG_PAD_AON_GPIOB_12            REG_PAD_AON_GPIOB_12; // 0x030
} AON_IOMUX_RegDef;


#endif // __AON_IOMUX_REGFILE_H__

