//  ----------------------------------------------------------------------
//  File Name   : GenCFold/aon_ctrl_reg_mars.h
//  Description : C header file generated by Python script.
//  Script Ver  : LS.AUTO_REG.2024.03.01
//  Create Time : 2024-03-20 14:46:55
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __AON_CTRL_REGFILE_H__
#define __AON_CTRL_REGFILE_H__

#include <stdint.h>

#define AON_CTRL_AON_CHIP_VER_OFFSET                0x000
#define AON_CTRL_AON_CHIP_VER_AON_CHIP_VER_Pos      0
#define AON_CTRL_AON_CHIP_VER_AON_CHIP_VER_Msk      0xffffffff

#define AON_CTRL_DFT_CTRL_OFFSET                    0x004
#define AON_CTRL_DFT_CTRL_TEST_RSVD1_Pos            1
#define AON_CTRL_DFT_CTRL_TEST_RSVD1_Msk            0xfffffffe
#define AON_CTRL_DFT_CTRL_DFT_MODE_Pos              0
#define AON_CTRL_DFT_CTRL_DFT_MODE_Msk              0x1

#define AON_CTRL_PWON_CNT_CFG0_OFFSET               0x008
#define AON_CTRL_PWON_CNT_CFG0_PWON_CNT2_Pos        16
#define AON_CTRL_PWON_CNT_CFG0_PWON_CNT2_Msk        0x3f0000
#define AON_CTRL_PWON_CNT_CFG0_PWON_CNT1_Pos        8
#define AON_CTRL_PWON_CNT_CFG0_PWON_CNT1_Msk        0x3f00
#define AON_CTRL_PWON_CNT_CFG0_PWON_CNT0_Pos        0
#define AON_CTRL_PWON_CNT_CFG0_PWON_CNT0_Msk        0x3f

#define AON_CTRL_PWON_CNT_CFG1_OFFSET               0x00C
#define AON_CTRL_PWON_CNT_CFG1_PWON_CNT4_Pos        16
#define AON_CTRL_PWON_CNT_CFG1_PWON_CNT4_Msk        0x3f0000
#define AON_CTRL_PWON_CNT_CFG1_PWON_CNT3_Pos        0
#define AON_CTRL_PWON_CNT_CFG1_PWON_CNT3_Msk        0x3f

#define AON_CTRL_WAKEUP_ENABLE_OFFSET               0x010
#define AON_CTRL_WAKEUP_ENABLE_ENA_GPIO_WAKEUP_Pos    8
#define AON_CTRL_WAKEUP_ENABLE_ENA_GPIO_WAKEUP_Msk    0x1fff00
#define AON_CTRL_WAKEUP_ENABLE_ENA_KEY_WAKEUP_Pos    2
#define AON_CTRL_WAKEUP_ENABLE_ENA_KEY_WAKEUP_Msk    0x4
#define AON_CTRL_WAKEUP_ENABLE_ENA_IWDT_WAKEUP_Pos    1
#define AON_CTRL_WAKEUP_ENABLE_ENA_IWDT_WAKEUP_Msk    0x2
#define AON_CTRL_WAKEUP_ENABLE_ENA_TIMER_WAKEUP_Pos    0
#define AON_CTRL_WAKEUP_ENABLE_ENA_TIMER_WAKEUP_Msk    0x1

#define AON_CTRL_WAKEUP_IRSR_OFFSET                 0x014
#define AON_CTRL_WAKEUP_IRSR_GPIO_WAKEUP_IRSR_Pos    8
#define AON_CTRL_WAKEUP_IRSR_GPIO_WAKEUP_IRSR_Msk    0x1fff00
#define AON_CTRL_WAKEUP_IRSR_KEY_WAKEUP_IRSR_Pos    2
#define AON_CTRL_WAKEUP_IRSR_KEY_WAKEUP_IRSR_Msk    0x4
#define AON_CTRL_WAKEUP_IRSR_IWDT_WAKEUP_IRSR_Pos    1
#define AON_CTRL_WAKEUP_IRSR_IWDT_WAKEUP_IRSR_Msk    0x2
#define AON_CTRL_WAKEUP_IRSR_TIMER_WAKEUP_IRSR_Pos    0
#define AON_CTRL_WAKEUP_IRSR_TIMER_WAKEUP_IRSR_Msk    0x1

#define AON_CTRL_WAKEUP_IMR_OFFSET                  0x018
#define AON_CTRL_WAKEUP_IMR_GPIO_WAKEUP_IMR_Pos     8
#define AON_CTRL_WAKEUP_IMR_GPIO_WAKEUP_IMR_Msk     0x1fff00
#define AON_CTRL_WAKEUP_IMR_KEY_WAKEUP_IMR_Pos      2
#define AON_CTRL_WAKEUP_IMR_KEY_WAKEUP_IMR_Msk      0x4
#define AON_CTRL_WAKEUP_IMR_IWDT_WAKEUP_IMR_Pos     1
#define AON_CTRL_WAKEUP_IMR_IWDT_WAKEUP_IMR_Msk     0x2
#define AON_CTRL_WAKEUP_IMR_TIMER_WAKEUP_IMR_Pos    0
#define AON_CTRL_WAKEUP_IMR_TIMER_WAKEUP_IMR_Msk    0x1

#define AON_CTRL_WAKEUP_ICR_OFFSET                  0x01C
#define AON_CTRL_WAKEUP_ICR_GPIO_WAKEUP_ICR_Pos     8
#define AON_CTRL_WAKEUP_ICR_GPIO_WAKEUP_ICR_Msk     0x1fff00
#define AON_CTRL_WAKEUP_ICR_KEY_WAKEUP_ICR_Pos      2
#define AON_CTRL_WAKEUP_ICR_KEY_WAKEUP_ICR_Msk      0x4
#define AON_CTRL_WAKEUP_ICR_IWDT_WAKEUP_ICR_Pos     1
#define AON_CTRL_WAKEUP_ICR_IWDT_WAKEUP_ICR_Msk     0x2
#define AON_CTRL_WAKEUP_ICR_TIMER_WAKEUP_ICR_Pos    0
#define AON_CTRL_WAKEUP_ICR_TIMER_WAKEUP_ICR_Msk    0x1

#define AON_CTRL_WAKEUP_ISR_OFFSET                  0x020
#define AON_CTRL_WAKEUP_ISR_GPIO_WAKEUP_ISR_Pos     8
#define AON_CTRL_WAKEUP_ISR_GPIO_WAKEUP_ISR_Msk     0x1fff00
#define AON_CTRL_WAKEUP_ISR_KEY_WAKEUP_ISR_Pos      2
#define AON_CTRL_WAKEUP_ISR_KEY_WAKEUP_ISR_Msk      0x4
#define AON_CTRL_WAKEUP_ISR_IWDT_WAKEUP_ISR_Pos     1
#define AON_CTRL_WAKEUP_ISR_IWDT_WAKEUP_ISR_Msk     0x2
#define AON_CTRL_WAKEUP_ISR_TIMER_WAKEUP_ISR_Pos    0
#define AON_CTRL_WAKEUP_ISR_TIMER_WAKEUP_ISR_Msk    0x1

#define AON_CTRL_SLEEP_MODE_OFFSET                  0x024
#define AON_CTRL_SLEEP_MODE_ENA_DEEPSLEEP_Pos       3
#define AON_CTRL_SLEEP_MODE_ENA_DEEPSLEEP_Msk       0x8
#define AON_CTRL_SLEEP_MODE_PW_MODE2_PD_RCO32K_Pos    2
#define AON_CTRL_SLEEP_MODE_PW_MODE2_PD_RCO32K_Msk    0x4
#define AON_CTRL_SLEEP_MODE_ENA_PWMODE_Pos          0
#define AON_CTRL_SLEEP_MODE_ENA_PWMODE_Msk          0x3

#define AON_CTRL_GPIO_WAKEUP_CTRL_OFFSET            0x028
#define AON_CTRL_GPIO_WAKEUP_CTRL_ENA_GPIO_WAKEUP_CTRL_Pos    31
#define AON_CTRL_GPIO_WAKEUP_CTRL_ENA_GPIO_WAKEUP_CTRL_Msk    0x80000000
#define AON_CTRL_GPIO_WAKEUP_CTRL_MSK_RELEASE_WAKEUP_IN_PR_MODE_Pos    30
#define AON_CTRL_GPIO_WAKEUP_CTRL_MSK_RELEASE_WAKEUP_IN_PR_MODE_Msk    0x40000000
#define AON_CTRL_GPIO_WAKEUP_CTRL_ENA_PRESS_IRQ_IN_PR_MODE_Pos    29
#define AON_CTRL_GPIO_WAKEUP_CTRL_ENA_PRESS_IRQ_IN_PR_MODE_Msk    0x20000000
#define AON_CTRL_GPIO_WAKEUP_CTRL_GPIO_WAKEUP_DB_STATUS_Pos    28
#define AON_CTRL_GPIO_WAKEUP_CTRL_GPIO_WAKEUP_DB_STATUS_Msk    0x10000000
#define AON_CTRL_GPIO_WAKEUP_CTRL_PRESSN_RELEASE_MODE_Pos    15
#define AON_CTRL_GPIO_WAKEUP_CTRL_PRESSN_RELEASE_MODE_Msk    0x8000
#define AON_CTRL_GPIO_WAKEUP_CTRL_GPIO_DB_CNT_Pos    0
#define AON_CTRL_GPIO_WAKEUP_CTRL_GPIO_DB_CNT_Msk    0x7fff

#define AON_CTRL_GPIO_CTRL_POL_OFFSET               0x02C
#define AON_CTRL_GPIO_CTRL_POL_GPIO_WAKEUP_POL_Pos    0
#define AON_CTRL_GPIO_CTRL_POL_GPIO_WAKEUP_POL_Msk    0x1fff

#define AON_CTRL_GPIO_CTRL_DB_ENA_OFFSET            0x030
#define AON_CTRL_GPIO_CTRL_DB_ENA_GPIO_WAKEUP_DB_DIS_Pos    0
#define AON_CTRL_GPIO_CTRL_DB_ENA_GPIO_WAKEUP_DB_DIS_Msk    0x1fff

#define AON_CTRL_GPIO_STATUS_OFFSET                 0x034
#define AON_CTRL_GPIO_STATUS_GPIO_STATUS_Pos        0
#define AON_CTRL_GPIO_STATUS_GPIO_STATUS_Msk        0x1fff

#define AON_CTRL_AON_GPIO_OUT_OFFSET                0x038
#define AON_CTRL_AON_GPIO_OUT_AON_GPIO_OUT_Pos      0
#define AON_CTRL_AON_GPIO_OUT_AON_GPIO_OUT_Msk      0x1fff

#define AON_CTRL_RAM_RETENTION_CTRL_OFFSET          0x03C
#define AON_CTRL_RAM_RETENTION_CTRL_RAM_RETENTION_ENABLE_Pos    1
#define AON_CTRL_RAM_RETENTION_CTRL_RAM_RETENTION_ENABLE_Msk    0x2
#define AON_CTRL_RAM_RETENTION_CTRL_RAM_RETENTION_MODE_Pos    0
#define AON_CTRL_RAM_RETENTION_CTRL_RAM_RETENTION_MODE_Msk    0x1

#define AON_CTRL_CHECK_UVLO_ENABLE_OFFSET           0x040
#define AON_CTRL_CHECK_UVLO_ENABLE_CHECK_UVLO_Pos    0
#define AON_CTRL_CHECK_UVLO_ENABLE_CHECK_UVLO_Msk    0xffff

#define AON_CTRL_SYSRST_STATUS_OFFSET               0x044
#define AON_CTRL_SYSRST_STATUS_SYS_RST_CAUSE_1_Pos    17
#define AON_CTRL_SYSRST_STATUS_SYS_RST_CAUSE_1_Msk    0x20000
#define AON_CTRL_SYSRST_STATUS_SYS_RST_CAUSE_0_Pos    16
#define AON_CTRL_SYSRST_STATUS_SYS_RST_CAUSE_0_Msk    0x10000
#define AON_CTRL_SYSRST_STATUS_AON_RST_STATUS_Pos    1
#define AON_CTRL_SYSRST_STATUS_AON_RST_STATUS_Msk    0x2
#define AON_CTRL_SYSRST_STATUS_POR_STATUS_Pos       0
#define AON_CTRL_SYSRST_STATUS_POR_STATUS_Msk       0x1

#define AON_CTRL_SLEEP_MODE_ENTRY_OFFSET            0x048
#define AON_CTRL_SLEEP_MODE_ENTRY_SW_ENTER_SLEEP_Pos    0
#define AON_CTRL_SLEEP_MODE_ENTRY_SW_ENTER_SLEEP_Msk    0x1

#define AON_CTRL_AON_SW_RESET_OFFSET                0x04C
#define AON_CTRL_AON_SW_RESET_AON_RESET_Pos         0
#define AON_CTRL_AON_SW_RESET_AON_RESET_Msk         0x1

#define AON_CTRL_AON_CLK_CTRL_OFFSET                0x050
#define AON_CTRL_AON_CLK_CTRL_ENA_AON_IOMUX_CLK_Pos    3
#define AON_CTRL_AON_CLK_CTRL_ENA_AON_IOMUX_CLK_Msk    0x8
#define AON_CTRL_AON_CLK_CTRL_SEL_RC_XTAL_32K_CLK_Pos    2
#define AON_CTRL_AON_CLK_CTRL_SEL_RC_XTAL_32K_CLK_Msk    0x4
#define AON_CTRL_AON_CLK_CTRL_ENA_AON_TIMER_CLK_Pos    1
#define AON_CTRL_AON_CLK_CTRL_ENA_AON_TIMER_CLK_Msk    0x2
#define AON_CTRL_AON_CLK_CTRL_ENA_KEYSENSE_CLK_Pos    0
#define AON_CTRL_AON_CLK_CTRL_ENA_KEYSENSE_CLK_Msk    0x1

#define AON_CTRL_AON_RST_CTRL_OFFSET                0x054
#define AON_CTRL_AON_RST_CTRL_AON_TIMER_RESET_Pos    1
#define AON_CTRL_AON_RST_CTRL_AON_TIMER_RESET_Msk    0x2
#define AON_CTRL_AON_RST_CTRL_KEYSENSE_RESET_Pos    0
#define AON_CTRL_AON_RST_CTRL_KEYSENSE_RESET_Msk    0x1

#define AON_CTRL_KEYSENSE_CTRL_OFFSET               0x058
#define AON_CTRL_KEYSENSE_CTRL_KEYIN_DETECT_EN_Pos    0
#define AON_CTRL_KEYSENSE_CTRL_KEYIN_DETECT_EN_Msk    0x1

#define AON_CTRL_GPADC_VDD_IO_DIV_SEL_OFFSET        0x05C
#define AON_CTRL_GPADC_VDD_IO_DIV_SEL_GPADC_VDD_IO_DIV_SEL_Pos    0
#define AON_CTRL_GPADC_VDD_IO_DIV_SEL_GPADC_VDD_IO_DIV_SEL_Msk    0x1

#define AON_CTRL_XO24M_CTRL_OFFSET                  0x060
#define AON_CTRL_XO24M_CTRL_XO24M_IBIT_Pos          24
#define AON_CTRL_XO24M_CTRL_XO24M_IBIT_Msk          0xf000000
#define AON_CTRL_XO24M_CTRL_XO24M_AMP_Pos           21
#define AON_CTRL_XO24M_CTRL_XO24M_AMP_Msk           0xe00000
#define AON_CTRL_XO24M_CTRL_XO24M_CAP_REG_Pos       16
#define AON_CTRL_XO24M_CTRL_XO24M_CAP_REG_Msk       0x1f0000
#define AON_CTRL_XO24M_CTRL_XO24M_INI_CNT1_Pos      9
#define AON_CTRL_XO24M_CTRL_XO24M_INI_CNT1_Msk      0xfe00
#define AON_CTRL_XO24M_CTRL_XO24M_INI_CNT_Pos       2
#define AON_CTRL_XO24M_CTRL_XO24M_INI_CNT_Msk       0x1fc
#define AON_CTRL_XO24M_CTRL_XO24M_IS_READY_Pos      1
#define AON_CTRL_XO24M_CTRL_XO24M_IS_READY_Msk      0x2
#define AON_CTRL_XO24M_CTRL_ENA_XO24M_SW_Pos        0
#define AON_CTRL_XO24M_CTRL_ENA_XO24M_SW_Msk        0x1

#define AON_CTRL_OSC24M_CTRL_OFFSET                 0x064
#define AON_CTRL_OSC24M_CTRL_OSC24M_RCO_IB_SEL_Pos    20
#define AON_CTRL_OSC24M_CTRL_OSC24M_RCO_IB_SEL_Msk    0x1f00000
#define AON_CTRL_OSC24M_CTRL_OSC24M_OSC_TRIM3_Pos    16
#define AON_CTRL_OSC24M_CTRL_OSC24M_OSC_TRIM3_Msk    0xf0000
#define AON_CTRL_OSC24M_CTRL_OSC24M_OSC_TRIM2_Pos    11
#define AON_CTRL_OSC24M_CTRL_OSC24M_OSC_TRIM2_Msk    0xf800
#define AON_CTRL_OSC24M_CTRL_OSC24M_OSC_TRIM1_Pos    6
#define AON_CTRL_OSC24M_CTRL_OSC24M_OSC_TRIM1_Msk    0x7c0
#define AON_CTRL_OSC24M_CTRL_OSC24M_OSC_LDO_TRIM_Pos    2
#define AON_CTRL_OSC24M_CTRL_OSC24M_OSC_LDO_TRIM_Msk    0x3c
#define AON_CTRL_OSC24M_CTRL_OSC24M_EN_RCO_TEST_VR_Pos    1
#define AON_CTRL_OSC24M_CTRL_OSC24M_EN_RCO_TEST_VR_Msk    0x2
#define AON_CTRL_OSC24M_CTRL_OSC24M_EN_OSC_LDO_BYPASS_Pos    0
#define AON_CTRL_OSC24M_CTRL_OSC24M_EN_OSC_LDO_BYPASS_Msk    0x1

#define AON_CTRL_AON_TUNE0_OFFSET                   0x068
#define AON_CTRL_AON_TUNE0_TUNE_LDO_VRAM_Pos        13
#define AON_CTRL_AON_TUNE0_TUNE_LDO_VRAM_Msk        0x7e000
#define AON_CTRL_AON_TUNE0_TUNE_LDO_VAON_Pos        7
#define AON_CTRL_AON_TUNE0_TUNE_LDO_VAON_Msk        0x1f80
#define AON_CTRL_AON_TUNE0_LDO_VAON_SEL_Pos         6
#define AON_CTRL_AON_TUNE0_LDO_VAON_SEL_Msk         0x40
#define AON_CTRL_AON_TUNE0_TUNE_BG_AON_Pos          0
#define AON_CTRL_AON_TUNE0_TUNE_BG_AON_Msk          0x3f

#define AON_CTRL_AON_TUNE1_OFFSET                   0x06C
#define AON_CTRL_AON_TUNE1_EN_FC_LDO_VA_Pos         23
#define AON_CTRL_AON_TUNE1_EN_FC_LDO_VA_Msk         0x800000
#define AON_CTRL_AON_TUNE1_EN_CURLIMIT_HVLDO_VIO_Pos    22
#define AON_CTRL_AON_TUNE1_EN_CURLIMIT_HVLDO_VIO_Msk    0x400000
#define AON_CTRL_AON_TUNE1_TUNE_HVLDO_VIO_Pos       17
#define AON_CTRL_AON_TUNE1_TUNE_HVLDO_VIO_Msk       0x3e0000
#define AON_CTRL_AON_TUNE1_VIO_OK_S_Pos             16
#define AON_CTRL_AON_TUNE1_VIO_OK_S_Msk             0x10000
#define AON_CTRL_AON_TUNE1_PROG_UVLO_Pos            15
#define AON_CTRL_AON_TUNE1_PROG_UVLO_Msk            0x8000
#define AON_CTRL_AON_TUNE1_ENTEST_UVLO_VIO_Pos      14
#define AON_CTRL_AON_TUNE1_ENTEST_UVLO_VIO_Msk      0x4000
#define AON_CTRL_AON_TUNE1_TUNE_UVLO_VIO_Pos        8
#define AON_CTRL_AON_TUNE1_TUNE_UVLO_VIO_Msk        0x3f00
#define AON_CTRL_AON_TUNE1_BG_TEST_SEL_Pos          6
#define AON_CTRL_AON_TUNE1_BG_TEST_SEL_Msk          0xc0
#define AON_CTRL_AON_TUNE1_RCO32K_RTRIM_Pos         0
#define AON_CTRL_AON_TUNE1_RCO32K_RTRIM_Msk         0x3f

#define AON_CTRL_AON_TUNE2_OFFSET                   0x070
#define AON_CTRL_AON_TUNE2_HVLDO_BYPASS_EN_Pos      29
#define AON_CTRL_AON_TUNE2_HVLDO_BYPASS_EN_Msk      0x20000000
#define AON_CTRL_AON_TUNE2_EN_LDO_VA_Pos            28
#define AON_CTRL_AON_TUNE2_EN_LDO_VA_Msk            0x10000000
#define AON_CTRL_AON_TUNE2_EN_CURLIMIT_LDO_VA_Pos    27
#define AON_CTRL_AON_TUNE2_EN_CURLIMIT_LDO_VA_Msk    0x8000000
#define AON_CTRL_AON_TUNE2_EN_CAPLESS_LDO_VA_Pos    26
#define AON_CTRL_AON_TUNE2_EN_CAPLESS_LDO_VA_Msk    0x4000000
#define AON_CTRL_AON_TUNE2_TUNE_LDO_VA_Pos          22
#define AON_CTRL_AON_TUNE2_TUNE_LDO_VA_Msk          0x3c00000
#define AON_CTRL_AON_TUNE2_TESTEN_DET_VCC_Pos       21
#define AON_CTRL_AON_TUNE2_TESTEN_DET_VCC_Msk       0x200000
#define AON_CTRL_AON_TUNE2_TUNE_DET_VCC_Pos         16
#define AON_CTRL_AON_TUNE2_TUNE_DET_VCC_Msk         0x1f0000
#define AON_CTRL_AON_TUNE2_EN_DET_VCC_Pos           15
#define AON_CTRL_AON_TUNE2_EN_DET_VCC_Msk           0x8000
#define AON_CTRL_AON_TUNE2_DET_VCC_FLAG_Pos         14
#define AON_CTRL_AON_TUNE2_DET_VCC_FLAG_Msk         0x4000
#define AON_CTRL_AON_TUNE2_TUNE_LDO_CORE_Pos        8
#define AON_CTRL_AON_TUNE2_TUNE_LDO_CORE_Msk        0x3f00
#define AON_CTRL_AON_TUNE2_EN_CURLIMIT_LDO_CORE_Pos    7
#define AON_CTRL_AON_TUNE2_EN_CURLIMIT_LDO_CORE_Msk    0x80
#define AON_CTRL_AON_TUNE2_TUNE_BG_FINE_Pos         0
#define AON_CTRL_AON_TUNE2_TUNE_BG_FINE_Msk         0x7f

#define AON_CTRL_AON_ANA_RSVD_OFFSET                0x074
#define AON_CTRL_AON_ANA_RSVD_AON_ANA_RSVD_Pos      0
#define AON_CTRL_AON_ANA_RSVD_AON_ANA_RSVD_Msk      0xff

#define AON_CTRL_AON_DIG_RSVD_OFFSET                0x078
#define AON_CTRL_AON_DIG_RSVD_AON_DIG_RSVD_Pos      0
#define AON_CTRL_AON_DIG_RSVD_AON_DIG_RSVD_Msk      0xffffffff

#define AON_CTRL_AON_FORCE_CTRL_OFFSET              0x07C
#define AON_CTRL_AON_FORCE_CTRL_ISO_CORE_FRC_Pos    16
#define AON_CTRL_AON_FORCE_CTRL_ISO_CORE_FRC_Msk    0x10000
#define AON_CTRL_AON_FORCE_CTRL_RAM_RET1N_FRC_Pos    15
#define AON_CTRL_AON_FORCE_CTRL_RAM_RET1N_FRC_Msk    0x8000
#define AON_CTRL_AON_FORCE_CTRL_RAM_RET2N_FRC_Pos    14
#define AON_CTRL_AON_FORCE_CTRL_RAM_RET2N_FRC_Msk    0x4000
#define AON_CTRL_AON_FORCE_CTRL_RAM_PGEN_FRC_Pos    13
#define AON_CTRL_AON_FORCE_CTRL_RAM_PGEN_FRC_Msk    0x2000
#define AON_CTRL_AON_FORCE_CTRL_XO24M_BUF_EN_FRC_Pos    12
#define AON_CTRL_AON_FORCE_CTRL_XO24M_BUF_EN_FRC_Msk    0x1000
#define AON_CTRL_AON_FORCE_CTRL_EN_LDO_VRAM_FRC_Pos    11
#define AON_CTRL_AON_FORCE_CTRL_EN_LDO_VRAM_FRC_Msk    0x800
#define AON_CTRL_AON_FORCE_CTRL_XO24M_CORE_EN_FRC_Pos    10
#define AON_CTRL_AON_FORCE_CTRL_XO24M_CORE_EN_FRC_Msk    0x400
#define AON_CTRL_AON_FORCE_CTRL_XO24M_BUF_CORE_EN_FRC_Pos    9
#define AON_CTRL_AON_FORCE_CTRL_XO24M_BUF_CORE_EN_FRC_Msk    0x200
#define AON_CTRL_AON_FORCE_CTRL_OSC24M_EN_OSC_TOP_FRC_Pos    8
#define AON_CTRL_AON_FORCE_CTRL_OSC24M_EN_OSC_TOP_FRC_Msk    0x100
#define AON_CTRL_AON_FORCE_CTRL_OSC24M_EN_CORE_FRC_Pos    7
#define AON_CTRL_AON_FORCE_CTRL_OSC24M_EN_CORE_FRC_Msk    0x80
#define AON_CTRL_AON_FORCE_CTRL_EN_LDO_CORE_FRC_Pos    6
#define AON_CTRL_AON_FORCE_CTRL_EN_LDO_CORE_FRC_Msk    0x40
#define AON_CTRL_AON_FORCE_CTRL_ISO_ANA_FRC_Pos     5
#define AON_CTRL_AON_FORCE_CTRL_ISO_ANA_FRC_Msk     0x20
#define AON_CTRL_AON_FORCE_CTRL_EN_BG_FINE_FRC_Pos    4
#define AON_CTRL_AON_FORCE_CTRL_EN_BG_FINE_FRC_Msk    0x10
#define AON_CTRL_AON_FORCE_CTRL_EN_UVLO_VIO_FRC_Pos    3
#define AON_CTRL_AON_FORCE_CTRL_EN_UVLO_VIO_FRC_Msk    0x8
#define AON_CTRL_AON_FORCE_CTRL_RCO32K_PD_FRC_Pos    2
#define AON_CTRL_AON_FORCE_CTRL_RCO32K_PD_FRC_Msk    0x4
#define AON_CTRL_AON_FORCE_CTRL_NORMON_VREF_LDO_VRAM_FRC_Pos    1
#define AON_CTRL_AON_FORCE_CTRL_NORMON_VREF_LDO_VRAM_FRC_Msk    0x2
#define AON_CTRL_AON_FORCE_CTRL_XO24M_CAP_FRC_Pos    0
#define AON_CTRL_AON_FORCE_CTRL_XO24M_CAP_FRC_Msk    0x1

#define AON_CTRL_AON_FORCE_DATA_OFFSET              0x080
#define AON_CTRL_AON_FORCE_DATA_ISO_CORE_FRCDATA_Pos    20
#define AON_CTRL_AON_FORCE_DATA_ISO_CORE_FRCDATA_Msk    0x100000
#define AON_CTRL_AON_FORCE_DATA_RAM_RET1N_FRCDATA_Pos    19
#define AON_CTRL_AON_FORCE_DATA_RAM_RET1N_FRCDATA_Msk    0x80000
#define AON_CTRL_AON_FORCE_DATA_RAM_RET2N_FRCDATA_Pos    18
#define AON_CTRL_AON_FORCE_DATA_RAM_RET2N_FRCDATA_Msk    0x40000
#define AON_CTRL_AON_FORCE_DATA_RAM_PGEN_FRCDATA_Pos    17
#define AON_CTRL_AON_FORCE_DATA_RAM_PGEN_FRCDATA_Msk    0x20000
#define AON_CTRL_AON_FORCE_DATA_XO24M_BUF_EN_FRCDATA_Pos    16
#define AON_CTRL_AON_FORCE_DATA_XO24M_BUF_EN_FRCDATA_Msk    0x10000
#define AON_CTRL_AON_FORCE_DATA_EN_LDO_VRAM_FRCDATA_Pos    15
#define AON_CTRL_AON_FORCE_DATA_EN_LDO_VRAM_FRCDATA_Msk    0x8000
#define AON_CTRL_AON_FORCE_DATA_XO24M_CORE_EN_FRCDATA_Pos    14
#define AON_CTRL_AON_FORCE_DATA_XO24M_CORE_EN_FRCDATA_Msk    0x4000
#define AON_CTRL_AON_FORCE_DATA_XO24M_BUF_CORE_EN_FRCDATA_Pos    13
#define AON_CTRL_AON_FORCE_DATA_XO24M_BUF_CORE_EN_FRCDATA_Msk    0x2000
#define AON_CTRL_AON_FORCE_DATA_OSC24M_EN_OSC_TOP_FRCDATA_Pos    12
#define AON_CTRL_AON_FORCE_DATA_OSC24M_EN_OSC_TOP_FRCDATA_Msk    0x1000
#define AON_CTRL_AON_FORCE_DATA_OSC24M_EN_CORE_FRCDATA_Pos    11
#define AON_CTRL_AON_FORCE_DATA_OSC24M_EN_CORE_FRCDATA_Msk    0x800
#define AON_CTRL_AON_FORCE_DATA_EN_LDO_CORE_FRCDATA_Pos    10
#define AON_CTRL_AON_FORCE_DATA_EN_LDO_CORE_FRCDATA_Msk    0x400
#define AON_CTRL_AON_FORCE_DATA_ISO_ANA_FRCDATA_Pos    9
#define AON_CTRL_AON_FORCE_DATA_ISO_ANA_FRCDATA_Msk    0x200
#define AON_CTRL_AON_FORCE_DATA_EN_BG_FINE_FRCDATA_Pos    8
#define AON_CTRL_AON_FORCE_DATA_EN_BG_FINE_FRCDATA_Msk    0x100
#define AON_CTRL_AON_FORCE_DATA_EN_UVLO_VIO_FRCDATA_Pos    7
#define AON_CTRL_AON_FORCE_DATA_EN_UVLO_VIO_FRCDATA_Msk    0x80
#define AON_CTRL_AON_FORCE_DATA_RCO32K_PD_FRCDATA_Pos    6
#define AON_CTRL_AON_FORCE_DATA_RCO32K_PD_FRCDATA_Msk    0x40
#define AON_CTRL_AON_FORCE_DATA_NORMON_VREF_LDO_VRAM_FRCDATA_Pos    5
#define AON_CTRL_AON_FORCE_DATA_NORMON_VREF_LDO_VRAM_FRCDATA_Msk    0x20
#define AON_CTRL_AON_FORCE_DATA_XO24M_CAP_FRCDATA_Pos    0
#define AON_CTRL_AON_FORCE_DATA_XO24M_CAP_FRCDATA_Msk    0x1f

struct AON_CTRL_REG_AON_CHIP_VER_BITS
{
    volatile uint32_t AON_CHIP_VER                  : 32; // bit 0~31
};

union AON_CTRL_REG_AON_CHIP_VER {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_CHIP_VER_BITS           bit;
};

struct AON_CTRL_REG_DFT_CTRL_BITS
{
    volatile uint32_t DFT_MODE                      : 1; // bit 0~0
    volatile uint32_t TEST_RSVD1                    : 31; // bit 1~31
};

union AON_CTRL_REG_DFT_CTRL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_DFT_CTRL_BITS               bit;
};

struct AON_CTRL_REG_PWON_CNT_CFG0_BITS
{
    volatile uint32_t PWON_CNT0                     : 6; // bit 0~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t PWON_CNT1                     : 6; // bit 8~13
    volatile uint32_t RESV_14_15                    : 2; // bit 14~15
    volatile uint32_t PWON_CNT2                     : 6; // bit 16~21
    volatile uint32_t RESV_22_31                    : 10; // bit 22~31
};

union AON_CTRL_REG_PWON_CNT_CFG0 {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_PWON_CNT_CFG0_BITS          bit;
};

struct AON_CTRL_REG_PWON_CNT_CFG1_BITS
{
    volatile uint32_t PWON_CNT3                     : 6; // bit 0~5
    volatile uint32_t RESV_6_15                     : 10; // bit 6~15
    volatile uint32_t PWON_CNT4                     : 6; // bit 16~21
    volatile uint32_t RESV_22_31                    : 10; // bit 22~31
};

union AON_CTRL_REG_PWON_CNT_CFG1 {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_PWON_CNT_CFG1_BITS          bit;
};

struct AON_CTRL_REG_WAKEUP_ENABLE_BITS
{
    volatile uint32_t ENA_TIMER_WAKEUP              : 1; // bit 0~0
    volatile uint32_t ENA_IWDT_WAKEUP               : 1; // bit 1~1
    volatile uint32_t ENA_KEY_WAKEUP                : 1; // bit 2~2
    volatile uint32_t RESV_3_7                      : 5; // bit 3~7
    volatile uint32_t ENA_GPIO_WAKEUP               : 13; // bit 8~20
    volatile uint32_t RESV_21_31                    : 11; // bit 21~31
};

union AON_CTRL_REG_WAKEUP_ENABLE {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_WAKEUP_ENABLE_BITS          bit;
};

struct AON_CTRL_REG_WAKEUP_IRSR_BITS
{
    volatile uint32_t TIMER_WAKEUP_IRSR             : 1; // bit 0~0
    volatile uint32_t IWDT_WAKEUP_IRSR              : 1; // bit 1~1
    volatile uint32_t KEY_WAKEUP_IRSR               : 1; // bit 2~2
    volatile uint32_t RESV_3_7                      : 5; // bit 3~7
    volatile uint32_t GPIO_WAKEUP_IRSR              : 13; // bit 8~20
    volatile uint32_t RESV_21_31                    : 11; // bit 21~31
};

union AON_CTRL_REG_WAKEUP_IRSR {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_WAKEUP_IRSR_BITS            bit;
};

struct AON_CTRL_REG_WAKEUP_IMR_BITS
{
    volatile uint32_t TIMER_WAKEUP_IMR              : 1; // bit 0~0
    volatile uint32_t IWDT_WAKEUP_IMR               : 1; // bit 1~1
    volatile uint32_t KEY_WAKEUP_IMR                : 1; // bit 2~2
    volatile uint32_t RESV_3_7                      : 5; // bit 3~7
    volatile uint32_t GPIO_WAKEUP_IMR               : 13; // bit 8~20
    volatile uint32_t RESV_21_31                    : 11; // bit 21~31
};

union AON_CTRL_REG_WAKEUP_IMR {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_WAKEUP_IMR_BITS             bit;
};

struct AON_CTRL_REG_WAKEUP_ICR_BITS
{
    volatile uint32_t TIMER_WAKEUP_ICR              : 1; // bit 0~0
    volatile uint32_t IWDT_WAKEUP_ICR               : 1; // bit 1~1
    volatile uint32_t KEY_WAKEUP_ICR                : 1; // bit 2~2
    volatile uint32_t RESV_3_7                      : 5; // bit 3~7
    volatile uint32_t GPIO_WAKEUP_ICR               : 13; // bit 8~20
    volatile uint32_t RESV_21_31                    : 11; // bit 21~31
};

union AON_CTRL_REG_WAKEUP_ICR {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_WAKEUP_ICR_BITS             bit;
};

struct AON_CTRL_REG_WAKEUP_ISR_BITS
{
    volatile uint32_t TIMER_WAKEUP_ISR              : 1; // bit 0~0
    volatile uint32_t IWDT_WAKEUP_ISR               : 1; // bit 1~1
    volatile uint32_t KEY_WAKEUP_ISR                : 1; // bit 2~2
    volatile uint32_t RESV_3_7                      : 5; // bit 3~7
    volatile uint32_t GPIO_WAKEUP_ISR               : 13; // bit 8~20
    volatile uint32_t RESV_21_31                    : 11; // bit 21~31
};

union AON_CTRL_REG_WAKEUP_ISR {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_WAKEUP_ISR_BITS             bit;
};

struct AON_CTRL_REG_SLEEP_MODE_BITS
{
    volatile uint32_t ENA_PWMODE                    : 2; // bit 0~1
    volatile uint32_t PW_MODE2_PD_RCO32K            : 1; // bit 2~2
    volatile uint32_t ENA_DEEPSLEEP                 : 1; // bit 3~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union AON_CTRL_REG_SLEEP_MODE {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_SLEEP_MODE_BITS             bit;
};

struct AON_CTRL_REG_GPIO_WAKEUP_CTRL_BITS
{
    volatile uint32_t GPIO_DB_CNT                   : 15; // bit 0~14
    volatile uint32_t PRESSN_RELEASE_MODE           : 1; // bit 15~15
    volatile uint32_t RESV_16_27                    : 12; // bit 16~27
    volatile uint32_t GPIO_WAKEUP_DB_STATUS         : 1; // bit 28~28
    volatile uint32_t ENA_PRESS_IRQ_IN_PR_MODE      : 1; // bit 29~29
    volatile uint32_t MSK_RELEASE_WAKEUP_IN_PR_MODE    : 1; // bit 30~30
    volatile uint32_t ENA_GPIO_WAKEUP_CTRL          : 1; // bit 31~31
};

union AON_CTRL_REG_GPIO_WAKEUP_CTRL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_GPIO_WAKEUP_CTRL_BITS       bit;
};

struct AON_CTRL_REG_GPIO_CTRL_POL_BITS
{
    volatile uint32_t GPIO_WAKEUP_POL               : 13; // bit 0~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union AON_CTRL_REG_GPIO_CTRL_POL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_GPIO_CTRL_POL_BITS          bit;
};

struct AON_CTRL_REG_GPIO_CTRL_DB_ENA_BITS
{
    volatile uint32_t GPIO_WAKEUP_DB_DIS            : 13; // bit 0~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union AON_CTRL_REG_GPIO_CTRL_DB_ENA {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_GPIO_CTRL_DB_ENA_BITS       bit;
};

struct AON_CTRL_REG_GPIO_STATUS_BITS
{
    volatile uint32_t GPIO_STATUS                   : 13; // bit 0~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union AON_CTRL_REG_GPIO_STATUS {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_GPIO_STATUS_BITS            bit;
};

struct AON_CTRL_REG_AON_GPIO_OUT_BITS
{
    volatile uint32_t AON_GPIO_OUT                  : 13; // bit 0~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union AON_CTRL_REG_AON_GPIO_OUT {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_GPIO_OUT_BITS           bit;
};

struct AON_CTRL_REG_RAM_RETENTION_CTRL_BITS
{
    volatile uint32_t RAM_RETENTION_MODE            : 1; // bit 0~0
    volatile uint32_t RAM_RETENTION_ENABLE          : 1; // bit 1~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union AON_CTRL_REG_RAM_RETENTION_CTRL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_RAM_RETENTION_CTRL_BITS     bit;
};

struct AON_CTRL_REG_CHECK_UVLO_ENABLE_BITS
{
    volatile uint32_t CHECK_UVLO                    : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union AON_CTRL_REG_CHECK_UVLO_ENABLE {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_CHECK_UVLO_ENABLE_BITS      bit;
};

struct AON_CTRL_REG_SYSRST_STATUS_BITS
{
    volatile uint32_t POR_STATUS                    : 1; // bit 0~0
    volatile uint32_t AON_RST_STATUS                : 1; // bit 1~1
    volatile uint32_t RESV_2_15                     : 14; // bit 2~15
    volatile uint32_t SYS_RST_CAUSE_0               : 1; // bit 16~16
    volatile uint32_t SYS_RST_CAUSE_1               : 1; // bit 17~17
    volatile uint32_t RESV_18_31                    : 14; // bit 18~31
};

union AON_CTRL_REG_SYSRST_STATUS {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_SYSRST_STATUS_BITS          bit;
};

struct AON_CTRL_REG_SLEEP_MODE_ENTRY_BITS
{
    volatile uint32_t SW_ENTER_SLEEP                : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union AON_CTRL_REG_SLEEP_MODE_ENTRY {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_SLEEP_MODE_ENTRY_BITS       bit;
};

struct AON_CTRL_REG_AON_SW_RESET_BITS
{
    volatile uint32_t AON_RESET                     : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union AON_CTRL_REG_AON_SW_RESET {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_SW_RESET_BITS           bit;
};

struct AON_CTRL_REG_AON_CLK_CTRL_BITS
{
    volatile uint32_t ENA_KEYSENSE_CLK              : 1; // bit 0~0
    volatile uint32_t ENA_AON_TIMER_CLK             : 1; // bit 1~1
    volatile uint32_t SEL_RC_XTAL_32K_CLK           : 1; // bit 2~2
    volatile uint32_t ENA_AON_IOMUX_CLK             : 1; // bit 3~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union AON_CTRL_REG_AON_CLK_CTRL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_CLK_CTRL_BITS           bit;
};

struct AON_CTRL_REG_AON_RST_CTRL_BITS
{
    volatile uint32_t KEYSENSE_RESET                : 1; // bit 0~0
    volatile uint32_t AON_TIMER_RESET               : 1; // bit 1~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union AON_CTRL_REG_AON_RST_CTRL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_RST_CTRL_BITS           bit;
};

struct AON_CTRL_REG_KEYSENSE_CTRL_BITS
{
    volatile uint32_t KEYIN_DETECT_EN               : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union AON_CTRL_REG_KEYSENSE_CTRL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_KEYSENSE_CTRL_BITS          bit;
};

struct AON_CTRL_REG_GPADC_VDD_IO_DIV_SEL_BITS
{
    volatile uint32_t GPADC_VDD_IO_DIV_SEL          : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union AON_CTRL_REG_GPADC_VDD_IO_DIV_SEL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_GPADC_VDD_IO_DIV_SEL_BITS    bit;
};

struct AON_CTRL_REG_XO24M_CTRL_BITS
{
    volatile uint32_t ENA_XO24M_SW                  : 1; // bit 0~0
    volatile uint32_t XO24M_IS_READY                : 1; // bit 1~1
    volatile uint32_t XO24M_INI_CNT                 : 7; // bit 2~8
    volatile uint32_t XO24M_INI_CNT1                : 7; // bit 9~15
    volatile uint32_t XO24M_CAP_REG                 : 5; // bit 16~20
    volatile uint32_t XO24M_AMP                     : 3; // bit 21~23
    volatile uint32_t XO24M_IBIT                    : 4; // bit 24~27
    volatile uint32_t RESV_28_31                    : 4; // bit 28~31
};

union AON_CTRL_REG_XO24M_CTRL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_XO24M_CTRL_BITS             bit;
};

struct AON_CTRL_REG_OSC24M_CTRL_BITS
{
    volatile uint32_t OSC24M_EN_OSC_LDO_BYPASS      : 1; // bit 0~0
    volatile uint32_t OSC24M_EN_RCO_TEST_VR         : 1; // bit 1~1
    volatile uint32_t OSC24M_OSC_LDO_TRIM           : 4; // bit 2~5
    volatile uint32_t OSC24M_OSC_TRIM1              : 5; // bit 6~10
    volatile uint32_t OSC24M_OSC_TRIM2              : 5; // bit 11~15
    volatile uint32_t OSC24M_OSC_TRIM3              : 4; // bit 16~19
    volatile uint32_t OSC24M_RCO_IB_SEL             : 5; // bit 20~24
    volatile uint32_t RESV_25_31                    : 7; // bit 25~31
};

union AON_CTRL_REG_OSC24M_CTRL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_OSC24M_CTRL_BITS            bit;
};

struct AON_CTRL_REG_AON_TUNE0_BITS
{
    volatile uint32_t TUNE_BG_AON                   : 6; // bit 0~5
    volatile uint32_t LDO_VAON_SEL                  : 1; // bit 6~6
    volatile uint32_t TUNE_LDO_VAON                 : 6; // bit 7~12
    volatile uint32_t TUNE_LDO_VRAM                 : 6; // bit 13~18
    volatile uint32_t RESV_19_31                    : 13; // bit 19~31
};

union AON_CTRL_REG_AON_TUNE0 {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_TUNE0_BITS              bit;
};

struct AON_CTRL_REG_AON_TUNE1_BITS
{
    volatile uint32_t RCO32K_RTRIM                  : 6; // bit 0~5
    volatile uint32_t BG_TEST_SEL                   : 2; // bit 6~7
    volatile uint32_t TUNE_UVLO_VIO                 : 6; // bit 8~13
    volatile uint32_t ENTEST_UVLO_VIO               : 1; // bit 14~14
    volatile uint32_t PROG_UVLO                     : 1; // bit 15~15
    volatile uint32_t VIO_OK_S                      : 1; // bit 16~16
    volatile uint32_t TUNE_HVLDO_VIO                : 5; // bit 17~21
    volatile uint32_t EN_CURLIMIT_HVLDO_VIO         : 1; // bit 22~22
    volatile uint32_t EN_FC_LDO_VA                  : 1; // bit 23~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union AON_CTRL_REG_AON_TUNE1 {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_TUNE1_BITS              bit;
};

struct AON_CTRL_REG_AON_TUNE2_BITS
{
    volatile uint32_t TUNE_BG_FINE                  : 7; // bit 0~6
    volatile uint32_t EN_CURLIMIT_LDO_CORE          : 1; // bit 7~7
    volatile uint32_t TUNE_LDO_CORE                 : 6; // bit 8~13
    volatile uint32_t DET_VCC_FLAG                  : 1; // bit 14~14
    volatile uint32_t EN_DET_VCC                    : 1; // bit 15~15
    volatile uint32_t TUNE_DET_VCC                  : 5; // bit 16~20
    volatile uint32_t TESTEN_DET_VCC                : 1; // bit 21~21
    volatile uint32_t TUNE_LDO_VA                   : 4; // bit 22~25
    volatile uint32_t EN_CAPLESS_LDO_VA             : 1; // bit 26~26
    volatile uint32_t EN_CURLIMIT_LDO_VA            : 1; // bit 27~27
    volatile uint32_t EN_LDO_VA                     : 1; // bit 28~28
    volatile uint32_t HVLDO_BYPASS_EN               : 1; // bit 29~29
    volatile uint32_t RESV_30_31                    : 2; // bit 30~31
};

union AON_CTRL_REG_AON_TUNE2 {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_TUNE2_BITS              bit;
};

struct AON_CTRL_REG_AON_ANA_RSVD_BITS
{
    volatile uint32_t AON_ANA_RSVD                  : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union AON_CTRL_REG_AON_ANA_RSVD {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_ANA_RSVD_BITS           bit;
};

struct AON_CTRL_REG_AON_DIG_RSVD_BITS
{
    volatile uint32_t AON_DIG_RSVD                  : 32; // bit 0~31
};

union AON_CTRL_REG_AON_DIG_RSVD {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_DIG_RSVD_BITS           bit;
};

struct AON_CTRL_REG_AON_FORCE_CTRL_BITS
{
    volatile uint32_t XO24M_CAP_FRC                 : 1; // bit 0~0
    volatile uint32_t NORMON_VREF_LDO_VRAM_FRC      : 1; // bit 1~1
    volatile uint32_t RCO32K_PD_FRC                 : 1; // bit 2~2
    volatile uint32_t EN_UVLO_VIO_FRC               : 1; // bit 3~3
    volatile uint32_t EN_BG_FINE_FRC                : 1; // bit 4~4
    volatile uint32_t ISO_ANA_FRC                   : 1; // bit 5~5
    volatile uint32_t EN_LDO_CORE_FRC               : 1; // bit 6~6
    volatile uint32_t OSC24M_EN_CORE_FRC            : 1; // bit 7~7
    volatile uint32_t OSC24M_EN_OSC_TOP_FRC         : 1; // bit 8~8
    volatile uint32_t XO24M_BUF_CORE_EN_FRC         : 1; // bit 9~9
    volatile uint32_t XO24M_CORE_EN_FRC             : 1; // bit 10~10
    volatile uint32_t EN_LDO_VRAM_FRC               : 1; // bit 11~11
    volatile uint32_t XO24M_BUF_EN_FRC              : 1; // bit 12~12
    volatile uint32_t RAM_PGEN_FRC                  : 1; // bit 13~13
    volatile uint32_t RAM_RET2N_FRC                 : 1; // bit 14~14
    volatile uint32_t RAM_RET1N_FRC                 : 1; // bit 15~15
    volatile uint32_t ISO_CORE_FRC                  : 1; // bit 16~16
    volatile uint32_t RESV_17_31                    : 15; // bit 17~31
};

union AON_CTRL_REG_AON_FORCE_CTRL {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_FORCE_CTRL_BITS         bit;
};

struct AON_CTRL_REG_AON_FORCE_DATA_BITS
{
    volatile uint32_t XO24M_CAP_FRCDATA             : 5; // bit 0~4
    volatile uint32_t NORMON_VREF_LDO_VRAM_FRCDATA    : 1; // bit 5~5
    volatile uint32_t RCO32K_PD_FRCDATA             : 1; // bit 6~6
    volatile uint32_t EN_UVLO_VIO_FRCDATA           : 1; // bit 7~7
    volatile uint32_t EN_BG_FINE_FRCDATA            : 1; // bit 8~8
    volatile uint32_t ISO_ANA_FRCDATA               : 1; // bit 9~9
    volatile uint32_t EN_LDO_CORE_FRCDATA           : 1; // bit 10~10
    volatile uint32_t OSC24M_EN_CORE_FRCDATA        : 1; // bit 11~11
    volatile uint32_t OSC24M_EN_OSC_TOP_FRCDATA     : 1; // bit 12~12
    volatile uint32_t XO24M_BUF_CORE_EN_FRCDATA     : 1; // bit 13~13
    volatile uint32_t XO24M_CORE_EN_FRCDATA         : 1; // bit 14~14
    volatile uint32_t EN_LDO_VRAM_FRCDATA           : 1; // bit 15~15
    volatile uint32_t XO24M_BUF_EN_FRCDATA          : 1; // bit 16~16
    volatile uint32_t RAM_PGEN_FRCDATA              : 1; // bit 17~17
    volatile uint32_t RAM_RET2N_FRCDATA             : 1; // bit 18~18
    volatile uint32_t RAM_RET1N_FRCDATA             : 1; // bit 19~19
    volatile uint32_t ISO_CORE_FRCDATA              : 1; // bit 20~20
    volatile uint32_t RESV_21_31                    : 11; // bit 21~31
};

union AON_CTRL_REG_AON_FORCE_DATA {
    volatile uint32_t                               all;
    struct AON_CTRL_REG_AON_FORCE_DATA_BITS         bit;
};

typedef struct
{
    union AON_CTRL_REG_AON_CHIP_VER                 REG_AON_CHIP_VER; // 0x000
    union AON_CTRL_REG_DFT_CTRL                     REG_DFT_CTRL; // 0x004
    union AON_CTRL_REG_PWON_CNT_CFG0                REG_PWON_CNT_CFG0; // 0x008
    union AON_CTRL_REG_PWON_CNT_CFG1                REG_PWON_CNT_CFG1; // 0x00C
    union AON_CTRL_REG_WAKEUP_ENABLE                REG_WAKEUP_ENABLE; // 0x010
    union AON_CTRL_REG_WAKEUP_IRSR                  REG_WAKEUP_IRSR; // 0x014
    union AON_CTRL_REG_WAKEUP_IMR                   REG_WAKEUP_IMR; // 0x018
    union AON_CTRL_REG_WAKEUP_ICR                   REG_WAKEUP_ICR; // 0x01C
    union AON_CTRL_REG_WAKEUP_ISR                   REG_WAKEUP_ISR; // 0x020
    union AON_CTRL_REG_SLEEP_MODE                   REG_SLEEP_MODE; // 0x024
    union AON_CTRL_REG_GPIO_WAKEUP_CTRL             REG_GPIO_WAKEUP_CTRL; // 0x028
    union AON_CTRL_REG_GPIO_CTRL_POL                REG_GPIO_CTRL_POL; // 0x02C
    union AON_CTRL_REG_GPIO_CTRL_DB_ENA             REG_GPIO_CTRL_DB_ENA; // 0x030
    union AON_CTRL_REG_GPIO_STATUS                  REG_GPIO_STATUS; // 0x034
    union AON_CTRL_REG_AON_GPIO_OUT                 REG_AON_GPIO_OUT; // 0x038
    union AON_CTRL_REG_RAM_RETENTION_CTRL           REG_RAM_RETENTION_CTRL; // 0x03C
    union AON_CTRL_REG_CHECK_UVLO_ENABLE            REG_CHECK_UVLO_ENABLE; // 0x040
    union AON_CTRL_REG_SYSRST_STATUS                REG_SYSRST_STATUS; // 0x044
    union AON_CTRL_REG_SLEEP_MODE_ENTRY             REG_SLEEP_MODE_ENTRY; // 0x048
    union AON_CTRL_REG_AON_SW_RESET                 REG_AON_SW_RESET; // 0x04C
    union AON_CTRL_REG_AON_CLK_CTRL                 REG_AON_CLK_CTRL; // 0x050
    union AON_CTRL_REG_AON_RST_CTRL                 REG_AON_RST_CTRL; // 0x054
    union AON_CTRL_REG_KEYSENSE_CTRL                REG_KEYSENSE_CTRL; // 0x058
    union AON_CTRL_REG_GPADC_VDD_IO_DIV_SEL         REG_GPADC_VDD_IO_DIV_SEL; // 0x05C
    union AON_CTRL_REG_XO24M_CTRL                   REG_XO24M_CTRL; // 0x060
    union AON_CTRL_REG_OSC24M_CTRL                  REG_OSC24M_CTRL; // 0x064
    union AON_CTRL_REG_AON_TUNE0                    REG_AON_TUNE0; // 0x068
    union AON_CTRL_REG_AON_TUNE1                    REG_AON_TUNE1; // 0x06C
    union AON_CTRL_REG_AON_TUNE2                    REG_AON_TUNE2; // 0x070
    union AON_CTRL_REG_AON_ANA_RSVD                 REG_AON_ANA_RSVD; // 0x074
    union AON_CTRL_REG_AON_DIG_RSVD                 REG_AON_DIG_RSVD; // 0x078
    union AON_CTRL_REG_AON_FORCE_CTRL               REG_AON_FORCE_CTRL; // 0x07C
    union AON_CTRL_REG_AON_FORCE_DATA               REG_AON_FORCE_DATA; // 0x080
} AON_CTRL_RegDef;


#endif // __AON_CTRL_REGFILE_H__

