//  ----------------------------------------------------------------------
//  File Name   : GenCFold/apc_reg_mars.h
//  Description : C header file generated by Python script.
//  Script Ver  : LS.AUTO_REG.2024.03.01
//  Create Time : 2024-03-20 14:46:55
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __APC_REGFILE_H__
#define __APC_REGFILE_H__

#include <stdint.h>

#define APC_APC_CFG_OFFSET                          0x000
#define APC_APC_CFG_DAC_CLASSD_SRC_Pos              5
#define APC_APC_CFG_DAC_CLASSD_SRC_Msk              0x60
#define APC_APC_CFG_I2S_OUT_SRC_Pos                 4
#define APC_APC_CFG_I2S_OUT_SRC_Msk                 0x10
#define APC_APC_CFG_AUTO_CLK_GATING_Pos             3
#define APC_APC_CFG_AUTO_CLK_GATING_Msk             0x8
#define APC_APC_CFG_APC_TX_PATH_RESET_Pos           2
#define APC_APC_CFG_APC_TX_PATH_RESET_Msk           0x4
#define APC_APC_CFG_APC_RX_PATH_RESET_Pos           1
#define APC_APC_CFG_APC_RX_PATH_RESET_Msk           0x2
#define APC_APC_CFG_APC_ENABLE_Pos                  0
#define APC_APC_CFG_APC_ENABLE_Msk                  0x1

#define APC_APC_CFG_RSVD0_OFFSET                    0x004

#define APC_APC_CFG_RSVD1_OFFSET                    0x008

#define APC_APC_TX_CH_CFG_OFFSET                    0x00C
#define APC_APC_TX_CH_CFG_TX_CH_DMA_THD_SEL_Pos     29
#define APC_APC_TX_CH_CFG_TX_CH_DMA_THD_SEL_Msk     0x60000000
#define APC_APC_TX_CH_CFG_TX_CH_STEREO_MODE_Pos     28
#define APC_APC_TX_CH_CFG_TX_CH_STEREO_MODE_Msk     0x10000000
#define APC_APC_TX_CH_CFG_TX_CH_R_16B_ALONE_Pos     27
#define APC_APC_TX_CH_CFG_TX_CH_R_16B_ALONE_Msk     0x8000000
#define APC_APC_TX_CH_CFG_TX_CHR_SRC_SEL_Pos        25
#define APC_APC_TX_CH_CFG_TX_CHR_SRC_SEL_Msk        0x6000000
#define APC_APC_TX_CH_CFG_TX_CH_R_FIFO_CNT_Pos      20
#define APC_APC_TX_CH_CFG_TX_CH_R_FIFO_CNT_Msk      0x1f00000
#define APC_APC_TX_CH_CFG_TX_CH_R_FIFO_FLUSH_Pos    19
#define APC_APC_TX_CH_CFG_TX_CH_R_FIFO_FLUSH_Msk    0x80000
#define APC_APC_TX_CH_CFG_TX_CH_R_MODE_Pos          17
#define APC_APC_TX_CH_CFG_TX_CH_R_MODE_Msk          0x60000
#define APC_APC_TX_CH_CFG_TX_CH_R_EN_Pos            16
#define APC_APC_TX_CH_CFG_TX_CH_R_EN_Msk            0x10000
#define APC_APC_TX_CH_CFG_TX_CH_RD_AUTOFEED_Pos     12
#define APC_APC_TX_CH_CFG_TX_CH_RD_AUTOFEED_Msk     0x1000
#define APC_APC_TX_CH_CFG_TX_CH_L_16B_ALONE_Pos     11
#define APC_APC_TX_CH_CFG_TX_CH_L_16B_ALONE_Msk     0x800
#define APC_APC_TX_CH_CFG_TX_CHL_SRC_SEL_Pos        9
#define APC_APC_TX_CH_CFG_TX_CHL_SRC_SEL_Msk        0x600
#define APC_APC_TX_CH_CFG_TX_CH_L_FIFO_CNT_Pos      4
#define APC_APC_TX_CH_CFG_TX_CH_L_FIFO_CNT_Msk      0x1f0
#define APC_APC_TX_CH_CFG_TX_CH_L_FIFO_FLUSH_Pos    3
#define APC_APC_TX_CH_CFG_TX_CH_L_FIFO_FLUSH_Msk    0x8
#define APC_APC_TX_CH_CFG_TX_CH_L_MODE_Pos          1
#define APC_APC_TX_CH_CFG_TX_CH_L_MODE_Msk          0x6
#define APC_APC_TX_CH_CFG_TX_CH_L_EN_Pos            0
#define APC_APC_TX_CH_CFG_TX_CH_L_EN_Msk            0x1

#define APC_APC_RX_CH_CFG0_OFFSET                   0x010
#define APC_APC_RX_CH_CFG0_RX_CH_DMA_THD_SEL_Pos    29
#define APC_APC_RX_CH_CFG0_RX_CH_DMA_THD_SEL_Msk    0x60000000
#define APC_APC_RX_CH_CFG0_RX_CH_STEREO_MODE_Pos    28
#define APC_APC_RX_CH_CFG0_RX_CH_STEREO_MODE_Msk    0x10000000
#define APC_APC_RX_CH_CFG0_RX_CHR_SRC_SEL_Pos       25
#define APC_APC_RX_CH_CFG0_RX_CHR_SRC_SEL_Msk       0xe000000
#define APC_APC_RX_CH_CFG0_RX_CH_R_FIFO_CNT_Pos     20
#define APC_APC_RX_CH_CFG0_RX_CH_R_FIFO_CNT_Msk     0x1f00000
#define APC_APC_RX_CH_CFG0_RX_CH_R_FIFO_FLUSH_Pos    19
#define APC_APC_RX_CH_CFG0_RX_CH_R_FIFO_FLUSH_Msk    0x80000
#define APC_APC_RX_CH_CFG0_RX_CH_R_MODE_Pos         17
#define APC_APC_RX_CH_CFG0_RX_CH_R_MODE_Msk         0x60000
#define APC_APC_RX_CH_CFG0_RX_CH_R_EN_Pos           16
#define APC_APC_RX_CH_CFG0_RX_CH_R_EN_Msk           0x10000
#define APC_APC_RX_CH_CFG0_SRC_CLR_Pos              15
#define APC_APC_RX_CH_CFG0_SRC_CLR_Msk              0x8000
#define APC_APC_RX_CH_CFG0_SRC_MODE_Pos             14
#define APC_APC_RX_CH_CFG0_SRC_MODE_Msk             0x4000
#define APC_APC_RX_CH_CFG0_SRC_CH_EN_Pos            12
#define APC_APC_RX_CH_CFG0_SRC_CH_EN_Msk            0x3000
#define APC_APC_RX_CH_CFG0_RX_CHL_SRC_SEL_Pos       9
#define APC_APC_RX_CH_CFG0_RX_CHL_SRC_SEL_Msk       0xe00
#define APC_APC_RX_CH_CFG0_RX_CH_L_FIFO_CNT_Pos     4
#define APC_APC_RX_CH_CFG0_RX_CH_L_FIFO_CNT_Msk     0x1f0
#define APC_APC_RX_CH_CFG0_RX_CH_L_FIFO_FLUSH_Pos    3
#define APC_APC_RX_CH_CFG0_RX_CH_L_FIFO_FLUSH_Msk    0x8
#define APC_APC_RX_CH_CFG0_RX_CH_L_MODE_Pos         1
#define APC_APC_RX_CH_CFG0_RX_CH_L_MODE_Msk         0x6
#define APC_APC_RX_CH_CFG0_RX_CH_L_EN_Pos           0
#define APC_APC_RX_CH_CFG0_RX_CH_L_EN_Msk           0x1

#define APC_APC_RX_CH_CFG1_OFFSET                   0x014
#define APC_APC_RX_CH_CFG1_RX_FIFO_LR_SPLICING_Pos    2
#define APC_APC_RX_CH_CFG1_RX_FIFO_LR_SPLICING_Msk    0x4
#define APC_APC_RX_CH_CFG1_RX_CH_R_16B_ALONE_Pos    1
#define APC_APC_RX_CH_CFG1_RX_CH_R_16B_ALONE_Msk    0x2
#define APC_APC_RX_CH_CFG1_RX_CH_L_16B_ALONE_Pos    0
#define APC_APC_RX_CH_CFG1_RX_CH_L_16B_ALONE_Msk    0x1

#define APC_APC_I2S_CFG0_OFFSET                     0x018
#define APC_APC_I2S_CFG0_I2S_ENABLE_Pos             31
#define APC_APC_I2S_CFG0_I2S_ENABLE_Msk             0x80000000
#define APC_APC_I2S_CFG0_I2S_SW_RESET_Pos           30
#define APC_APC_I2S_CFG0_I2S_SW_RESET_Msk           0x40000000
#define APC_APC_I2S_CFG0_I2S_RSTN_BYPASS_Pos        29
#define APC_APC_I2S_CFG0_I2S_RSTN_BYPASS_Msk        0x20000000
#define APC_APC_I2S_CFG0_I2S_EN_FORCE_ON_Pos        28
#define APC_APC_I2S_CFG0_I2S_EN_FORCE_ON_Msk        0x10000000
#define APC_APC_I2S_CFG0_I2S_BCK_FORCE_ON_Pos       27
#define APC_APC_I2S_CFG0_I2S_BCK_FORCE_ON_Msk       0x8000000
#define APC_APC_I2S_CFG0_I2S_BYPASS_FIFOVLD_Pos     26
#define APC_APC_I2S_CFG0_I2S_BYPASS_FIFOVLD_Msk     0x4000000
#define APC_APC_I2S_CFG0_I2S_TX_MODE_Pos            24
#define APC_APC_I2S_CFG0_I2S_TX_MODE_Msk            0x3000000
#define APC_APC_I2S_CFG0_I2S_SERIAL_MODE_Pos        22
#define APC_APC_I2S_CFG0_I2S_SERIAL_MODE_Msk        0xc00000
#define APC_APC_I2S_CFG0_I2S_MASTER_MODE_Pos        21
#define APC_APC_I2S_CFG0_I2S_MASTER_MODE_Msk        0x200000
#define APC_APC_I2S_CFG0_I2S_TX_DLY_Pos             20
#define APC_APC_I2S_CFG0_I2S_TX_DLY_Msk             0x100000
#define APC_APC_I2S_CFG0_I2S_TX_RX_DLY_S_Pos        19
#define APC_APC_I2S_CFG0_I2S_TX_RX_DLY_S_Msk        0x80000
#define APC_APC_I2S_CFG0_I2S_RX_DLY_Pos             17
#define APC_APC_I2S_CFG0_I2S_RX_DLY_Msk             0x60000
#define APC_APC_I2S_CFG0_I2S_TX_HALF_CYCLE_DLY_Pos    16
#define APC_APC_I2S_CFG0_I2S_TX_HALF_CYCLE_DLY_Msk    0x10000
#define APC_APC_I2S_CFG0_I2S_RX_HALF_CYCLE_DLY_Pos    15
#define APC_APC_I2S_CFG0_I2S_RX_HALF_CYCLE_DLY_Msk    0x8000
#define APC_APC_I2S_CFG0_I2S_BCKOUT_GATE_Pos        14
#define APC_APC_I2S_CFG0_I2S_BCKOUT_GATE_Msk        0x4000
#define APC_APC_I2S_CFG0_I2S_BCK_POL_Pos            13
#define APC_APC_I2S_CFG0_I2S_BCK_POL_Msk            0x2000
#define APC_APC_I2S_CFG0_I2S_LRCK_POL_Pos           12
#define APC_APC_I2S_CFG0_I2S_LRCK_POL_Msk           0x1000
#define APC_APC_I2S_CFG0_I2S_WLEN_Pos               10
#define APC_APC_I2S_CFG0_I2S_WLEN_Msk               0xc00
#define APC_APC_I2S_CFG0_I2S_BCK_LRCK_Pos           5
#define APC_APC_I2S_CFG0_I2S_BCK_LRCK_Msk           0x3e0
#define APC_APC_I2S_CFG0_I2S_RIGHT_JUSTIFIED_Pos    4
#define APC_APC_I2S_CFG0_I2S_RIGHT_JUSTIFIED_Msk    0x10
#define APC_APC_I2S_CFG0_I2S_LSB_Pos                3
#define APC_APC_I2S_CFG0_I2S_LSB_Msk                0x8
#define APC_APC_I2S_CFG0_I2S_LOOP_BACK_Pos          2
#define APC_APC_I2S_CFG0_I2S_LOOP_BACK_Msk          0x4
#define APC_APC_I2S_CFG0_I2S_SWAP_CHLR_Pos          0
#define APC_APC_I2S_CFG0_I2S_SWAP_CHLR_Msk          0x3

#define APC_APC_I2S_CFG1_OFFSET                     0x01C
#define APC_APC_I2S_CFG1_I2S_ERR_MASK_Pos           31
#define APC_APC_I2S_CFG1_I2S_ERR_MASK_Msk           0x80000000
#define APC_APC_I2S_CFG1_I2S_ERR_CLR_Pos            30
#define APC_APC_I2S_CFG1_I2S_ERR_CLR_Msk            0x40000000
#define APC_APC_I2S_CFG1_I2S_ERR_ISR_Pos            29
#define APC_APC_I2S_CFG1_I2S_ERR_ISR_Msk            0x20000000
#define APC_APC_I2S_CFG1_I2S_ERR_IRSR_Pos           28
#define APC_APC_I2S_CFG1_I2S_ERR_IRSR_Msk           0x10000000
#define APC_APC_I2S_CFG1_I2S_SAME_EDGE_Pos          27
#define APC_APC_I2S_CFG1_I2S_SAME_EDGE_Msk          0x8000000
#define APC_APC_I2S_CFG1_I2S_BCK_DIV_LD_Pos         26
#define APC_APC_I2S_CFG1_I2S_BCK_DIV_LD_Msk         0x4000000
#define APC_APC_I2S_CFG1_I2S_BCK_DIV_Pos            16
#define APC_APC_I2S_CFG1_I2S_BCK_DIV_Msk            0x3ff0000
#define APC_APC_I2S_CFG1_I2S_SLOT_LRCK_Pos          9
#define APC_APC_I2S_CFG1_I2S_SLOT_LRCK_Msk          0xfe00
#define APC_APC_I2S_CFG1_I2S_LONGSYNC_Pos           8
#define APC_APC_I2S_CFG1_I2S_LONGSYNC_Msk           0x100
#define APC_APC_I2S_CFG1_I2S_SLOTNUM_Pos            0
#define APC_APC_I2S_CFG1_I2S_SLOTNUM_Msk            0xff

#define APC_APC_I2S_CFG3_OFFSET                     0x020
#define APC_APC_I2S_CFG3_I2S_CLK_SRC_Pos            1
#define APC_APC_I2S_CFG3_I2S_CLK_SRC_Msk            0x6
#define APC_APC_I2S_CFG3_I2S_SWRST_SYNC_BYPASS_Pos    0
#define APC_APC_I2S_CFG3_I2S_SWRST_SYNC_BYPASS_Msk    0x1

#define APC_APC_TX_CH_L_DATA_OFFSET                 0x024
#define APC_APC_TX_CH_L_DATA_TX_CH_L_DATA_Pos       0
#define APC_APC_TX_CH_L_DATA_TX_CH_L_DATA_Msk       0xffffffff

#define APC_APC_TX_CH_R_DATA_OFFSET                 0x028
#define APC_APC_TX_CH_R_DATA_TX_CH_R_DATA_Pos       0
#define APC_APC_TX_CH_R_DATA_TX_CH_R_DATA_Msk       0xffffffff

#define APC_APC_RX_CH_L_DATA_OFFSET                 0x02C
#define APC_APC_RX_CH_L_DATA_RX_CH_L_DATA_Pos       0
#define APC_APC_RX_CH_L_DATA_RX_CH_L_DATA_Msk       0xffffffff

#define APC_APC_RX_CH_R_DATA_OFFSET                 0x030
#define APC_APC_RX_CH_R_DATA_RX_CH_R_DATA_Pos       0
#define APC_APC_RX_CH_R_DATA_RX_CH_R_DATA_Msk       0xffffffff

#define APC_APC_INTR_TX_MSK_OFFSET                  0x034
#define APC_APC_INTR_TX_MSK_TX_CH_FIFO_VLD_MSK_Pos    10
#define APC_APC_INTR_TX_MSK_TX_CH_FIFO_VLD_MSK_Msk    0x400
#define APC_APC_INTR_TX_MSK_TX_CH_R_DMA_REQ_MSK_Pos    9
#define APC_APC_INTR_TX_MSK_TX_CH_R_DMA_REQ_MSK_Msk    0x200
#define APC_APC_INTR_TX_MSK_TX_CH_R_FIFO_OVFLOW_MSK_Pos    8
#define APC_APC_INTR_TX_MSK_TX_CH_R_FIFO_OVFLOW_MSK_Msk    0x100
#define APC_APC_INTR_TX_MSK_TX_CH_R_FIFO_UNFLOW_MSK_Pos    7
#define APC_APC_INTR_TX_MSK_TX_CH_R_FIFO_UNFLOW_MSK_Msk    0x80
#define APC_APC_INTR_TX_MSK_TX_CH_R_FIFO_FUL_MSK_Pos    6
#define APC_APC_INTR_TX_MSK_TX_CH_R_FIFO_FUL_MSK_Msk    0x40
#define APC_APC_INTR_TX_MSK_TX_CH_R_FIFO_EMP_MSK_Pos    5
#define APC_APC_INTR_TX_MSK_TX_CH_R_FIFO_EMP_MSK_Msk    0x20
#define APC_APC_INTR_TX_MSK_TX_CH_L_DMA_REQ_MSK_Pos    4
#define APC_APC_INTR_TX_MSK_TX_CH_L_DMA_REQ_MSK_Msk    0x10
#define APC_APC_INTR_TX_MSK_TX_CH_L_FIFO_OVFLOW_MSK_Pos    3
#define APC_APC_INTR_TX_MSK_TX_CH_L_FIFO_OVFLOW_MSK_Msk    0x8
#define APC_APC_INTR_TX_MSK_TX_CH_L_FIFO_UNFLOW_MSK_Pos    2
#define APC_APC_INTR_TX_MSK_TX_CH_L_FIFO_UNFLOW_MSK_Msk    0x4
#define APC_APC_INTR_TX_MSK_TX_CH_L_FIFO_FUL_MSK_Pos    1
#define APC_APC_INTR_TX_MSK_TX_CH_L_FIFO_FUL_MSK_Msk    0x2
#define APC_APC_INTR_TX_MSK_TX_CH_L_FIFO_EMP_MSK_Pos    0
#define APC_APC_INTR_TX_MSK_TX_CH_L_FIFO_EMP_MSK_Msk    0x1

#define APC_APC_INTR_RX_MSK_OFFSET                  0x038
#define APC_APC_INTR_RX_MSK_RX_CH_R_DMA_REQ_MSK_Pos    9
#define APC_APC_INTR_RX_MSK_RX_CH_R_DMA_REQ_MSK_Msk    0x200
#define APC_APC_INTR_RX_MSK_RX_CH_R_FIFO_OVFLOW_MSK_Pos    8
#define APC_APC_INTR_RX_MSK_RX_CH_R_FIFO_OVFLOW_MSK_Msk    0x100
#define APC_APC_INTR_RX_MSK_RX_CH_R_FIFO_UNFLOW_MSK_Pos    7
#define APC_APC_INTR_RX_MSK_RX_CH_R_FIFO_UNFLOW_MSK_Msk    0x80
#define APC_APC_INTR_RX_MSK_RX_CH_R_FIFO_FUL_MSK_Pos    6
#define APC_APC_INTR_RX_MSK_RX_CH_R_FIFO_FUL_MSK_Msk    0x40
#define APC_APC_INTR_RX_MSK_RX_CH_R_FIFO_EMP_MSK_Pos    5
#define APC_APC_INTR_RX_MSK_RX_CH_R_FIFO_EMP_MSK_Msk    0x20
#define APC_APC_INTR_RX_MSK_RX_CH_L_DMA_REQ_MSK_Pos    4
#define APC_APC_INTR_RX_MSK_RX_CH_L_DMA_REQ_MSK_Msk    0x10
#define APC_APC_INTR_RX_MSK_RX_CH_L_FIFO_OVFLOW_MSK_Pos    3
#define APC_APC_INTR_RX_MSK_RX_CH_L_FIFO_OVFLOW_MSK_Msk    0x8
#define APC_APC_INTR_RX_MSK_RX_CH_L_FIFO_UNFLOW_MSK_Pos    2
#define APC_APC_INTR_RX_MSK_RX_CH_L_FIFO_UNFLOW_MSK_Msk    0x4
#define APC_APC_INTR_RX_MSK_RX_CH_L_FIFO_FUL_MSK_Pos    1
#define APC_APC_INTR_RX_MSK_RX_CH_L_FIFO_FUL_MSK_Msk    0x2
#define APC_APC_INTR_RX_MSK_RX_CH_L_FIFO_EMP_MSK_Pos    0
#define APC_APC_INTR_RX_MSK_RX_CH_L_FIFO_EMP_MSK_Msk    0x1

#define APC_APC_INTR_TX_CLR_OFFSET                  0x03C
#define APC_APC_INTR_TX_CLR_TX_CH_FIFO_VLD_CLR_Pos    10
#define APC_APC_INTR_TX_CLR_TX_CH_FIFO_VLD_CLR_Msk    0x400
#define APC_APC_INTR_TX_CLR_TX_CH_R_DMA_REQ_CLR_Pos    9
#define APC_APC_INTR_TX_CLR_TX_CH_R_DMA_REQ_CLR_Msk    0x200
#define APC_APC_INTR_TX_CLR_TX_CH_R_FIFO_OVFLOW_CLR_Pos    8
#define APC_APC_INTR_TX_CLR_TX_CH_R_FIFO_OVFLOW_CLR_Msk    0x100
#define APC_APC_INTR_TX_CLR_TX_CH_R_FIFO_UNFLOW_CLR_Pos    7
#define APC_APC_INTR_TX_CLR_TX_CH_R_FIFO_UNFLOW_CLR_Msk    0x80
#define APC_APC_INTR_TX_CLR_TX_CH_R_FIFO_FUL_CLR_Pos    6
#define APC_APC_INTR_TX_CLR_TX_CH_R_FIFO_FUL_CLR_Msk    0x40
#define APC_APC_INTR_TX_CLR_TX_CH_R_FIFO_EMP_CLR_Pos    5
#define APC_APC_INTR_TX_CLR_TX_CH_R_FIFO_EMP_CLR_Msk    0x20
#define APC_APC_INTR_TX_CLR_TX_CH_L_DMA_REQ_CLR_Pos    4
#define APC_APC_INTR_TX_CLR_TX_CH_L_DMA_REQ_CLR_Msk    0x10
#define APC_APC_INTR_TX_CLR_TX_CH_L_FIFO_OVFLOW_CLR_Pos    3
#define APC_APC_INTR_TX_CLR_TX_CH_L_FIFO_OVFLOW_CLR_Msk    0x8
#define APC_APC_INTR_TX_CLR_TX_CH_L_FIFO_UNFLOW_CLR_Pos    2
#define APC_APC_INTR_TX_CLR_TX_CH_L_FIFO_UNFLOW_CLR_Msk    0x4
#define APC_APC_INTR_TX_CLR_TX_CH_L_FIFO_FUL_CLR_Pos    1
#define APC_APC_INTR_TX_CLR_TX_CH_L_FIFO_FUL_CLR_Msk    0x2
#define APC_APC_INTR_TX_CLR_TX_CH_L_FIFO_EMP_CLR_Pos    0
#define APC_APC_INTR_TX_CLR_TX_CH_L_FIFO_EMP_CLR_Msk    0x1

#define APC_APC_INTR_RX_CLR_OFFSET                  0x040
#define APC_APC_INTR_RX_CLR_RX_CH_R_DMA_REQ_CLR_Pos    9
#define APC_APC_INTR_RX_CLR_RX_CH_R_DMA_REQ_CLR_Msk    0x200
#define APC_APC_INTR_RX_CLR_RX_CH_R_FIFO_OVFLOW_CLR_Pos    8
#define APC_APC_INTR_RX_CLR_RX_CH_R_FIFO_OVFLOW_CLR_Msk    0x100
#define APC_APC_INTR_RX_CLR_RX_CH_R_FIFO_UNFLOW_CLR_Pos    7
#define APC_APC_INTR_RX_CLR_RX_CH_R_FIFO_UNFLOW_CLR_Msk    0x80
#define APC_APC_INTR_RX_CLR_RX_CH_R_FIFO_FUL_CLR_Pos    6
#define APC_APC_INTR_RX_CLR_RX_CH_R_FIFO_FUL_CLR_Msk    0x40
#define APC_APC_INTR_RX_CLR_RX_CH_R_FIFO_EMP_CLR_Pos    5
#define APC_APC_INTR_RX_CLR_RX_CH_R_FIFO_EMP_CLR_Msk    0x20
#define APC_APC_INTR_RX_CLR_RX_CH_L_DMA_REQ_CLR_Pos    4
#define APC_APC_INTR_RX_CLR_RX_CH_L_DMA_REQ_CLR_Msk    0x10
#define APC_APC_INTR_RX_CLR_RX_CH_L_FIFO_OVFLOW_CLR_Pos    3
#define APC_APC_INTR_RX_CLR_RX_CH_L_FIFO_OVFLOW_CLR_Msk    0x8
#define APC_APC_INTR_RX_CLR_RX_CH_L_FIFO_UNFLOW_CLR_Pos    2
#define APC_APC_INTR_RX_CLR_RX_CH_L_FIFO_UNFLOW_CLR_Msk    0x4
#define APC_APC_INTR_RX_CLR_RX_CH_L_FIFO_FUL_CLR_Pos    1
#define APC_APC_INTR_RX_CLR_RX_CH_L_FIFO_FUL_CLR_Msk    0x2
#define APC_APC_INTR_RX_CLR_RX_CH_L_FIFO_EMP_CLR_Pos    0
#define APC_APC_INTR_RX_CLR_RX_CH_L_FIFO_EMP_CLR_Msk    0x1

#define APC_APC_INTR_TX_IRSR_OFFSET                 0x044
#define APC_APC_INTR_TX_IRSR_TX_CH_FIFO_VLD_IRSR_Pos    10
#define APC_APC_INTR_TX_IRSR_TX_CH_FIFO_VLD_IRSR_Msk    0x400
#define APC_APC_INTR_TX_IRSR_TX_CH_R_DMA_REQ_IRSR_Pos    9
#define APC_APC_INTR_TX_IRSR_TX_CH_R_DMA_REQ_IRSR_Msk    0x200
#define APC_APC_INTR_TX_IRSR_TX_CH_R_FIFO_OVFLOW_IRSR_Pos    8
#define APC_APC_INTR_TX_IRSR_TX_CH_R_FIFO_OVFLOW_IRSR_Msk    0x100
#define APC_APC_INTR_TX_IRSR_TX_CH_R_FIFO_UNFLOW_IRSR_Pos    7
#define APC_APC_INTR_TX_IRSR_TX_CH_R_FIFO_UNFLOW_IRSR_Msk    0x80
#define APC_APC_INTR_TX_IRSR_TX_CH_R_FIFO_FUL_IRSR_Pos    6
#define APC_APC_INTR_TX_IRSR_TX_CH_R_FIFO_FUL_IRSR_Msk    0x40
#define APC_APC_INTR_TX_IRSR_TX_CH_R_FIFO_EMP_IRSR_Pos    5
#define APC_APC_INTR_TX_IRSR_TX_CH_R_FIFO_EMP_IRSR_Msk    0x20
#define APC_APC_INTR_TX_IRSR_TX_CH_L_DMA_REQ_IRSR_Pos    4
#define APC_APC_INTR_TX_IRSR_TX_CH_L_DMA_REQ_IRSR_Msk    0x10
#define APC_APC_INTR_TX_IRSR_TX_CH_L_FIFO_OVFLOW_IRSR_Pos    3
#define APC_APC_INTR_TX_IRSR_TX_CH_L_FIFO_OVFLOW_IRSR_Msk    0x8
#define APC_APC_INTR_TX_IRSR_TX_CH_L_FIFO_UNFLOW_IRSR_Pos    2
#define APC_APC_INTR_TX_IRSR_TX_CH_L_FIFO_UNFLOW_IRSR_Msk    0x4
#define APC_APC_INTR_TX_IRSR_TX_CH_L_FIFO_FUL_IRSR_Pos    1
#define APC_APC_INTR_TX_IRSR_TX_CH_L_FIFO_FUL_IRSR_Msk    0x2
#define APC_APC_INTR_TX_IRSR_TX_CH_L_FIFO_EMP_IRSR_Pos    0
#define APC_APC_INTR_TX_IRSR_TX_CH_L_FIFO_EMP_IRSR_Msk    0x1

#define APC_APC_INTR_RX_IRSR_OFFSET                 0x048
#define APC_APC_INTR_RX_IRSR_RX_CH_R_DMA_REQ_IRSR_Pos    9
#define APC_APC_INTR_RX_IRSR_RX_CH_R_DMA_REQ_IRSR_Msk    0x200
#define APC_APC_INTR_RX_IRSR_RX_CH_R_FIFO_OVFLOW_IRSR_Pos    8
#define APC_APC_INTR_RX_IRSR_RX_CH_R_FIFO_OVFLOW_IRSR_Msk    0x100
#define APC_APC_INTR_RX_IRSR_RX_CH_R_FIFO_UNFLOW_IRSR_Pos    7
#define APC_APC_INTR_RX_IRSR_RX_CH_R_FIFO_UNFLOW_IRSR_Msk    0x80
#define APC_APC_INTR_RX_IRSR_RX_CH_R_FIFO_FUL_IRSR_Pos    6
#define APC_APC_INTR_RX_IRSR_RX_CH_R_FIFO_FUL_IRSR_Msk    0x40
#define APC_APC_INTR_RX_IRSR_RX_CH_R_FIFO_EMP_IRSR_Pos    5
#define APC_APC_INTR_RX_IRSR_RX_CH_R_FIFO_EMP_IRSR_Msk    0x20
#define APC_APC_INTR_RX_IRSR_RX_CH_L_DMA_REQ_IRSR_Pos    4
#define APC_APC_INTR_RX_IRSR_RX_CH_L_DMA_REQ_IRSR_Msk    0x10
#define APC_APC_INTR_RX_IRSR_RX_CH_L_FIFO_OVFLOW_IRSR_Pos    3
#define APC_APC_INTR_RX_IRSR_RX_CH_L_FIFO_OVFLOW_IRSR_Msk    0x8
#define APC_APC_INTR_RX_IRSR_RX_CH_L_FIFO_UNFLOW_IRSR_Pos    2
#define APC_APC_INTR_RX_IRSR_RX_CH_L_FIFO_UNFLOW_IRSR_Msk    0x4
#define APC_APC_INTR_RX_IRSR_RX_CH_L_FIFO_FUL_IRSR_Pos    1
#define APC_APC_INTR_RX_IRSR_RX_CH_L_FIFO_FUL_IRSR_Msk    0x2
#define APC_APC_INTR_RX_IRSR_RX_CH_L_FIFO_EMP_IRSR_Pos    0
#define APC_APC_INTR_RX_IRSR_RX_CH_L_FIFO_EMP_IRSR_Msk    0x1

#define APC_APC_INTR_TX_ISR_OFFSET                  0x04C
#define APC_APC_INTR_TX_ISR_TX_CH_FIFO_VLD_ISR_Pos    10
#define APC_APC_INTR_TX_ISR_TX_CH_FIFO_VLD_ISR_Msk    0x400
#define APC_APC_INTR_TX_ISR_TX_CH_R_DMA_REQ_ISR_Pos    9
#define APC_APC_INTR_TX_ISR_TX_CH_R_DMA_REQ_ISR_Msk    0x200
#define APC_APC_INTR_TX_ISR_TX_CH_R_FIFO_OVFLOW_ISR_Pos    8
#define APC_APC_INTR_TX_ISR_TX_CH_R_FIFO_OVFLOW_ISR_Msk    0x100
#define APC_APC_INTR_TX_ISR_TX_CH_R_FIFO_UNFLOW_ISR_Pos    7
#define APC_APC_INTR_TX_ISR_TX_CH_R_FIFO_UNFLOW_ISR_Msk    0x80
#define APC_APC_INTR_TX_ISR_TX_CH_R_FIFO_FUL_ISR_Pos    6
#define APC_APC_INTR_TX_ISR_TX_CH_R_FIFO_FUL_ISR_Msk    0x40
#define APC_APC_INTR_TX_ISR_TX_CH_R_FIFO_EMP_ISR_Pos    5
#define APC_APC_INTR_TX_ISR_TX_CH_R_FIFO_EMP_ISR_Msk    0x20
#define APC_APC_INTR_TX_ISR_TX_CH_L_DMA_REQ_ISR_Pos    4
#define APC_APC_INTR_TX_ISR_TX_CH_L_DMA_REQ_ISR_Msk    0x10
#define APC_APC_INTR_TX_ISR_TX_CH_L_FIFO_OVFLOW_ISR_Pos    3
#define APC_APC_INTR_TX_ISR_TX_CH_L_FIFO_OVFLOW_ISR_Msk    0x8
#define APC_APC_INTR_TX_ISR_TX_CH_L_FIFO_UNFLOW_ISR_Pos    2
#define APC_APC_INTR_TX_ISR_TX_CH_L_FIFO_UNFLOW_ISR_Msk    0x4
#define APC_APC_INTR_TX_ISR_TX_CH_L_FIFO_FUL_ISR_Pos    1
#define APC_APC_INTR_TX_ISR_TX_CH_L_FIFO_FUL_ISR_Msk    0x2
#define APC_APC_INTR_TX_ISR_TX_CH_L_FIFO_EMP_ISR_Pos    0
#define APC_APC_INTR_TX_ISR_TX_CH_L_FIFO_EMP_ISR_Msk    0x1

#define APC_APC_INTR_RX_ISR_OFFSET                  0x050
#define APC_APC_INTR_RX_ISR_RX_CH_R_DMA_REQ_ISR_Pos    9
#define APC_APC_INTR_RX_ISR_RX_CH_R_DMA_REQ_ISR_Msk    0x200
#define APC_APC_INTR_RX_ISR_RX_CH_R_FIFO_OVFLOW_ISR_Pos    8
#define APC_APC_INTR_RX_ISR_RX_CH_R_FIFO_OVFLOW_ISR_Msk    0x100
#define APC_APC_INTR_RX_ISR_RX_CH_R_FIFO_UNFLOW_ISR_Pos    7
#define APC_APC_INTR_RX_ISR_RX_CH_R_FIFO_UNFLOW_ISR_Msk    0x80
#define APC_APC_INTR_RX_ISR_RX_CH_R_FIFO_FUL_ISR_Pos    6
#define APC_APC_INTR_RX_ISR_RX_CH_R_FIFO_FUL_ISR_Msk    0x40
#define APC_APC_INTR_RX_ISR_RX_CH_R_FIFO_EMP_ISR_Pos    5
#define APC_APC_INTR_RX_ISR_RX_CH_R_FIFO_EMP_ISR_Msk    0x20
#define APC_APC_INTR_RX_ISR_RX_CH_L_DMA_REQ_ISR_Pos    4
#define APC_APC_INTR_RX_ISR_RX_CH_L_DMA_REQ_ISR_Msk    0x10
#define APC_APC_INTR_RX_ISR_RX_CH_L_FIFO_OVFLOW_ISR_Pos    3
#define APC_APC_INTR_RX_ISR_RX_CH_L_FIFO_OVFLOW_ISR_Msk    0x8
#define APC_APC_INTR_RX_ISR_RX_CH_L_FIFO_UNFLOW_ISR_Pos    2
#define APC_APC_INTR_RX_ISR_RX_CH_L_FIFO_UNFLOW_ISR_Msk    0x4
#define APC_APC_INTR_RX_ISR_RX_CH_L_FIFO_FUL_ISR_Pos    1
#define APC_APC_INTR_RX_ISR_RX_CH_L_FIFO_FUL_ISR_Msk    0x2
#define APC_APC_INTR_RX_ISR_RX_CH_L_FIFO_EMP_ISR_Pos    0
#define APC_APC_INTR_RX_ISR_RX_CH_L_FIFO_EMP_ISR_Msk    0x1

#define APC_APC_RSVD_RW_REG_OFFSET                  0x054
#define APC_APC_RSVD_RW_REG_APC_RSVD_RW_REG_Pos     0
#define APC_APC_RSVD_RW_REG_APC_RSVD_RW_REG_Msk     0xffffffff

#define APC_APC_RSVD_RO_REG_OFFSET                  0x058
#define APC_APC_RSVD_RO_REG_APC_RSVD_RO_REG_Pos     0
#define APC_APC_RSVD_RO_REG_APC_RSVD_RO_REG_Msk     0xffffffff

struct APC_REG_APC_CFG_BITS
{
    volatile uint32_t APC_ENABLE                    : 1; // bit 0~0
    volatile uint32_t APC_RX_PATH_RESET             : 1; // bit 1~1
    volatile uint32_t APC_TX_PATH_RESET             : 1; // bit 2~2
    volatile uint32_t AUTO_CLK_GATING               : 1; // bit 3~3
    volatile uint32_t I2S_OUT_SRC                   : 1; // bit 4~4
    volatile uint32_t DAC_CLASSD_SRC                : 2; // bit 5~6
    volatile uint32_t RESV_7_31                     : 25; // bit 7~31
};

union APC_REG_APC_CFG {
    volatile uint32_t                               all;
    struct APC_REG_APC_CFG_BITS                     bit;
};

struct APC_REG_APC_CFG_RSVD0_BITS
{
    volatile uint32_t RESV_0_31                     : 32; // bit 0~31
};

union APC_REG_APC_CFG_RSVD0 {
    volatile uint32_t                               all;
    struct APC_REG_APC_CFG_RSVD0_BITS               bit;
};

struct APC_REG_APC_CFG_RSVD1_BITS
{
    volatile uint32_t RESV_0_31                     : 32; // bit 0~31
};

union APC_REG_APC_CFG_RSVD1 {
    volatile uint32_t                               all;
    struct APC_REG_APC_CFG_RSVD1_BITS               bit;
};

struct APC_REG_APC_TX_CH_CFG_BITS
{
    volatile uint32_t TX_CH_L_EN                    : 1; // bit 0~0
    volatile uint32_t TX_CH_L_MODE                  : 2; // bit 1~2
    volatile uint32_t TX_CH_L_FIFO_FLUSH            : 1; // bit 3~3
    volatile uint32_t TX_CH_L_FIFO_CNT              : 5; // bit 4~8
    volatile uint32_t TX_CHL_SRC_SEL                : 2; // bit 9~10
    volatile uint32_t TX_CH_L_16B_ALONE             : 1; // bit 11~11
    volatile uint32_t TX_CH_RD_AUTOFEED             : 1; // bit 12~12
    volatile uint32_t RESV_13_15                    : 3; // bit 13~15
    volatile uint32_t TX_CH_R_EN                    : 1; // bit 16~16
    volatile uint32_t TX_CH_R_MODE                  : 2; // bit 17~18
    volatile uint32_t TX_CH_R_FIFO_FLUSH            : 1; // bit 19~19
    volatile uint32_t TX_CH_R_FIFO_CNT              : 5; // bit 20~24
    volatile uint32_t TX_CHR_SRC_SEL                : 2; // bit 25~26
    volatile uint32_t TX_CH_R_16B_ALONE             : 1; // bit 27~27
    volatile uint32_t TX_CH_STEREO_MODE             : 1; // bit 28~28
    volatile uint32_t TX_CH_DMA_THD_SEL             : 2; // bit 29~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union APC_REG_APC_TX_CH_CFG {
    volatile uint32_t                               all;
    struct APC_REG_APC_TX_CH_CFG_BITS               bit;
};

struct APC_REG_APC_RX_CH_CFG0_BITS
{
    volatile uint32_t RX_CH_L_EN                    : 1; // bit 0~0
    volatile uint32_t RX_CH_L_MODE                  : 2; // bit 1~2
    volatile uint32_t RX_CH_L_FIFO_FLUSH            : 1; // bit 3~3
    volatile uint32_t RX_CH_L_FIFO_CNT              : 5; // bit 4~8
    volatile uint32_t RX_CHL_SRC_SEL                : 3; // bit 9~11
    volatile uint32_t SRC_CH_EN                     : 2; // bit 12~13
    volatile uint32_t SRC_MODE                      : 1; // bit 14~14
    volatile uint32_t SRC_CLR                       : 1; // bit 15~15
    volatile uint32_t RX_CH_R_EN                    : 1; // bit 16~16
    volatile uint32_t RX_CH_R_MODE                  : 2; // bit 17~18
    volatile uint32_t RX_CH_R_FIFO_FLUSH            : 1; // bit 19~19
    volatile uint32_t RX_CH_R_FIFO_CNT              : 5; // bit 20~24
    volatile uint32_t RX_CHR_SRC_SEL                : 3; // bit 25~27
    volatile uint32_t RX_CH_STEREO_MODE             : 1; // bit 28~28
    volatile uint32_t RX_CH_DMA_THD_SEL             : 2; // bit 29~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union APC_REG_APC_RX_CH_CFG0 {
    volatile uint32_t                               all;
    struct APC_REG_APC_RX_CH_CFG0_BITS              bit;
};

struct APC_REG_APC_RX_CH_CFG1_BITS
{
    volatile uint32_t RX_CH_L_16B_ALONE             : 1; // bit 0~0
    volatile uint32_t RX_CH_R_16B_ALONE             : 1; // bit 1~1
    volatile uint32_t RX_FIFO_LR_SPLICING           : 1; // bit 2~2
    volatile uint32_t RESV_3_31                     : 29; // bit 3~31
};

union APC_REG_APC_RX_CH_CFG1 {
    volatile uint32_t                               all;
    struct APC_REG_APC_RX_CH_CFG1_BITS              bit;
};

struct APC_REG_APC_I2S_CFG0_BITS
{
    volatile uint32_t I2S_SWAP_CHLR                 : 2; // bit 0~1
    volatile uint32_t I2S_LOOP_BACK                 : 1; // bit 2~2
    volatile uint32_t I2S_LSB                       : 1; // bit 3~3
    volatile uint32_t I2S_RIGHT_JUSTIFIED           : 1; // bit 4~4
    volatile uint32_t I2S_BCK_LRCK                  : 5; // bit 5~9
    volatile uint32_t I2S_WLEN                      : 2; // bit 10~11
    volatile uint32_t I2S_LRCK_POL                  : 1; // bit 12~12
    volatile uint32_t I2S_BCK_POL                   : 1; // bit 13~13
    volatile uint32_t I2S_BCKOUT_GATE               : 1; // bit 14~14
    volatile uint32_t I2S_RX_HALF_CYCLE_DLY         : 1; // bit 15~15
    volatile uint32_t I2S_TX_HALF_CYCLE_DLY         : 1; // bit 16~16
    volatile uint32_t I2S_RX_DLY                    : 2; // bit 17~18
    volatile uint32_t I2S_TX_RX_DLY_S               : 1; // bit 19~19
    volatile uint32_t I2S_TX_DLY                    : 1; // bit 20~20
    volatile uint32_t I2S_MASTER_MODE               : 1; // bit 21~21
    volatile uint32_t I2S_SERIAL_MODE               : 2; // bit 22~23
    volatile uint32_t I2S_TX_MODE                   : 2; // bit 24~25
    volatile uint32_t I2S_BYPASS_FIFOVLD            : 1; // bit 26~26
    volatile uint32_t I2S_BCK_FORCE_ON              : 1; // bit 27~27
    volatile uint32_t I2S_EN_FORCE_ON               : 1; // bit 28~28
    volatile uint32_t I2S_RSTN_BYPASS               : 1; // bit 29~29
    volatile uint32_t I2S_SW_RESET                  : 1; // bit 30~30
    volatile uint32_t I2S_ENABLE                    : 1; // bit 31~31
};

union APC_REG_APC_I2S_CFG0 {
    volatile uint32_t                               all;
    struct APC_REG_APC_I2S_CFG0_BITS                bit;
};

struct APC_REG_APC_I2S_CFG1_BITS
{
    volatile uint32_t I2S_SLOTNUM                   : 8; // bit 0~7
    volatile uint32_t I2S_LONGSYNC                  : 1; // bit 8~8
    volatile uint32_t I2S_SLOT_LRCK                 : 7; // bit 9~15
    volatile uint32_t I2S_BCK_DIV                   : 10; // bit 16~25
    volatile uint32_t I2S_BCK_DIV_LD                : 1; // bit 26~26
    volatile uint32_t I2S_SAME_EDGE                 : 1; // bit 27~27
    volatile uint32_t I2S_ERR_IRSR                  : 1; // bit 28~28
    volatile uint32_t I2S_ERR_ISR                   : 1; // bit 29~29
    volatile uint32_t I2S_ERR_CLR                   : 1; // bit 30~30
    volatile uint32_t I2S_ERR_MASK                  : 1; // bit 31~31
};

union APC_REG_APC_I2S_CFG1 {
    volatile uint32_t                               all;
    struct APC_REG_APC_I2S_CFG1_BITS                bit;
};

struct APC_REG_APC_I2S_CFG3_BITS
{
    volatile uint32_t I2S_SWRST_SYNC_BYPASS         : 1; // bit 0~0
    volatile uint32_t I2S_CLK_SRC                   : 2; // bit 1~2
    volatile uint32_t RESV_3_31                     : 29; // bit 3~31
};

union APC_REG_APC_I2S_CFG3 {
    volatile uint32_t                               all;
    struct APC_REG_APC_I2S_CFG3_BITS                bit;
};

struct APC_REG_APC_TX_CH_L_DATA_BITS
{
    volatile uint32_t TX_CH_L_DATA                  : 32; // bit 0~31
};

union APC_REG_APC_TX_CH_L_DATA {
    volatile uint32_t                               all;
    struct APC_REG_APC_TX_CH_L_DATA_BITS            bit;
};

struct APC_REG_APC_TX_CH_R_DATA_BITS
{
    volatile uint32_t TX_CH_R_DATA                  : 32; // bit 0~31
};

union APC_REG_APC_TX_CH_R_DATA {
    volatile uint32_t                               all;
    struct APC_REG_APC_TX_CH_R_DATA_BITS            bit;
};

struct APC_REG_APC_RX_CH_L_DATA_BITS
{
    volatile uint32_t RX_CH_L_DATA                  : 32; // bit 0~31
};

union APC_REG_APC_RX_CH_L_DATA {
    volatile uint32_t                               all;
    struct APC_REG_APC_RX_CH_L_DATA_BITS            bit;
};

struct APC_REG_APC_RX_CH_R_DATA_BITS
{
    volatile uint32_t RX_CH_R_DATA                  : 32; // bit 0~31
};

union APC_REG_APC_RX_CH_R_DATA {
    volatile uint32_t                               all;
    struct APC_REG_APC_RX_CH_R_DATA_BITS            bit;
};

struct APC_REG_APC_INTR_TX_MSK_BITS
{
    volatile uint32_t TX_CH_L_FIFO_EMP_MSK          : 1; // bit 0~0
    volatile uint32_t TX_CH_L_FIFO_FUL_MSK          : 1; // bit 1~1
    volatile uint32_t TX_CH_L_FIFO_UNFLOW_MSK       : 1; // bit 2~2
    volatile uint32_t TX_CH_L_FIFO_OVFLOW_MSK       : 1; // bit 3~3
    volatile uint32_t TX_CH_L_DMA_REQ_MSK           : 1; // bit 4~4
    volatile uint32_t TX_CH_R_FIFO_EMP_MSK          : 1; // bit 5~5
    volatile uint32_t TX_CH_R_FIFO_FUL_MSK          : 1; // bit 6~6
    volatile uint32_t TX_CH_R_FIFO_UNFLOW_MSK       : 1; // bit 7~7
    volatile uint32_t TX_CH_R_FIFO_OVFLOW_MSK       : 1; // bit 8~8
    volatile uint32_t TX_CH_R_DMA_REQ_MSK           : 1; // bit 9~9
    volatile uint32_t TX_CH_FIFO_VLD_MSK            : 1; // bit 10~10
    volatile uint32_t RESV_11_31                    : 21; // bit 11~31
};

union APC_REG_APC_INTR_TX_MSK {
    volatile uint32_t                               all;
    struct APC_REG_APC_INTR_TX_MSK_BITS             bit;
};

struct APC_REG_APC_INTR_RX_MSK_BITS
{
    volatile uint32_t RX_CH_L_FIFO_EMP_MSK          : 1; // bit 0~0
    volatile uint32_t RX_CH_L_FIFO_FUL_MSK          : 1; // bit 1~1
    volatile uint32_t RX_CH_L_FIFO_UNFLOW_MSK       : 1; // bit 2~2
    volatile uint32_t RX_CH_L_FIFO_OVFLOW_MSK       : 1; // bit 3~3
    volatile uint32_t RX_CH_L_DMA_REQ_MSK           : 1; // bit 4~4
    volatile uint32_t RX_CH_R_FIFO_EMP_MSK          : 1; // bit 5~5
    volatile uint32_t RX_CH_R_FIFO_FUL_MSK          : 1; // bit 6~6
    volatile uint32_t RX_CH_R_FIFO_UNFLOW_MSK       : 1; // bit 7~7
    volatile uint32_t RX_CH_R_FIFO_OVFLOW_MSK       : 1; // bit 8~8
    volatile uint32_t RX_CH_R_DMA_REQ_MSK           : 1; // bit 9~9
    volatile uint32_t RESV_10_31                    : 22; // bit 10~31
};

union APC_REG_APC_INTR_RX_MSK {
    volatile uint32_t                               all;
    struct APC_REG_APC_INTR_RX_MSK_BITS             bit;
};

struct APC_REG_APC_INTR_TX_CLR_BITS
{
    volatile uint32_t TX_CH_L_FIFO_EMP_CLR          : 1; // bit 0~0
    volatile uint32_t TX_CH_L_FIFO_FUL_CLR          : 1; // bit 1~1
    volatile uint32_t TX_CH_L_FIFO_UNFLOW_CLR       : 1; // bit 2~2
    volatile uint32_t TX_CH_L_FIFO_OVFLOW_CLR       : 1; // bit 3~3
    volatile uint32_t TX_CH_L_DMA_REQ_CLR           : 1; // bit 4~4
    volatile uint32_t TX_CH_R_FIFO_EMP_CLR          : 1; // bit 5~5
    volatile uint32_t TX_CH_R_FIFO_FUL_CLR          : 1; // bit 6~6
    volatile uint32_t TX_CH_R_FIFO_UNFLOW_CLR       : 1; // bit 7~7
    volatile uint32_t TX_CH_R_FIFO_OVFLOW_CLR       : 1; // bit 8~8
    volatile uint32_t TX_CH_R_DMA_REQ_CLR           : 1; // bit 9~9
    volatile uint32_t TX_CH_FIFO_VLD_CLR            : 1; // bit 10~10
    volatile uint32_t RESV_11_31                    : 21; // bit 11~31
};

union APC_REG_APC_INTR_TX_CLR {
    volatile uint32_t                               all;
    struct APC_REG_APC_INTR_TX_CLR_BITS             bit;
};

struct APC_REG_APC_INTR_RX_CLR_BITS
{
    volatile uint32_t RX_CH_L_FIFO_EMP_CLR          : 1; // bit 0~0
    volatile uint32_t RX_CH_L_FIFO_FUL_CLR          : 1; // bit 1~1
    volatile uint32_t RX_CH_L_FIFO_UNFLOW_CLR       : 1; // bit 2~2
    volatile uint32_t RX_CH_L_FIFO_OVFLOW_CLR       : 1; // bit 3~3
    volatile uint32_t RX_CH_L_DMA_REQ_CLR           : 1; // bit 4~4
    volatile uint32_t RX_CH_R_FIFO_EMP_CLR          : 1; // bit 5~5
    volatile uint32_t RX_CH_R_FIFO_FUL_CLR          : 1; // bit 6~6
    volatile uint32_t RX_CH_R_FIFO_UNFLOW_CLR       : 1; // bit 7~7
    volatile uint32_t RX_CH_R_FIFO_OVFLOW_CLR       : 1; // bit 8~8
    volatile uint32_t RX_CH_R_DMA_REQ_CLR           : 1; // bit 9~9
    volatile uint32_t RESV_10_31                    : 22; // bit 10~31
};

union APC_REG_APC_INTR_RX_CLR {
    volatile uint32_t                               all;
    struct APC_REG_APC_INTR_RX_CLR_BITS             bit;
};

struct APC_REG_APC_INTR_TX_IRSR_BITS
{
    volatile uint32_t TX_CH_L_FIFO_EMP_IRSR         : 1; // bit 0~0
    volatile uint32_t TX_CH_L_FIFO_FUL_IRSR         : 1; // bit 1~1
    volatile uint32_t TX_CH_L_FIFO_UNFLOW_IRSR      : 1; // bit 2~2
    volatile uint32_t TX_CH_L_FIFO_OVFLOW_IRSR      : 1; // bit 3~3
    volatile uint32_t TX_CH_L_DMA_REQ_IRSR          : 1; // bit 4~4
    volatile uint32_t TX_CH_R_FIFO_EMP_IRSR         : 1; // bit 5~5
    volatile uint32_t TX_CH_R_FIFO_FUL_IRSR         : 1; // bit 6~6
    volatile uint32_t TX_CH_R_FIFO_UNFLOW_IRSR      : 1; // bit 7~7
    volatile uint32_t TX_CH_R_FIFO_OVFLOW_IRSR      : 1; // bit 8~8
    volatile uint32_t TX_CH_R_DMA_REQ_IRSR          : 1; // bit 9~9
    volatile uint32_t TX_CH_FIFO_VLD_IRSR           : 1; // bit 10~10
    volatile uint32_t RESV_11_31                    : 21; // bit 11~31
};

union APC_REG_APC_INTR_TX_IRSR {
    volatile uint32_t                               all;
    struct APC_REG_APC_INTR_TX_IRSR_BITS            bit;
};

struct APC_REG_APC_INTR_RX_IRSR_BITS
{
    volatile uint32_t RX_CH_L_FIFO_EMP_IRSR         : 1; // bit 0~0
    volatile uint32_t RX_CH_L_FIFO_FUL_IRSR         : 1; // bit 1~1
    volatile uint32_t RX_CH_L_FIFO_UNFLOW_IRSR      : 1; // bit 2~2
    volatile uint32_t RX_CH_L_FIFO_OVFLOW_IRSR      : 1; // bit 3~3
    volatile uint32_t RX_CH_L_DMA_REQ_IRSR          : 1; // bit 4~4
    volatile uint32_t RX_CH_R_FIFO_EMP_IRSR         : 1; // bit 5~5
    volatile uint32_t RX_CH_R_FIFO_FUL_IRSR         : 1; // bit 6~6
    volatile uint32_t RX_CH_R_FIFO_UNFLOW_IRSR      : 1; // bit 7~7
    volatile uint32_t RX_CH_R_FIFO_OVFLOW_IRSR      : 1; // bit 8~8
    volatile uint32_t RX_CH_R_DMA_REQ_IRSR          : 1; // bit 9~9
    volatile uint32_t RESV_10_31                    : 22; // bit 10~31
};

union APC_REG_APC_INTR_RX_IRSR {
    volatile uint32_t                               all;
    struct APC_REG_APC_INTR_RX_IRSR_BITS            bit;
};

struct APC_REG_APC_INTR_TX_ISR_BITS
{
    volatile uint32_t TX_CH_L_FIFO_EMP_ISR          : 1; // bit 0~0
    volatile uint32_t TX_CH_L_FIFO_FUL_ISR          : 1; // bit 1~1
    volatile uint32_t TX_CH_L_FIFO_UNFLOW_ISR       : 1; // bit 2~2
    volatile uint32_t TX_CH_L_FIFO_OVFLOW_ISR       : 1; // bit 3~3
    volatile uint32_t TX_CH_L_DMA_REQ_ISR           : 1; // bit 4~4
    volatile uint32_t TX_CH_R_FIFO_EMP_ISR          : 1; // bit 5~5
    volatile uint32_t TX_CH_R_FIFO_FUL_ISR          : 1; // bit 6~6
    volatile uint32_t TX_CH_R_FIFO_UNFLOW_ISR       : 1; // bit 7~7
    volatile uint32_t TX_CH_R_FIFO_OVFLOW_ISR       : 1; // bit 8~8
    volatile uint32_t TX_CH_R_DMA_REQ_ISR           : 1; // bit 9~9
    volatile uint32_t TX_CH_FIFO_VLD_ISR            : 1; // bit 10~10
    volatile uint32_t RESV_11_31                    : 21; // bit 11~31
};

union APC_REG_APC_INTR_TX_ISR {
    volatile uint32_t                               all;
    struct APC_REG_APC_INTR_TX_ISR_BITS             bit;
};

struct APC_REG_APC_INTR_RX_ISR_BITS
{
    volatile uint32_t RX_CH_L_FIFO_EMP_ISR          : 1; // bit 0~0
    volatile uint32_t RX_CH_L_FIFO_FUL_ISR          : 1; // bit 1~1
    volatile uint32_t RX_CH_L_FIFO_UNFLOW_ISR       : 1; // bit 2~2
    volatile uint32_t RX_CH_L_FIFO_OVFLOW_ISR       : 1; // bit 3~3
    volatile uint32_t RX_CH_L_DMA_REQ_ISR           : 1; // bit 4~4
    volatile uint32_t RX_CH_R_FIFO_EMP_ISR          : 1; // bit 5~5
    volatile uint32_t RX_CH_R_FIFO_FUL_ISR          : 1; // bit 6~6
    volatile uint32_t RX_CH_R_FIFO_UNFLOW_ISR       : 1; // bit 7~7
    volatile uint32_t RX_CH_R_FIFO_OVFLOW_ISR       : 1; // bit 8~8
    volatile uint32_t RX_CH_R_DMA_REQ_ISR           : 1; // bit 9~9
    volatile uint32_t RESV_10_31                    : 22; // bit 10~31
};

union APC_REG_APC_INTR_RX_ISR {
    volatile uint32_t                               all;
    struct APC_REG_APC_INTR_RX_ISR_BITS             bit;
};

struct APC_REG_APC_RSVD_RW_REG_BITS
{
    volatile uint32_t APC_RSVD_RW_REG               : 32; // bit 0~31
};

union APC_REG_APC_RSVD_RW_REG {
    volatile uint32_t                               all;
    struct APC_REG_APC_RSVD_RW_REG_BITS             bit;
};

struct APC_REG_APC_RSVD_RO_REG_BITS
{
    volatile uint32_t APC_RSVD_RO_REG               : 32; // bit 0~31
};

union APC_REG_APC_RSVD_RO_REG {
    volatile uint32_t                               all;
    struct APC_REG_APC_RSVD_RO_REG_BITS             bit;
};

typedef struct
{
    union APC_REG_APC_CFG                           REG_APC_CFG; // 0x000
    union APC_REG_APC_CFG_RSVD0                     REG_APC_CFG_RSVD0; // 0x004
    union APC_REG_APC_CFG_RSVD1                     REG_APC_CFG_RSVD1; // 0x008
    union APC_REG_APC_TX_CH_CFG                     REG_APC_TX_CH_CFG; // 0x00C
    union APC_REG_APC_RX_CH_CFG0                    REG_APC_RX_CH_CFG0; // 0x010
    union APC_REG_APC_RX_CH_CFG1                    REG_APC_RX_CH_CFG1; // 0x014
    union APC_REG_APC_I2S_CFG0                      REG_APC_I2S_CFG0; // 0x018
    union APC_REG_APC_I2S_CFG1                      REG_APC_I2S_CFG1; // 0x01C
    union APC_REG_APC_I2S_CFG3                      REG_APC_I2S_CFG3; // 0x020
    union APC_REG_APC_TX_CH_L_DATA                  REG_APC_TX_CH_L_DATA; // 0x024
    union APC_REG_APC_TX_CH_R_DATA                  REG_APC_TX_CH_R_DATA; // 0x028
    union APC_REG_APC_RX_CH_L_DATA                  REG_APC_RX_CH_L_DATA; // 0x02C
    union APC_REG_APC_RX_CH_R_DATA                  REG_APC_RX_CH_R_DATA; // 0x030
    union APC_REG_APC_INTR_TX_MSK                   REG_APC_INTR_TX_MSK; // 0x034
    union APC_REG_APC_INTR_RX_MSK                   REG_APC_INTR_RX_MSK; // 0x038
    union APC_REG_APC_INTR_TX_CLR                   REG_APC_INTR_TX_CLR; // 0x03C
    union APC_REG_APC_INTR_RX_CLR                   REG_APC_INTR_RX_CLR; // 0x040
    union APC_REG_APC_INTR_TX_IRSR                  REG_APC_INTR_TX_IRSR; // 0x044
    union APC_REG_APC_INTR_RX_IRSR                  REG_APC_INTR_RX_IRSR; // 0x048
    union APC_REG_APC_INTR_TX_ISR                   REG_APC_INTR_TX_ISR; // 0x04C
    union APC_REG_APC_INTR_RX_ISR                   REG_APC_INTR_RX_ISR; // 0x050
    union APC_REG_APC_RSVD_RW_REG                   REG_APC_RSVD_RW_REG; // 0x054
    union APC_REG_APC_RSVD_RO_REG                   REG_APC_RSVD_RO_REG; // 0x058
} APC_RegDef;


#endif // __APC_REGFILE_H__

