//  ----------------------------------------------------------------------
//  File Name   : GenCFold/audio_codec_reg_mars.h
//  Description : C header file generated by Python script.
//  Script Ver  : LS.AUTO_REG.2024.03.01
//  Create Time : 2024-03-20 14:46:55
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __AUDIO_CODEC_REGFILE_H__
#define __AUDIO_CODEC_REGFILE_H__

#include <stdint.h>

#define AUDIO_CODEC_AUD_R0_RSVD_REG0_OFFSET         0x000
#define AUDIO_CODEC_AUD_R0_RSVD_REG0_AUD_ADC_RSV_Pos    0
#define AUDIO_CODEC_AUD_R0_RSVD_REG0_AUD_ADC_RSV_Msk    0xffff

#define AUDIO_CODEC_AUD_R1_GLOBAL0_OFFSET           0x004
#define AUDIO_CODEC_AUD_R1_GLOBAL0_TEST_OUT_SELA_Pos    10
#define AUDIO_CODEC_AUD_R1_GLOBAL0_TEST_OUT_SELA_Msk    0x7c00
#define AUDIO_CODEC_AUD_R1_GLOBAL0_TEST_OUT_SELB_Pos    6
#define AUDIO_CODEC_AUD_R1_GLOBAL0_TEST_OUT_SELB_Msk    0x3c0
#define AUDIO_CODEC_AUD_R1_GLOBAL0_TEST_IN_SEL_Pos    3
#define AUDIO_CODEC_AUD_R1_GLOBAL0_TEST_IN_SEL_Msk    0x38
#define AUDIO_CODEC_AUD_R1_GLOBAL0_DEBUG_MODE_Pos    0
#define AUDIO_CODEC_AUD_R1_GLOBAL0_DEBUG_MODE_Msk    0x7

#define AUDIO_CODEC_AUD_R2_GLOBAL1_OFFSET           0x008
#define AUDIO_CODEC_AUD_R2_GLOBAL1_AUD_EN_VMID_Pos    1
#define AUDIO_CODEC_AUD_R2_GLOBAL1_AUD_EN_VMID_Msk    0x2
#define AUDIO_CODEC_AUD_R2_GLOBAL1_AUD_EN_IREF_Pos    0
#define AUDIO_CODEC_AUD_R2_GLOBAL1_AUD_EN_IREF_Msk    0x1

#define AUDIO_CODEC_AUD_R3_RSVD_REG1_OFFSET         0x00C

#define AUDIO_CODEC_AUD_R4_RSVD_REG2_OFFSET         0x010

#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_OFFSET         0x014
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_ADC_GAIN_COMP_SEL_Pos    11
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_ADC_GAIN_COMP_SEL_Msk    0x800
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_ADC_CAP_CALI_GO_Pos    10
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_ADC_CAP_CALI_GO_Msk    0x400
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_PGA_TOEN_Pos    9
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_PGA_TOEN_Msk    0x200
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_REG_ADC_RSTN_Pos    8
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_REG_ADC_RSTN_Msk    0x100
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_ADCCLK_EN_Pos    7
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_ADCCLK_EN_Msk    0x80
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_ADCOSR_Pos     4
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_ADCOSR_Msk     0x70
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_ADCSR_Pos      0
#define AUDIO_CODEC_AUD_R5_ADC_CTRL0_ADCSR_Msk      0xf

#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_OFFSET         0x018
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_ADC_HPFOUT_SEL_Pos    25
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_ADC_HPFOUT_SEL_Msk    0x2000000
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_ADC_SINGLE_CH_MODE_Pos    24
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_ADC_SINGLE_CH_MODE_Msk    0x1000000
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_HPFCUT_Pos     21
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_HPFCUT_Msk     0xe00000
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_ADC_PGA_LEVEL_Pos    16
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_ADC_PGA_LEVEL_Msk    0x1f0000
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_HPF1EN_Pos     15
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_HPF1EN_Msk     0x8000
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_HPF2EN_Pos     14
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_HPF2EN_Msk     0x4000
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_ADCVOL_L_Pos    7
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_ADCVOL_L_Msk    0x3f80
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_ADCVOL_R_Pos    0
#define AUDIO_CODEC_AUD_R6_ADC_CTRL1_ADCVOL_R_Msk    0x7f

#define AUDIO_CODEC_AUD_R7_ADC_CTRL2_OFFSET         0x01C
#define AUDIO_CODEC_AUD_R7_ADC_CTRL2_NFA1_Pos       16
#define AUDIO_CODEC_AUD_R7_ADC_CTRL2_NFA1_Msk       0x3fff0000
#define AUDIO_CODEC_AUD_R7_ADC_CTRL2_NFEN_Pos       14
#define AUDIO_CODEC_AUD_R7_ADC_CTRL2_NFEN_Msk       0x4000
#define AUDIO_CODEC_AUD_R7_ADC_CTRL2_NFA0_Pos       0
#define AUDIO_CODEC_AUD_R7_ADC_CTRL2_NFA0_Msk       0x3fff

#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_OFFSET         0x020
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_TOLERANCE_Pos    23
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_TOLERANCE_Msk    0x3800000
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_TARGET_Pos     18
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_TARGET_Msk     0x7c0000
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_ALCMODE_Pos    17
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_ALCMODE_Msk    0x20000
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_ALCSEL_Pos     16
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_ALCSEL_Msk     0x10000
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_NG_EN_Pos      15
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_NG_EN_Msk      0x8000
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_NG_Pos         10
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_NG_Msk         0x7c00
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_ALCMAX_Pos     5
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_ALCMAX_Msk     0x3e0
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_ALCMIN_Pos     0
#define AUDIO_CODEC_AUD_R8_ADC_CTRL3_ALCMIN_Msk     0x1f

#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_OFFSET         0x024
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_AUTORST_EN_Pos    26
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_AUTORST_EN_Msk    0x4000000
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_AUTORST_TYPE_Pos    23
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_AUTORST_TYPE_Msk    0x3800000
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_DMIC_ENABLE_Pos    22
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_DMIC_ENABLE_Msk    0x400000
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_DMIC_SRC_Pos    21
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_DMIC_SRC_Msk    0x200000
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_DMIC_LATCH_ADJ_Pos    19
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_DMIC_LATCH_ADJ_Msk    0x180000
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_UNCONNECT_Pos    17
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_UNCONNECT_Msk    0x60000
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_DMIC_MODE_Pos    16
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_DMIC_MODE_Msk    0x10000
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_PEAK_FASTALC_EN_Pos    12
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_PEAK_FASTALC_EN_Msk    0x1000
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_ALCHLD_Pos     8
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_ALCHLD_Msk     0xf00
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_ALCATK_Pos     4
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_ALCATK_Msk     0xf0
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_ALCDCY_Pos     0
#define AUDIO_CODEC_AUD_R9_ADC_CTRL4_ALCDCY_Msk     0xf

#define AUDIO_CODEC_AUD_R10_ADC_CTRL5_OFFSET        0x028
#define AUDIO_CODEC_AUD_R10_ADC_CTRL5_OFFSET_REGEN_Pos    31
#define AUDIO_CODEC_AUD_R10_ADC_CTRL5_OFFSET_REGEN_Msk    0x80000000
#define AUDIO_CODEC_AUD_R10_ADC_CTRL5_OFFSET_REG_Pos    21
#define AUDIO_CODEC_AUD_R10_ADC_CTRL5_OFFSET_REG_Msk    0x7fe00000
#define AUDIO_CODEC_AUD_R10_ADC_CTRL5_FILGAIN_REGEN_Pos    20
#define AUDIO_CODEC_AUD_R10_ADC_CTRL5_FILGAIN_REGEN_Msk    0x100000
#define AUDIO_CODEC_AUD_R10_ADC_CTRL5_FILGAIN_REG_Pos    0
#define AUDIO_CODEC_AUD_R10_ADC_CTRL5_FILGAIN_REG_Msk    0xfffff

#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_OFFSET        0x02C
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_ADC_CAP_CALI_SRC_Pos    20
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_ADC_CAP_CALI_SRC_Msk    0x100000
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_ADC_CAP_CALI_REG_Pos    15
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_ADC_CAP_CALI_REG_Msk    0xf8000
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_ADC_CAP_CALI_EN_REG_Pos    14
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_ADC_CAP_CALI_EN_REG_Msk    0x4000
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_ADC_CAP_CALI_EN_SRC_Pos    13
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_ADC_CAP_CALI_EN_SRC_Msk    0x2000
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_ADC_IDAC_CTRL_Pos    11
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_ADC_IDAC_CTRL_Msk    0x1800
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_ADC_IB_CTRL_Pos    9
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_ADC_IB_CTRL_Msk    0x600
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_ANA_ADC_RST_REG_Pos    7
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_ANA_ADC_RST_REG_Msk    0x80
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_REG_ADC_ANACLK_INV_Pos    6
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_REG_ADC_ANACLK_INV_Msk    0x40
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_ADC_CLK_INV_Pos    5
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_ADC_CLK_INV_Msk    0x20
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_ADC_CLK_LVL_SEL_Pos    4
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_ADC_CLK_LVL_SEL_Msk    0x10
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_ADC_CLK_SRC_Pos    2
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_ADC_CLK_SRC_Msk    0xc
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_REG_AUD_EN_ADC_Pos    1
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_REG_AUD_EN_ADC_Msk    0x2
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_EN_ADC_CLK_Pos    0
#define AUDIO_CODEC_AUD_R11_ADC_CTRL6_AUD_EN_ADC_CLK_Msk    0x1

#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_OFFSET        0x030
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_MODE_Pos    21
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_MODE_Msk    0x200000
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_EN_ADC_VREF_Pos    20
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_EN_ADC_VREF_Msk    0x100000
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_IDAC_BIAS_REG_Pos    19
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_IDAC_BIAS_REG_Msk    0x80000
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_IDAC_BIAS_SRC_Pos    18
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_IDAC_BIAS_SRC_Msk    0x40000
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_IDAC_OS_CTRL_Pos    16
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_IDAC_OS_CTRL_Msk    0x30000
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_INT1_LPR_Pos    15
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_INT1_LPR_Msk    0x8000
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_INT2_LPR_Pos    14
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_INT2_LPR_Msk    0x4000
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_SAR_COMP_LPR_Pos    13
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_SAR_COMP_LPR_Msk    0x2000
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_SAR_DELAY_CTRL_Pos    10
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_SAR_DELAY_CTRL_Msk    0x1c00
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_SAR_TEST_EN_Pos    9
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_SAR_TEST_EN_Msk    0x200
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_ATB_CTRL_Pos    7
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_ADC_ATB_CTRL_Msk    0x180
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_PGA_ZCEN_REG_Pos    6
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_PGA_ZCEN_REG_Msk    0x40
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_PGA_LPR_Pos    5
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_PGA_LPR_Msk    0x20
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_EN_PGA_SINGLE_Pos    4
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_EN_PGA_SINGLE_Msk    0x10
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_PGA_MUTE_Pos    3
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_PGA_MUTE_Msk    0x8
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_REG_AUD_EN_PGA_Pos    2
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_REG_AUD_EN_PGA_Msk    0x4
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_PGA_VCOM_SEL_Pos    1
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_PGA_VCOM_SEL_Msk    0x2
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_EN_PGA_VCMBUF_Pos    0
#define AUDIO_CODEC_AUD_R12_ADC_CTRL7_AUD_EN_PGA_VCMBUF_Msk    0x1

#define AUDIO_CODEC_AUD_R13_RSVD_REG3_OFFSET        0x034

#define AUDIO_CODEC_AUD_R14_RSVD_REG4_OFFSET        0x038

#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_OFFSET        0x03C
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_PWM_SEL_Pos    11
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_PWM_SEL_Msk    0x800
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_USE_REMAP_VER_Pos    10
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_USE_REMAP_VER_Msk    0x400
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_OFF_VAL_Pos    9
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_OFF_VAL_Msk    0x200
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_REV_N_Pos     8
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_REV_N_Msk     0x100
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_REV_P_Pos     7
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_REV_P_Msk     0x80
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_INI_LR_OUT_Pos    6
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_INI_LR_OUT_Msk    0x40
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_REG_CLD_RSTN_Pos    5
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_REG_CLD_RSTN_Msk    0x20
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_CLASSD_CLK_EN_Pos    4
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_CLASSD_CLK_EN_Msk    0x10
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_CLASSD_OSR_Pos    2
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_CLASSD_OSR_Msk    0xc
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_CLASSD_SR_Pos    0
#define AUDIO_CODEC_AUD_R15_CLD_CTRL0_CLASSD_SR_Msk    0x3

#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_OFFSET        0x040
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_DATA_FORCE_Pos    17
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_DATA_FORCE_Msk    0x20000
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_REG_CLASSD_DATA_P_Pos    16
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_REG_CLASSD_DATA_P_Msk    0x10000
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_REG_CLASSD_DATA_N_Pos    15
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_REG_CLASSD_DATA_N_Msk    0x8000
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_ENABLE_DIG_Pos    14
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_ENABLE_DIG_Msk    0x4000
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_EN_Pos    13
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_EN_Msk    0x2000
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_TEST_CTRL_Pos    10
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_TEST_CTRL_Msk    0x1c00
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_SLEWCTL_Pos    7
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_SLEWCTL_Msk    0x380
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_MODE_Pos    5
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_MODE_Msk    0x60
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_HVLDO_EN_Pos    4
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_CLASSD_HVLDO_EN_Msk    0x10
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_AUD_CLD_CLK_INV_Pos    3
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_AUD_CLD_CLK_INV_Msk    0x8
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_AUD_CLD_MCLK_SRC_Pos    1
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_AUD_CLD_MCLK_SRC_Msk    0x6
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_AUD_EN_CLD_CLK_Pos    0
#define AUDIO_CODEC_AUD_R16_CLD_CTRL1_AUD_EN_CLD_CLK_Msk    0x1

#define AUDIO_CODEC_AUD_R25_STATUS0_OFFSET          0x044
#define AUDIO_CODEC_AUD_R25_STATUS0_AUD_ADC_CAP_CALI_Pos    3
#define AUDIO_CODEC_AUD_R25_STATUS0_AUD_ADC_CAP_CALI_Msk    0xf8
#define AUDIO_CODEC_AUD_R25_STATUS0_ADC_CAP_CALI_FAIL_Pos    2
#define AUDIO_CODEC_AUD_R25_STATUS0_ADC_CAP_CALI_FAIL_Msk    0x4
#define AUDIO_CODEC_AUD_R25_STATUS0_ADC_CAP_CALI_DONE_Pos    1
#define AUDIO_CODEC_AUD_R25_STATUS0_ADC_CAP_CALI_DONE_Msk    0x2
#define AUDIO_CODEC_AUD_R25_STATUS0_AUD_ADC_CAP_CALI_FLAG_INST_Pos    0
#define AUDIO_CODEC_AUD_R25_STATUS0_AUD_ADC_CAP_CALI_FLAG_INST_Msk    0x1

struct AUDIO_CODEC_REG_AUD_R0_RSVD_REG0_BITS
{
    volatile uint32_t AUD_ADC_RSV                   : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union AUDIO_CODEC_REG_AUD_R0_RSVD_REG0 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R0_RSVD_REG0_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R1_GLOBAL0_BITS
{
    volatile uint32_t DEBUG_MODE                    : 3; // bit 0~2
    volatile uint32_t TEST_IN_SEL                   : 3; // bit 3~5
    volatile uint32_t TEST_OUT_SELB                 : 4; // bit 6~9
    volatile uint32_t TEST_OUT_SELA                 : 5; // bit 10~14
    volatile uint32_t RESV_15_31                    : 17; // bit 15~31
};

union AUDIO_CODEC_REG_AUD_R1_GLOBAL0 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R1_GLOBAL0_BITS      bit;
};

struct AUDIO_CODEC_REG_AUD_R2_GLOBAL1_BITS
{
    volatile uint32_t AUD_EN_IREF                   : 1; // bit 0~0
    volatile uint32_t AUD_EN_VMID                   : 1; // bit 1~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union AUDIO_CODEC_REG_AUD_R2_GLOBAL1 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R2_GLOBAL1_BITS      bit;
};

struct AUDIO_CODEC_REG_AUD_R3_RSVD_REG1_BITS
{
    volatile uint32_t RESV_0_31                     : 32; // bit 0~31
};

union AUDIO_CODEC_REG_AUD_R3_RSVD_REG1 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R3_RSVD_REG1_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R4_RSVD_REG2_BITS
{
    volatile uint32_t RESV_0_31                     : 32; // bit 0~31
};

union AUDIO_CODEC_REG_AUD_R4_RSVD_REG2 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R4_RSVD_REG2_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R5_ADC_CTRL0_BITS
{
    volatile uint32_t ADCSR                         : 4; // bit 0~3
    volatile uint32_t ADCOSR                        : 3; // bit 4~6
    volatile uint32_t ADCCLK_EN                     : 1; // bit 7~7
    volatile uint32_t REG_ADC_RSTN                  : 1; // bit 8~8
    volatile uint32_t PGA_TOEN                      : 1; // bit 9~9
    volatile uint32_t ADC_CAP_CALI_GO               : 1; // bit 10~10
    volatile uint32_t ADC_GAIN_COMP_SEL             : 1; // bit 11~11
    volatile uint32_t RESV_12_31                    : 20; // bit 12~31
};

union AUDIO_CODEC_REG_AUD_R5_ADC_CTRL0 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R5_ADC_CTRL0_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R6_ADC_CTRL1_BITS
{
    volatile uint32_t ADCVOL_R                      : 7; // bit 0~6
    volatile uint32_t ADCVOL_L                      : 7; // bit 7~13
    volatile uint32_t HPF2EN                        : 1; // bit 14~14
    volatile uint32_t HPF1EN                        : 1; // bit 15~15
    volatile uint32_t ADC_PGA_LEVEL                 : 5; // bit 16~20
    volatile uint32_t HPFCUT                        : 3; // bit 21~23
    volatile uint32_t ADC_SINGLE_CH_MODE            : 1; // bit 24~24
    volatile uint32_t ADC_HPFOUT_SEL                : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AUDIO_CODEC_REG_AUD_R6_ADC_CTRL1 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R6_ADC_CTRL1_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R7_ADC_CTRL2_BITS
{
    volatile uint32_t NFA0                          : 14; // bit 0~13
    volatile uint32_t NFEN                          : 1; // bit 14~14
    volatile uint32_t RESV_15_15                    : 1; // bit 15~15
    volatile uint32_t NFA1                          : 14; // bit 16~29
    volatile uint32_t RESV_30_31                    : 2; // bit 30~31
};

union AUDIO_CODEC_REG_AUD_R7_ADC_CTRL2 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R7_ADC_CTRL2_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R8_ADC_CTRL3_BITS
{
    volatile uint32_t ALCMIN                        : 5; // bit 0~4
    volatile uint32_t ALCMAX                        : 5; // bit 5~9
    volatile uint32_t NG                            : 5; // bit 10~14
    volatile uint32_t NG_EN                         : 1; // bit 15~15
    volatile uint32_t ALCSEL                        : 1; // bit 16~16
    volatile uint32_t ALCMODE                       : 1; // bit 17~17
    volatile uint32_t TARGET                        : 5; // bit 18~22
    volatile uint32_t TOLERANCE                     : 3; // bit 23~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union AUDIO_CODEC_REG_AUD_R8_ADC_CTRL3 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R8_ADC_CTRL3_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R9_ADC_CTRL4_BITS
{
    volatile uint32_t ALCDCY                        : 4; // bit 0~3
    volatile uint32_t ALCATK                        : 4; // bit 4~7
    volatile uint32_t ALCHLD                        : 4; // bit 8~11
    volatile uint32_t PEAK_FASTALC_EN               : 1; // bit 12~12
    volatile uint32_t RESV_13_15                    : 3; // bit 13~15
    volatile uint32_t DMIC_MODE                     : 1; // bit 16~16
    volatile uint32_t UNCONNECT                     : 2; // bit 17~18
    volatile uint32_t DMIC_LATCH_ADJ                : 2; // bit 19~20
    volatile uint32_t DMIC_SRC                      : 1; // bit 21~21
    volatile uint32_t DMIC_ENABLE                   : 1; // bit 22~22
    volatile uint32_t AUTORST_TYPE                  : 3; // bit 23~25
    volatile uint32_t AUTORST_EN                    : 1; // bit 26~26
    volatile uint32_t RESV_27_31                    : 5; // bit 27~31
};

union AUDIO_CODEC_REG_AUD_R9_ADC_CTRL4 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R9_ADC_CTRL4_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R10_ADC_CTRL5_BITS
{
    volatile uint32_t FILGAIN_REG                   : 20; // bit 0~19
    volatile uint32_t FILGAIN_REGEN                 : 1; // bit 20~20
    volatile uint32_t OFFSET_REG                    : 10; // bit 21~30
    volatile uint32_t OFFSET_REGEN                  : 1; // bit 31~31
};

union AUDIO_CODEC_REG_AUD_R10_ADC_CTRL5 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R10_ADC_CTRL5_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R11_ADC_CTRL6_BITS
{
    volatile uint32_t AUD_EN_ADC_CLK                : 1; // bit 0~0
    volatile uint32_t REG_AUD_EN_ADC                : 1; // bit 1~1
    volatile uint32_t AUD_ADC_CLK_SRC               : 2; // bit 2~3
    volatile uint32_t AUD_ADC_CLK_LVL_SEL           : 1; // bit 4~4
    volatile uint32_t AUD_ADC_CLK_INV               : 1; // bit 5~5
    volatile uint32_t REG_ADC_ANACLK_INV            : 1; // bit 6~6
    volatile uint32_t ANA_ADC_RST_REG               : 1; // bit 7~7
    volatile uint32_t RESV_8_8                      : 1; // bit 8~8
    volatile uint32_t AUD_ADC_IB_CTRL               : 2; // bit 9~10
    volatile uint32_t AUD_ADC_IDAC_CTRL             : 2; // bit 11~12
    volatile uint32_t ADC_CAP_CALI_EN_SRC           : 1; // bit 13~13
    volatile uint32_t ADC_CAP_CALI_EN_REG           : 1; // bit 14~14
    volatile uint32_t ADC_CAP_CALI_REG              : 5; // bit 15~19
    volatile uint32_t ADC_CAP_CALI_SRC              : 1; // bit 20~20
    volatile uint32_t RESV_21_31                    : 11; // bit 21~31
};

union AUDIO_CODEC_REG_AUD_R11_ADC_CTRL6 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R11_ADC_CTRL6_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R12_ADC_CTRL7_BITS
{
    volatile uint32_t AUD_EN_PGA_VCMBUF             : 1; // bit 0~0
    volatile uint32_t AUD_PGA_VCOM_SEL              : 1; // bit 1~1
    volatile uint32_t REG_AUD_EN_PGA                : 1; // bit 2~2
    volatile uint32_t AUD_PGA_MUTE                  : 1; // bit 3~3
    volatile uint32_t AUD_EN_PGA_SINGLE             : 1; // bit 4~4
    volatile uint32_t AUD_PGA_LPR                   : 1; // bit 5~5
    volatile uint32_t PGA_ZCEN_REG                  : 1; // bit 6~6
    volatile uint32_t AUD_ADC_ATB_CTRL              : 2; // bit 7~8
    volatile uint32_t AUD_ADC_SAR_TEST_EN           : 1; // bit 9~9
    volatile uint32_t AUD_ADC_SAR_DELAY_CTRL        : 3; // bit 10~12
    volatile uint32_t AUD_ADC_SAR_COMP_LPR          : 1; // bit 13~13
    volatile uint32_t AUD_ADC_INT2_LPR              : 1; // bit 14~14
    volatile uint32_t AUD_ADC_INT1_LPR              : 1; // bit 15~15
    volatile uint32_t AUD_ADC_IDAC_OS_CTRL          : 2; // bit 16~17
    volatile uint32_t AUD_IDAC_BIAS_SRC             : 1; // bit 18~18
    volatile uint32_t AUD_IDAC_BIAS_REG             : 1; // bit 19~19
    volatile uint32_t AUD_EN_ADC_VREF               : 1; // bit 20~20
    volatile uint32_t AUD_ADC_MODE                  : 1; // bit 21~21
    volatile uint32_t RESV_22_31                    : 10; // bit 22~31
};

union AUDIO_CODEC_REG_AUD_R12_ADC_CTRL7 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R12_ADC_CTRL7_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R13_RSVD_REG3_BITS
{
    volatile uint32_t RESV_0_31                     : 32; // bit 0~31
};

union AUDIO_CODEC_REG_AUD_R13_RSVD_REG3 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R13_RSVD_REG3_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R14_RSVD_REG4_BITS
{
    volatile uint32_t RESV_0_31                     : 32; // bit 0~31
};

union AUDIO_CODEC_REG_AUD_R14_RSVD_REG4 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R14_RSVD_REG4_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R15_CLD_CTRL0_BITS
{
    volatile uint32_t CLASSD_SR                     : 2; // bit 0~1
    volatile uint32_t CLASSD_OSR                    : 2; // bit 2~3
    volatile uint32_t CLASSD_CLK_EN                 : 1; // bit 4~4
    volatile uint32_t REG_CLD_RSTN                  : 1; // bit 5~5
    volatile uint32_t INI_LR_OUT                    : 1; // bit 6~6
    volatile uint32_t REV_P                         : 1; // bit 7~7
    volatile uint32_t REV_N                         : 1; // bit 8~8
    volatile uint32_t OFF_VAL                       : 1; // bit 9~9
    volatile uint32_t USE_REMAP_VER                 : 1; // bit 10~10
    volatile uint32_t PWM_SEL                       : 1; // bit 11~11
    volatile uint32_t RESV_12_31                    : 20; // bit 12~31
};

union AUDIO_CODEC_REG_AUD_R15_CLD_CTRL0 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R15_CLD_CTRL0_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R16_CLD_CTRL1_BITS
{
    volatile uint32_t AUD_EN_CLD_CLK                : 1; // bit 0~0
    volatile uint32_t AUD_CLD_MCLK_SRC              : 2; // bit 1~2
    volatile uint32_t AUD_CLD_CLK_INV               : 1; // bit 3~3
    volatile uint32_t CLASSD_HVLDO_EN               : 1; // bit 4~4
    volatile uint32_t CLASSD_MODE                   : 2; // bit 5~6
    volatile uint32_t CLASSD_SLEWCTL                : 3; // bit 7~9
    volatile uint32_t CLASSD_TEST_CTRL              : 3; // bit 10~12
    volatile uint32_t CLASSD_EN                     : 1; // bit 13~13
    volatile uint32_t CLASSD_ENABLE_DIG             : 1; // bit 14~14
    volatile uint32_t REG_CLASSD_DATA_N             : 1; // bit 15~15
    volatile uint32_t REG_CLASSD_DATA_P             : 1; // bit 16~16
    volatile uint32_t CLASSD_DATA_FORCE             : 1; // bit 17~17
    volatile uint32_t RESV_18_31                    : 14; // bit 18~31
};

union AUDIO_CODEC_REG_AUD_R16_CLD_CTRL1 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R16_CLD_CTRL1_BITS    bit;
};

struct AUDIO_CODEC_REG_AUD_R25_STATUS0_BITS
{
    volatile uint32_t AUD_ADC_CAP_CALI_FLAG_INST    : 1; // bit 0~0
    volatile uint32_t ADC_CAP_CALI_DONE             : 1; // bit 1~1
    volatile uint32_t ADC_CAP_CALI_FAIL             : 1; // bit 2~2
    volatile uint32_t AUD_ADC_CAP_CALI              : 5; // bit 3~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union AUDIO_CODEC_REG_AUD_R25_STATUS0 {
    volatile uint32_t                               all;
    struct AUDIO_CODEC_REG_AUD_R25_STATUS0_BITS     bit;
};

typedef struct
{
    union AUDIO_CODEC_REG_AUD_R0_RSVD_REG0          REG_AUD_R0_RSVD_REG0; // 0x000
    union AUDIO_CODEC_REG_AUD_R1_GLOBAL0            REG_AUD_R1_GLOBAL0; // 0x004
    union AUDIO_CODEC_REG_AUD_R2_GLOBAL1            REG_AUD_R2_GLOBAL1; // 0x008
    union AUDIO_CODEC_REG_AUD_R3_RSVD_REG1          REG_AUD_R3_RSVD_REG1; // 0x00C
    union AUDIO_CODEC_REG_AUD_R4_RSVD_REG2          REG_AUD_R4_RSVD_REG2; // 0x010
    union AUDIO_CODEC_REG_AUD_R5_ADC_CTRL0          REG_AUD_R5_ADC_CTRL0; // 0x014
    union AUDIO_CODEC_REG_AUD_R6_ADC_CTRL1          REG_AUD_R6_ADC_CTRL1; // 0x018
    union AUDIO_CODEC_REG_AUD_R7_ADC_CTRL2          REG_AUD_R7_ADC_CTRL2; // 0x01C
    union AUDIO_CODEC_REG_AUD_R8_ADC_CTRL3          REG_AUD_R8_ADC_CTRL3; // 0x020
    union AUDIO_CODEC_REG_AUD_R9_ADC_CTRL4          REG_AUD_R9_ADC_CTRL4; // 0x024
    union AUDIO_CODEC_REG_AUD_R10_ADC_CTRL5         REG_AUD_R10_ADC_CTRL5; // 0x028
    union AUDIO_CODEC_REG_AUD_R11_ADC_CTRL6         REG_AUD_R11_ADC_CTRL6; // 0x02C
    union AUDIO_CODEC_REG_AUD_R12_ADC_CTRL7         REG_AUD_R12_ADC_CTRL7; // 0x030
    union AUDIO_CODEC_REG_AUD_R13_RSVD_REG3         REG_AUD_R13_RSVD_REG3; // 0x034
    union AUDIO_CODEC_REG_AUD_R14_RSVD_REG4         REG_AUD_R14_RSVD_REG4; // 0x038
    union AUDIO_CODEC_REG_AUD_R15_CLD_CTRL0         REG_AUD_R15_CLD_CTRL0; // 0x03C
    union AUDIO_CODEC_REG_AUD_R16_CLD_CTRL1         REG_AUD_R16_CLD_CTRL1; // 0x040
    union AUDIO_CODEC_REG_AUD_R25_STATUS0           REG_AUD_R25_STATUS0; // 0x044
} AUDIO_CODEC_RegDef;


#endif // __AUDIO_CODEC_REGFILE_H__

