//  ----------------------------------------------------------------------
//  File Name   : GenCFold/cmn_buscfg_reg_mars.h
//  Description : C header file generated by Python script.
//  Script Ver  : LS.AUTO_REG.2024.03.01
//  Create Time : 2024-03-20 14:46:55
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __CMN_BUSCFG_REGFILE_H__
#define __CMN_BUSCFG_REGFILE_H__

#include <stdint.h>

#define CMN_BUSCFG_BUS_CLK_CFG0_OFFSET              0x000
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AON_CFG_PCLK_LD_Pos    19
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AON_CFG_PCLK_LD_Msk    0x80000
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AON_CFG_PCLK_N_Pos    14
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AON_CFG_PCLK_N_Msk    0x7c000
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AON_CFG_PCLK_M_Pos    8
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AON_CFG_PCLK_M_Msk    0x3f00
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AP_PERI_PCLK_LD_Pos    7
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AP_PERI_PCLK_LD_Msk    0x80
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AP_PERI_PCLK_N_Pos    4
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AP_PERI_PCLK_N_Msk    0x70
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AP_PERI_PCLK_M_Pos    0
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_AP_PERI_PCLK_M_Msk    0xf

#define CMN_BUSCFG_BUS_CLK_CFG1_OFFSET              0x004
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AP_HCLK_LD_Pos    9
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AP_HCLK_LD_Msk    0x200
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AP_HCLK_N_Pos    6
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AP_HCLK_N_Msk    0x1c0
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AP_HCLK_M_Pos    2
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AP_HCLK_M_Msk    0x3c
#define CMN_BUSCFG_BUS_CLK_CFG1_SEL_SYS_CLK_Pos     0
#define CMN_BUSCFG_BUS_CLK_CFG1_SEL_SYS_CLK_Msk     0x3

#define CMN_BUSCFG_BUS_CLK_CFG2_OFFSET              0x008
#define CMN_BUSCFG_BUS_CLK_CFG2_SEL_OSC_XO24M_CORE_CLK_Pos    0
#define CMN_BUSCFG_BUS_CLK_CFG2_SEL_OSC_XO24M_CORE_CLK_Msk    0x1

#define CMN_BUSCFG_SYSPLL_CFG0_OFFSET               0x00C
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_LOCK_Pos      12
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_LOCK_Msk      0x1000
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_LOCK_CNT_Pos    1
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_LOCK_CNT_Msk    0xffe
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_EN_Pos        0
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_EN_Msk        0x1

#define CMN_BUSCFG_SYSPLL_CFG1_OFFSET               0x010
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_REF_SEL_Pos    23
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_REF_SEL_Msk    0x800000
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_VCO_LDO_OUT_Pos    20
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_VCO_LDO_OUT_Msk    0x700000
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_CP_CPI_Pos    16
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_CP_CPI_Msk    0xf0000
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_CP_CPI_OFF_Pos    12
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_CP_CPI_OFF_Msk    0xf000
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_C1_Pos    9
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_C1_Msk    0xe00
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_C2_Pos    6
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_C2_Msk    0x1c0
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_C3_Pos    3
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_C3_Msk    0x38
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_R2_Pos    0
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_R2_Msk    0x7

#define CMN_BUSCFG_SYSPLL_CFG2_OFFSET               0x014
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_VCO_IBIT_Pos    23
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_VCO_IBIT_Msk    0x3800000
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_VCO_KVCO_Pos    20
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_VCO_KVCO_Msk    0x700000
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_FLASH_DIV_SEL_Pos    18
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_FLASH_DIV_SEL_Msk    0xc0000
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_CORE_DIV_SEL_Pos    14
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_CORE_DIV_SEL_Msk    0x3c000
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_SDM_TESTMODE_Pos    13
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_SDM_TESTMODE_Msk    0x2000
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_SDM_DIVN_INTEG_Pos    4
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_SDM_DIVN_INTEG_Msk    0x1ff0
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_SDM_ORDER_Pos    2
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_SDM_ORDER_Msk    0xc
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_SDM_DITHER_EN_Pos    1
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_SDM_DITHER_EN_Msk    0x2
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_SDM_EN_Pos    0
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_SDM_EN_Msk    0x1

#define CMN_BUSCFG_SYSPLL_CFG3_OFFSET               0x018
#define CMN_BUSCFG_SYSPLL_CFG3_SYSPLL_SDM_DIVN_FRAC_Pos    0
#define CMN_BUSCFG_SYSPLL_CFG3_SYSPLL_SDM_DIVN_FRAC_Msk    0x7ffffff

#define CMN_BUSCFG_CMN_FORCE_CTRL_OFFSET            0x01C
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_SDM_RST_FRC_Pos    6
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_SDM_RST_FRC_Msk    0x40
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_POSTDIV_RST_FRC_Pos    5
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_POSTDIV_RST_FRC_Msk    0x20
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_FBDIV_EN_FRC_Pos    4
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_FBDIV_EN_FRC_Msk    0x10
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_VCO_EN_FRC_Pos    3
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_VCO_EN_FRC_Msk    0x8
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_CP_EN_FRC_Pos    2
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_CP_EN_FRC_Msk    0x4
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_PFD_EN_FRC_Pos    1
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_PFD_EN_FRC_Msk    0x2
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_VCO_LDO_EN_FRC_Pos    0
#define CMN_BUSCFG_CMN_FORCE_CTRL_SYSPLL_VCO_LDO_EN_FRC_Msk    0x1

#define CMN_BUSCFG_CMN_FORCE_DATA_OFFSET            0x020
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_SDM_RST_FRCDATA_Pos    6
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_SDM_RST_FRCDATA_Msk    0x40
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_POSTDIV_RST_FRCDATA_Pos    5
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_POSTDIV_RST_FRCDATA_Msk    0x20
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_FBDIV_EN_FRCDATA_Pos    4
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_FBDIV_EN_FRCDATA_Msk    0x10
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_VCO_EN_FRCDATA_Pos    3
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_VCO_EN_FRCDATA_Msk    0x8
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_CP_EN_FRCDATA_Pos    2
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_CP_EN_FRCDATA_Msk    0x4
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_PFD_EN_FRCDATA_Pos    1
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_PFD_EN_FRCDATA_Msk    0x2
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_VCO_LDO_EN_FRCDATA_Pos    0
#define CMN_BUSCFG_CMN_FORCE_DATA_SYSPLL_VCO_LDO_EN_FRCDATA_Msk    0x1

#define CMN_BUSCFG_ROM_CONFIG_OFFSET                0x024
#define CMN_BUSCFG_ROM_CONFIG_ROM_CONFIG_Pos        0
#define CMN_BUSCFG_ROM_CONFIG_ROM_CONFIG_Msk        0xf

#define CMN_BUSCFG_SRAM_CONFIG_OFFSET               0x028
#define CMN_BUSCFG_SRAM_CONFIG_SRAM_CONFIG_Pos      0
#define CMN_BUSCFG_SRAM_CONFIG_SRAM_CONFIG_Msk      0x7fff

#define CMN_BUSCFG_RF_CONFIG_OFFSET                 0x02C
#define CMN_BUSCFG_RF_CONFIG_RF_CONFIG_Pos          0
#define CMN_BUSCFG_RF_CONFIG_RF_CONFIG_Msk          0x1fff

struct CMN_BUSCFG_REG_BUS_CLK_CFG0_BITS
{
    volatile uint32_t DIV_AP_PERI_PCLK_M            : 4; // bit 0~3
    volatile uint32_t DIV_AP_PERI_PCLK_N            : 3; // bit 4~6
    volatile uint32_t DIV_AP_PERI_PCLK_LD           : 1; // bit 7~7
    volatile uint32_t DIV_AON_CFG_PCLK_M            : 6; // bit 8~13
    volatile uint32_t DIV_AON_CFG_PCLK_N            : 5; // bit 14~18
    volatile uint32_t DIV_AON_CFG_PCLK_LD           : 1; // bit 19~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union CMN_BUSCFG_REG_BUS_CLK_CFG0 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_BUS_CLK_CFG0_BITS         bit;
};

struct CMN_BUSCFG_REG_BUS_CLK_CFG1_BITS
{
    volatile uint32_t SEL_SYS_CLK                   : 2; // bit 0~1
    volatile uint32_t DIV_AP_HCLK_M                 : 4; // bit 2~5
    volatile uint32_t DIV_AP_HCLK_N                 : 3; // bit 6~8
    volatile uint32_t DIV_AP_HCLK_LD                : 1; // bit 9~9
    volatile uint32_t RESV_10_31                    : 22; // bit 10~31
};

union CMN_BUSCFG_REG_BUS_CLK_CFG1 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_BUS_CLK_CFG1_BITS         bit;
};

struct CMN_BUSCFG_REG_BUS_CLK_CFG2_BITS
{
    volatile uint32_t SEL_OSC_XO24M_CORE_CLK        : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union CMN_BUSCFG_REG_BUS_CLK_CFG2 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_BUS_CLK_CFG2_BITS         bit;
};

struct CMN_BUSCFG_REG_SYSPLL_CFG0_BITS
{
    volatile uint32_t SYSPLL_EN                     : 1; // bit 0~0
    volatile uint32_t SYSPLL_LOCK_CNT               : 11; // bit 1~11
    volatile uint32_t SYSPLL_LOCK                   : 1; // bit 12~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union CMN_BUSCFG_REG_SYSPLL_CFG0 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SYSPLL_CFG0_BITS          bit;
};

struct CMN_BUSCFG_REG_SYSPLL_CFG1_BITS
{
    volatile uint32_t SYSPLL_LPF_R2                 : 3; // bit 0~2
    volatile uint32_t SYSPLL_LPF_C3                 : 3; // bit 3~5
    volatile uint32_t SYSPLL_LPF_C2                 : 3; // bit 6~8
    volatile uint32_t SYSPLL_LPF_C1                 : 3; // bit 9~11
    volatile uint32_t SYSPLL_CP_CPI_OFF             : 4; // bit 12~15
    volatile uint32_t SYSPLL_CP_CPI                 : 4; // bit 16~19
    volatile uint32_t SYSPLL_VCO_LDO_OUT            : 3; // bit 20~22
    volatile uint32_t SYSPLL_REF_SEL                : 1; // bit 23~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union CMN_BUSCFG_REG_SYSPLL_CFG1 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SYSPLL_CFG1_BITS          bit;
};

struct CMN_BUSCFG_REG_SYSPLL_CFG2_BITS
{
    volatile uint32_t SYSPLL_SDM_EN                 : 1; // bit 0~0
    volatile uint32_t SYSPLL_SDM_DITHER_EN          : 1; // bit 1~1
    volatile uint32_t SYSPLL_SDM_ORDER              : 2; // bit 2~3
    volatile uint32_t SYSPLL_SDM_DIVN_INTEG         : 9; // bit 4~12
    volatile uint32_t SYSPLL_SDM_TESTMODE           : 1; // bit 13~13
    volatile uint32_t SYSPLL_POSTDIV_CORE_DIV_SEL    : 4; // bit 14~17
    volatile uint32_t SYSPLL_POSTDIV_FLASH_DIV_SEL    : 2; // bit 18~19
    volatile uint32_t SYSPLL_VCO_KVCO               : 3; // bit 20~22
    volatile uint32_t SYSPLL_VCO_IBIT               : 3; // bit 23~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union CMN_BUSCFG_REG_SYSPLL_CFG2 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SYSPLL_CFG2_BITS          bit;
};

struct CMN_BUSCFG_REG_SYSPLL_CFG3_BITS
{
    volatile uint32_t SYSPLL_SDM_DIVN_FRAC          : 27; // bit 0~26
    volatile uint32_t RESV_27_31                    : 5; // bit 27~31
};

union CMN_BUSCFG_REG_SYSPLL_CFG3 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SYSPLL_CFG3_BITS          bit;
};

struct CMN_BUSCFG_REG_CMN_FORCE_CTRL_BITS
{
    volatile uint32_t SYSPLL_VCO_LDO_EN_FRC         : 1; // bit 0~0
    volatile uint32_t SYSPLL_PFD_EN_FRC             : 1; // bit 1~1
    volatile uint32_t SYSPLL_CP_EN_FRC              : 1; // bit 2~2
    volatile uint32_t SYSPLL_VCO_EN_FRC             : 1; // bit 3~3
    volatile uint32_t SYSPLL_FBDIV_EN_FRC           : 1; // bit 4~4
    volatile uint32_t SYSPLL_POSTDIV_RST_FRC        : 1; // bit 5~5
    volatile uint32_t SYSPLL_SDM_RST_FRC            : 1; // bit 6~6
    volatile uint32_t RESV_7_31                     : 25; // bit 7~31
};

union CMN_BUSCFG_REG_CMN_FORCE_CTRL {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_CMN_FORCE_CTRL_BITS       bit;
};

struct CMN_BUSCFG_REG_CMN_FORCE_DATA_BITS
{
    volatile uint32_t SYSPLL_VCO_LDO_EN_FRCDATA     : 1; // bit 0~0
    volatile uint32_t SYSPLL_PFD_EN_FRCDATA         : 1; // bit 1~1
    volatile uint32_t SYSPLL_CP_EN_FRCDATA          : 1; // bit 2~2
    volatile uint32_t SYSPLL_VCO_EN_FRCDATA         : 1; // bit 3~3
    volatile uint32_t SYSPLL_FBDIV_EN_FRCDATA       : 1; // bit 4~4
    volatile uint32_t SYSPLL_POSTDIV_RST_FRCDATA    : 1; // bit 5~5
    volatile uint32_t SYSPLL_SDM_RST_FRCDATA        : 1; // bit 6~6
    volatile uint32_t RESV_7_31                     : 25; // bit 7~31
};

union CMN_BUSCFG_REG_CMN_FORCE_DATA {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_CMN_FORCE_DATA_BITS       bit;
};

struct CMN_BUSCFG_REG_ROM_CONFIG_BITS
{
    volatile uint32_t ROM_CONFIG                    : 4; // bit 0~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union CMN_BUSCFG_REG_ROM_CONFIG {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_ROM_CONFIG_BITS           bit;
};

struct CMN_BUSCFG_REG_SRAM_CONFIG_BITS
{
    volatile uint32_t SRAM_CONFIG                   : 15; // bit 0~14
    volatile uint32_t RESV_15_31                    : 17; // bit 15~31
};

union CMN_BUSCFG_REG_SRAM_CONFIG {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SRAM_CONFIG_BITS          bit;
};

struct CMN_BUSCFG_REG_RF_CONFIG_BITS
{
    volatile uint32_t RF_CONFIG                     : 13; // bit 0~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union CMN_BUSCFG_REG_RF_CONFIG {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_RF_CONFIG_BITS            bit;
};

typedef struct
{
    union CMN_BUSCFG_REG_BUS_CLK_CFG0               REG_BUS_CLK_CFG0; // 0x000
    union CMN_BUSCFG_REG_BUS_CLK_CFG1               REG_BUS_CLK_CFG1; // 0x004
    union CMN_BUSCFG_REG_BUS_CLK_CFG2               REG_BUS_CLK_CFG2; // 0x008
    union CMN_BUSCFG_REG_SYSPLL_CFG0                REG_SYSPLL_CFG0; // 0x00C
    union CMN_BUSCFG_REG_SYSPLL_CFG1                REG_SYSPLL_CFG1; // 0x010
    union CMN_BUSCFG_REG_SYSPLL_CFG2                REG_SYSPLL_CFG2; // 0x014
    union CMN_BUSCFG_REG_SYSPLL_CFG3                REG_SYSPLL_CFG3; // 0x018
    union CMN_BUSCFG_REG_CMN_FORCE_CTRL             REG_CMN_FORCE_CTRL; // 0x01C
    union CMN_BUSCFG_REG_CMN_FORCE_DATA             REG_CMN_FORCE_DATA; // 0x020
    union CMN_BUSCFG_REG_ROM_CONFIG                 REG_ROM_CONFIG; // 0x024
    union CMN_BUSCFG_REG_SRAM_CONFIG                REG_SRAM_CONFIG; // 0x028
    union CMN_BUSCFG_REG_RF_CONFIG                  REG_RF_CONFIG; // 0x02C
} CMN_BUSCFG_RegDef;


#endif // __CMN_BUSCFG_REGFILE_H__

