//  ----------------------------------------------------------------------
//  File Name   : GenCFold/cmn_syscfg_reg_mars.h
//  Description : C header file generated by Python script.
//  Script Ver  : LS.AUTO_REG.2024.03.01
//  Create Time : 2024-03-20 14:46:55
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __CMN_SYSCFG_REGFILE_H__
#define __CMN_SYSCFG_REGFILE_H__

#include <stdint.h>

#define CMN_SYSCFG_TEST_CTRL_OFFSET                 0x000
#define CMN_SYSCFG_TEST_CTRL_DBG_OUT_EXCHANGE_Pos    15
#define CMN_SYSCFG_TEST_CTRL_DBG_OUT_EXCHANGE_Msk    0x18000
#define CMN_SYSCFG_TEST_CTRL_DBG_OUT_SEL_Pos        10
#define CMN_SYSCFG_TEST_CTRL_DBG_OUT_SEL_Msk        0x7c00
#define CMN_SYSCFG_TEST_CTRL_DBG_OUT_EN_Pos         9
#define CMN_SYSCFG_TEST_CTRL_DBG_OUT_EN_Msk         0x200
#define CMN_SYSCFG_TEST_CTRL_DBG_CLK_DIV_SEL_Pos    6
#define CMN_SYSCFG_TEST_CTRL_DBG_CLK_DIV_SEL_Msk    0x1c0
#define CMN_SYSCFG_TEST_CTRL_DBG_CLK_SEL_Pos        1
#define CMN_SYSCFG_TEST_CTRL_DBG_CLK_SEL_Msk        0x3e
#define CMN_SYSCFG_TEST_CTRL_DBG_CLK_EN_Pos         0
#define CMN_SYSCFG_TEST_CTRL_DBG_CLK_EN_Msk         0x1

#define CMN_SYSCFG_RST_CTRL0_OFFSET                 0x004
#define CMN_SYSCFG_RST_CTRL0_SYSRSTREQ2AP_RST_EN_Pos    31
#define CMN_SYSCFG_RST_CTRL0_SYSRSTREQ2AP_RST_EN_Msk    0x80000000
#define CMN_SYSCFG_RST_CTRL0_SYSRSTREQ2AON_RST_EN_Pos    30
#define CMN_SYSCFG_RST_CTRL0_SYSRSTREQ2AON_RST_EN_Msk    0x40000000
#define CMN_SYSCFG_RST_CTRL0_AP_RST_2_AON_RST_EN_Pos    29
#define CMN_SYSCFG_RST_CTRL0_AP_RST_2_AON_RST_EN_Msk    0x20000000
#define CMN_SYSCFG_RST_CTRL0_LUNA_RESET_Pos         16
#define CMN_SYSCFG_RST_CTRL0_LUNA_RESET_Msk         0x10000
#define CMN_SYSCFG_RST_CTRL0_MCU_CORE_RESET_Pos     15
#define CMN_SYSCFG_RST_CTRL0_MCU_CORE_RESET_Msk     0x8000
#define CMN_SYSCFG_RST_CTRL0_APC_CORE_RESET_Pos     14
#define CMN_SYSCFG_RST_CTRL0_APC_CORE_RESET_Msk     0x4000
#define CMN_SYSCFG_RST_CTRL0_APC_REG_RESET_Pos      13
#define CMN_SYSCFG_RST_CTRL0_APC_REG_RESET_Msk      0x2000
#define CMN_SYSCFG_RST_CTRL0_CODEC_ASYNC_RESET_Pos    12
#define CMN_SYSCFG_RST_CTRL0_CODEC_ASYNC_RESET_Msk    0x1000
#define CMN_SYSCFG_RST_CTRL0_CODEC_REG_RESET_Pos    11
#define CMN_SYSCFG_RST_CTRL0_CODEC_REG_RESET_Msk    0x800
#define CMN_SYSCFG_RST_CTRL0_I2S_RESET_Pos          10
#define CMN_SYSCFG_RST_CTRL0_I2S_RESET_Msk          0x400
#define CMN_SYSCFG_RST_CTRL0_GPT_RESET_Pos          9
#define CMN_SYSCFG_RST_CTRL0_GPT_RESET_Msk          0x200
#define CMN_SYSCFG_RST_CTRL0_FLASHC_RESET_Pos       8
#define CMN_SYSCFG_RST_CTRL0_FLASHC_RESET_Msk       0x100
#define CMN_SYSCFG_RST_CTRL0_DMA_RESET_Pos          7
#define CMN_SYSCFG_RST_CTRL0_DMA_RESET_Msk          0x80
#define CMN_SYSCFG_RST_CTRL0_GPADC_RESET_Pos        6
#define CMN_SYSCFG_RST_CTRL0_GPADC_RESET_Msk        0x40
#define CMN_SYSCFG_RST_CTRL0_GPIO0_RESET_Pos        5
#define CMN_SYSCFG_RST_CTRL0_GPIO0_RESET_Msk        0x20
#define CMN_SYSCFG_RST_CTRL0_I2C0_RESET_Pos         4
#define CMN_SYSCFG_RST_CTRL0_I2C0_RESET_Msk         0x10
#define CMN_SYSCFG_RST_CTRL0_SPI0_RESET_Pos         3
#define CMN_SYSCFG_RST_CTRL0_SPI0_RESET_Msk         0x8
#define CMN_SYSCFG_RST_CTRL0_IR_RESET_Pos           2
#define CMN_SYSCFG_RST_CTRL0_IR_RESET_Msk           0x4
#define CMN_SYSCFG_RST_CTRL0_UART1_RESET_Pos        1
#define CMN_SYSCFG_RST_CTRL0_UART1_RESET_Msk        0x2
#define CMN_SYSCFG_RST_CTRL0_UART0_RESET_Pos        0
#define CMN_SYSCFG_RST_CTRL0_UART0_RESET_Msk        0x1

#define CMN_SYSCFG_CLK_EN_CTRL0_OFFSET              0x008
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_CORE_32K_CLK_Pos    14
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_CORE_32K_CLK_Msk    0x4000
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_APC_CLK_Pos     13
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_APC_CLK_Msk     0x2000
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_CODEC_CLK_Pos    12
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_CODEC_CLK_Msk    0x1000
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_I2S_CLK_Pos     11
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_I2S_CLK_Msk     0x800
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_LUNA_CLK_Pos    10
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_LUNA_CLK_Msk    0x400
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_GPT_T0_CLK_Pos    9
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_GPT_T0_CLK_Msk    0x200
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_GPT_S_CLK_Pos    8
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_GPT_S_CLK_Msk    0x100
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_GPT_CLK_Pos     7
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_GPT_CLK_Msk     0x80
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_FLASHC_CLK_Pos    6
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_FLASHC_CLK_Msk    0x40
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_DMA_CLK_Pos     5
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_DMA_CLK_Msk     0x20
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_GPADC_CLK_Pos    4
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_GPADC_CLK_Msk    0x10
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_GPIO0_CLK_Pos    3
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_GPIO0_CLK_Msk    0x8
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_I2C0_CLK_Pos    2
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_I2C0_CLK_Msk    0x4
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_SPI0_CLK_Pos    1
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_SPI0_CLK_Msk    0x2
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_IR_CLK_Pos      0
#define CMN_SYSCFG_CLK_EN_CTRL0_ENA_IR_CLK_Msk      0x1

#define CMN_SYSCFG_PERI_CLK_CFG0_OFFSET             0x00C
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_SPI0_CLK_LD_Pos    30
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_SPI0_CLK_LD_Msk    0x40000000
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_SPI0_CLK_N_Pos    27
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_SPI0_CLK_N_Msk    0x38000000
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_SPI0_CLK_M_Pos    23
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_SPI0_CLK_M_Msk    0x7800000
#define CMN_SYSCFG_PERI_CLK_CFG0_SEL_SPI0_CLK_Pos    22
#define CMN_SYSCFG_PERI_CLK_CFG0_SEL_SPI0_CLK_Msk    0x400000
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_UART0_CLK_LD_Pos    21
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_UART0_CLK_LD_Msk    0x200000
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_UART0_CLK_N_Pos    11
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_UART0_CLK_N_Msk    0x1ff800
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_UART0_CLK_M_Pos    1
#define CMN_SYSCFG_PERI_CLK_CFG0_DIV_UART0_CLK_M_Msk    0x7fe
#define CMN_SYSCFG_PERI_CLK_CFG0_SEL_UART0_CLK_Pos    0
#define CMN_SYSCFG_PERI_CLK_CFG0_SEL_UART0_CLK_Msk    0x1

#define CMN_SYSCFG_PERI_CLK_CFG1_OFFSET             0x010
#define CMN_SYSCFG_PERI_CLK_CFG1_DIV_IR_TXCLK_LD_Pos    28
#define CMN_SYSCFG_PERI_CLK_CFG1_DIV_IR_TXCLK_LD_Msk    0x10000000
#define CMN_SYSCFG_PERI_CLK_CFG1_DIV_IR_TXCLK_M_Pos    22
#define CMN_SYSCFG_PERI_CLK_CFG1_DIV_IR_TXCLK_M_Msk    0xfc00000
#define CMN_SYSCFG_PERI_CLK_CFG1_DIV_UART1_CLK_LD_Pos    21
#define CMN_SYSCFG_PERI_CLK_CFG1_DIV_UART1_CLK_LD_Msk    0x200000
#define CMN_SYSCFG_PERI_CLK_CFG1_DIV_UART1_CLK_N_Pos    11
#define CMN_SYSCFG_PERI_CLK_CFG1_DIV_UART1_CLK_N_Msk    0x1ff800
#define CMN_SYSCFG_PERI_CLK_CFG1_DIV_UART1_CLK_M_Pos    1
#define CMN_SYSCFG_PERI_CLK_CFG1_DIV_UART1_CLK_M_Msk    0x7fe
#define CMN_SYSCFG_PERI_CLK_CFG1_SEL_UART1_CLK_Pos    0
#define CMN_SYSCFG_PERI_CLK_CFG1_SEL_UART1_CLK_Msk    0x1

#define CMN_SYSCFG_PERI_CLK_CFG2_OFFSET             0x014
#define CMN_SYSCFG_PERI_CLK_CFG2_DIV_GPADC_CLK_LD_Pos    14
#define CMN_SYSCFG_PERI_CLK_CFG2_DIV_GPADC_CLK_LD_Msk    0x4000
#define CMN_SYSCFG_PERI_CLK_CFG2_DIV_GPADC_CLK_M_Pos    4
#define CMN_SYSCFG_PERI_CLK_CFG2_DIV_GPADC_CLK_M_Msk    0x3ff0
#define CMN_SYSCFG_PERI_CLK_CFG2_DIV_FLASHC_CLK_LD_Pos    3
#define CMN_SYSCFG_PERI_CLK_CFG2_DIV_FLASHC_CLK_LD_Msk    0x8
#define CMN_SYSCFG_PERI_CLK_CFG2_DIV_FLASHC_CLK_M_Pos    1
#define CMN_SYSCFG_PERI_CLK_CFG2_DIV_FLASHC_CLK_M_Msk    0x6
#define CMN_SYSCFG_PERI_CLK_CFG2_SEL_FLASHC_CLK_Pos    0
#define CMN_SYSCFG_PERI_CLK_CFG2_SEL_FLASHC_CLK_Msk    0x1

#define CMN_SYSCFG_PERI_CLK_CFG3_OFFSET             0x018
#define CMN_SYSCFG_PERI_CLK_CFG3_DIV_GPT_T0_CLK_LD_Pos    11
#define CMN_SYSCFG_PERI_CLK_CFG3_DIV_GPT_T0_CLK_LD_Msk    0x800
#define CMN_SYSCFG_PERI_CLK_CFG3_DIV_GPT_T0_CLK_M_Pos    6
#define CMN_SYSCFG_PERI_CLK_CFG3_DIV_GPT_T0_CLK_M_Msk    0x7c0
#define CMN_SYSCFG_PERI_CLK_CFG3_DIV_GPT_S_CLK_LD_Pos    5
#define CMN_SYSCFG_PERI_CLK_CFG3_DIV_GPT_S_CLK_LD_Msk    0x20
#define CMN_SYSCFG_PERI_CLK_CFG3_DIV_GPT_S_CLK_M_Pos    0
#define CMN_SYSCFG_PERI_CLK_CFG3_DIV_GPT_S_CLK_M_Msk    0x1f

#define CMN_SYSCFG_PERI_CLK_CFG4_OFFSET             0x020
#define CMN_SYSCFG_PERI_CLK_CFG4_ENA_MTIME_TOGGLE_A_Pos    7
#define CMN_SYSCFG_PERI_CLK_CFG4_ENA_MTIME_TOGGLE_A_Msk    0x80
#define CMN_SYSCFG_PERI_CLK_CFG4_DIV_MTIME_TOGGLE_A_LD_Pos    6
#define CMN_SYSCFG_PERI_CLK_CFG4_DIV_MTIME_TOGGLE_A_LD_Msk    0x40
#define CMN_SYSCFG_PERI_CLK_CFG4_DIV_MTIME_TOGGLE_A_M_Pos    0
#define CMN_SYSCFG_PERI_CLK_CFG4_DIV_MTIME_TOGGLE_A_M_Msk    0x3f

#define CMN_SYSCFG_SW_RESET_AP_OFFSET               0x02C
#define CMN_SYSCFG_SW_RESET_AP_AP_RESET_Pos         0
#define CMN_SYSCFG_SW_RESET_AP_AP_RESET_Msk         0x1

#define CMN_SYSCFG_DMA_HS_SEL_OFFSET                0x030

#define CMN_SYSCFG_ANA_RSVD_OFFSET                  0x034
#define CMN_SYSCFG_ANA_RSVD_ANA_A2D_RSVD_Pos        16
#define CMN_SYSCFG_ANA_RSVD_ANA_A2D_RSVD_Msk        0xff0000
#define CMN_SYSCFG_ANA_RSVD_ANA_D2A_RSVD_Pos        0
#define CMN_SYSCFG_ANA_RSVD_ANA_D2A_RSVD_Msk        0xffff

#define CMN_SYSCFG_MCU_CFG_OFFSET                   0x038
#define CMN_SYSCFG_MCU_CFG_DBG_STOPTIME_Pos         6
#define CMN_SYSCFG_MCU_CFG_DBG_STOPTIME_Msk         0x40
#define CMN_SYSCFG_MCU_CFG_JTAG_BK_ENABLE_Pos       5
#define CMN_SYSCFG_MCU_CFG_JTAG_BK_ENABLE_Msk       0x20
#define CMN_SYSCFG_MCU_CFG_JTAG_DWBYPASS_Pos        4
#define CMN_SYSCFG_MCU_CFG_JTAG_DWBYPASS_Msk        0x10
#define CMN_SYSCFG_MCU_CFG_DBG_STOP_AT_BOOT_Pos     3
#define CMN_SYSCFG_MCU_CFG_DBG_STOP_AT_BOOT_Msk     0x8
#define CMN_SYSCFG_MCU_CFG_DBG_STOP_Pos             2
#define CMN_SYSCFG_MCU_CFG_DBG_STOP_Msk             0x4
#define CMN_SYSCFG_MCU_CFG_OVERRIDE_DM_SLEEP_Pos    1
#define CMN_SYSCFG_MCU_CFG_OVERRIDE_DM_SLEEP_Msk    0x2
#define CMN_SYSCFG_MCU_CFG_STOP_ON_RESET_Pos        0
#define CMN_SYSCFG_MCU_CFG_STOP_ON_RESET_Msk        0x1

#define CMN_SYSCFG_MCU_RST_ADDR_OFFSET              0x03C
#define CMN_SYSCFG_MCU_RST_ADDR_RESET_VECTOR_Pos    0
#define CMN_SYSCFG_MCU_RST_ADDR_RESET_VECTOR_Msk    0xffffffff

#define CMN_SYSCFG_VIO_OK_IMR_OFFSET                0x040
#define CMN_SYSCFG_VIO_OK_IMR_VIO_OK_FALL_IMR_Pos    1
#define CMN_SYSCFG_VIO_OK_IMR_VIO_OK_FALL_IMR_Msk    0x2
#define CMN_SYSCFG_VIO_OK_IMR_VIO_OK_RISE_IMR_Pos    0
#define CMN_SYSCFG_VIO_OK_IMR_VIO_OK_RISE_IMR_Msk    0x1

#define CMN_SYSCFG_VIO_OK_IRSR_OFFSET               0x044
#define CMN_SYSCFG_VIO_OK_IRSR_VIO_OK_FALL_IRSR_Pos    1
#define CMN_SYSCFG_VIO_OK_IRSR_VIO_OK_FALL_IRSR_Msk    0x2
#define CMN_SYSCFG_VIO_OK_IRSR_VIO_OK_RISE_IRSR_Pos    0
#define CMN_SYSCFG_VIO_OK_IRSR_VIO_OK_RISE_IRSR_Msk    0x1

#define CMN_SYSCFG_VIO_OK_ISR_OFFSET                0x048
#define CMN_SYSCFG_VIO_OK_ISR_VIO_OK_FALL_ISR_Pos    1
#define CMN_SYSCFG_VIO_OK_ISR_VIO_OK_FALL_ISR_Msk    0x2
#define CMN_SYSCFG_VIO_OK_ISR_VIO_OK_RISE_ISR_Pos    0
#define CMN_SYSCFG_VIO_OK_ISR_VIO_OK_RISE_ISR_Msk    0x1

#define CMN_SYSCFG_HIT_COUNT_OFFSET                 0x04C
#define CMN_SYSCFG_HIT_COUNT_E1_HIT_CNT_Pos         0
#define CMN_SYSCFG_HIT_COUNT_E1_HIT_CNT_Msk         0xffffffff

#define CMN_SYSCFG_MISS_COUNT_OFFSET                0x050
#define CMN_SYSCFG_MISS_COUNT_E1_MISS_CNT_Pos       0
#define CMN_SYSCFG_MISS_COUNT_E1_MISS_CNT_Msk       0xffffffff

#define CMN_SYSCFG_BYP_COUNT_OFFSET                 0x054
#define CMN_SYSCFG_BYP_COUNT_E1_BYP_CNT_Pos         0
#define CMN_SYSCFG_BYP_COUNT_E1_BYP_CNT_Msk         0xffffffff

#define CMN_SYSCFG_CACHE_CNT_CLR_OFFSET             0x058
#define CMN_SYSCFG_CACHE_CNT_CLR_E1_BYP_CNT_CLR_Pos    2
#define CMN_SYSCFG_CACHE_CNT_CLR_E1_BYP_CNT_CLR_Msk    0x4
#define CMN_SYSCFG_CACHE_CNT_CLR_E1_MISS_CNT_CLR_Pos    1
#define CMN_SYSCFG_CACHE_CNT_CLR_E1_MISS_CNT_CLR_Msk    0x2
#define CMN_SYSCFG_CACHE_CNT_CLR_E1_HIT_CNT_CLR_Pos    0
#define CMN_SYSCFG_CACHE_CNT_CLR_E1_HIT_CNT_CLR_Msk    0x1

#define CMN_SYSCFG_CMN_RSVD_OFFSET                  0x05C
#define CMN_SYSCFG_CMN_RSVD_CMN_CFG_RSVD_Pos        0
#define CMN_SYSCFG_CMN_RSVD_CMN_CFG_RSVD_Msk        0xffffffff

struct CMN_SYSCFG_REG_TEST_CTRL_BITS
{
    volatile uint32_t DBG_CLK_EN                    : 1; // bit 0~0
    volatile uint32_t DBG_CLK_SEL                   : 5; // bit 1~5
    volatile uint32_t DBG_CLK_DIV_SEL               : 3; // bit 6~8
    volatile uint32_t DBG_OUT_EN                    : 1; // bit 9~9
    volatile uint32_t DBG_OUT_SEL                   : 5; // bit 10~14
    volatile uint32_t DBG_OUT_EXCHANGE              : 2; // bit 15~16
    volatile uint32_t RESV_17_31                    : 15; // bit 17~31
};

union CMN_SYSCFG_REG_TEST_CTRL {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_TEST_CTRL_BITS            bit;
};

struct CMN_SYSCFG_REG_RST_CTRL0_BITS
{
    volatile uint32_t UART0_RESET                   : 1; // bit 0~0
    volatile uint32_t UART1_RESET                   : 1; // bit 1~1
    volatile uint32_t IR_RESET                      : 1; // bit 2~2
    volatile uint32_t SPI0_RESET                    : 1; // bit 3~3
    volatile uint32_t I2C0_RESET                    : 1; // bit 4~4
    volatile uint32_t GPIO0_RESET                   : 1; // bit 5~5
    volatile uint32_t GPADC_RESET                   : 1; // bit 6~6
    volatile uint32_t DMA_RESET                     : 1; // bit 7~7
    volatile uint32_t FLASHC_RESET                  : 1; // bit 8~8
    volatile uint32_t GPT_RESET                     : 1; // bit 9~9
    volatile uint32_t I2S_RESET                     : 1; // bit 10~10
    volatile uint32_t CODEC_REG_RESET               : 1; // bit 11~11
    volatile uint32_t CODEC_ASYNC_RESET             : 1; // bit 12~12
    volatile uint32_t APC_REG_RESET                 : 1; // bit 13~13
    volatile uint32_t APC_CORE_RESET                : 1; // bit 14~14
    volatile uint32_t MCU_CORE_RESET                : 1; // bit 15~15
    volatile uint32_t LUNA_RESET                    : 1; // bit 16~16
    volatile uint32_t RESV_17_28                    : 12; // bit 17~28
    volatile uint32_t AP_RST_2_AON_RST_EN           : 1; // bit 29~29
    volatile uint32_t SYSRSTREQ2AON_RST_EN          : 1; // bit 30~30
    volatile uint32_t SYSRSTREQ2AP_RST_EN           : 1; // bit 31~31
};

union CMN_SYSCFG_REG_RST_CTRL0 {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_RST_CTRL0_BITS            bit;
};

struct CMN_SYSCFG_REG_CLK_EN_CTRL0_BITS
{
    volatile uint32_t ENA_IR_CLK                    : 1; // bit 0~0
    volatile uint32_t ENA_SPI0_CLK                  : 1; // bit 1~1
    volatile uint32_t ENA_I2C0_CLK                  : 1; // bit 2~2
    volatile uint32_t ENA_GPIO0_CLK                 : 1; // bit 3~3
    volatile uint32_t ENA_GPADC_CLK                 : 1; // bit 4~4
    volatile uint32_t ENA_DMA_CLK                   : 1; // bit 5~5
    volatile uint32_t ENA_FLASHC_CLK                : 1; // bit 6~6
    volatile uint32_t ENA_GPT_CLK                   : 1; // bit 7~7
    volatile uint32_t ENA_GPT_S_CLK                 : 1; // bit 8~8
    volatile uint32_t ENA_GPT_T0_CLK                : 1; // bit 9~9
    volatile uint32_t ENA_LUNA_CLK                  : 1; // bit 10~10
    volatile uint32_t ENA_I2S_CLK                   : 1; // bit 11~11
    volatile uint32_t ENA_CODEC_CLK                 : 1; // bit 12~12
    volatile uint32_t ENA_APC_CLK                   : 1; // bit 13~13
    volatile uint32_t ENA_CORE_32K_CLK              : 1; // bit 14~14
    volatile uint32_t RESV_15_31                    : 17; // bit 15~31
};

union CMN_SYSCFG_REG_CLK_EN_CTRL0 {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_CLK_EN_CTRL0_BITS         bit;
};

struct CMN_SYSCFG_REG_PERI_CLK_CFG0_BITS
{
    volatile uint32_t SEL_UART0_CLK                 : 1; // bit 0~0
    volatile uint32_t DIV_UART0_CLK_M               : 10; // bit 1~10
    volatile uint32_t DIV_UART0_CLK_N               : 10; // bit 11~20
    volatile uint32_t DIV_UART0_CLK_LD              : 1; // bit 21~21
    volatile uint32_t SEL_SPI0_CLK                  : 1; // bit 22~22
    volatile uint32_t DIV_SPI0_CLK_M                : 4; // bit 23~26
    volatile uint32_t DIV_SPI0_CLK_N                : 3; // bit 27~29
    volatile uint32_t DIV_SPI0_CLK_LD               : 1; // bit 30~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union CMN_SYSCFG_REG_PERI_CLK_CFG0 {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_PERI_CLK_CFG0_BITS        bit;
};

struct CMN_SYSCFG_REG_PERI_CLK_CFG1_BITS
{
    volatile uint32_t SEL_UART1_CLK                 : 1; // bit 0~0
    volatile uint32_t DIV_UART1_CLK_M               : 10; // bit 1~10
    volatile uint32_t DIV_UART1_CLK_N               : 10; // bit 11~20
    volatile uint32_t DIV_UART1_CLK_LD              : 1; // bit 21~21
    volatile uint32_t DIV_IR_TXCLK_M                : 6; // bit 22~27
    volatile uint32_t DIV_IR_TXCLK_LD               : 1; // bit 28~28
    volatile uint32_t RESV_29_31                    : 3; // bit 29~31
};

union CMN_SYSCFG_REG_PERI_CLK_CFG1 {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_PERI_CLK_CFG1_BITS        bit;
};

struct CMN_SYSCFG_REG_PERI_CLK_CFG2_BITS
{
    volatile uint32_t SEL_FLASHC_CLK                : 1; // bit 0~0
    volatile uint32_t DIV_FLASHC_CLK_M              : 2; // bit 1~2
    volatile uint32_t DIV_FLASHC_CLK_LD             : 1; // bit 3~3
    volatile uint32_t DIV_GPADC_CLK_M               : 10; // bit 4~13
    volatile uint32_t DIV_GPADC_CLK_LD              : 1; // bit 14~14
    volatile uint32_t RESV_15_31                    : 17; // bit 15~31
};

union CMN_SYSCFG_REG_PERI_CLK_CFG2 {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_PERI_CLK_CFG2_BITS        bit;
};

struct CMN_SYSCFG_REG_PERI_CLK_CFG3_BITS
{
    volatile uint32_t DIV_GPT_S_CLK_M               : 5; // bit 0~4
    volatile uint32_t DIV_GPT_S_CLK_LD              : 1; // bit 5~5
    volatile uint32_t DIV_GPT_T0_CLK_M              : 5; // bit 6~10
    volatile uint32_t DIV_GPT_T0_CLK_LD             : 1; // bit 11~11
    volatile uint32_t RESV_12_31                    : 20; // bit 12~31
};

union CMN_SYSCFG_REG_PERI_CLK_CFG3 {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_PERI_CLK_CFG3_BITS        bit;
};

struct CMN_SYSCFG_REG_PERI_CLK_CFG4_BITS
{
    volatile uint32_t DIV_MTIME_TOGGLE_A_M          : 6; // bit 0~5
    volatile uint32_t DIV_MTIME_TOGGLE_A_LD         : 1; // bit 6~6
    volatile uint32_t ENA_MTIME_TOGGLE_A            : 1; // bit 7~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union CMN_SYSCFG_REG_PERI_CLK_CFG4 {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_PERI_CLK_CFG4_BITS        bit;
};

struct CMN_SYSCFG_REG_SW_RESET_AP_BITS
{
    volatile uint32_t AP_RESET                      : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union CMN_SYSCFG_REG_SW_RESET_AP {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_SW_RESET_AP_BITS          bit;
};

struct CMN_SYSCFG_REG_DMA_HS_SEL_BITS
{
    volatile uint32_t RESV_0_31                     : 32; // bit 0~31
};

union CMN_SYSCFG_REG_DMA_HS_SEL {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_DMA_HS_SEL_BITS           bit;
};

struct CMN_SYSCFG_REG_ANA_RSVD_BITS
{
    volatile uint32_t ANA_D2A_RSVD                  : 16; // bit 0~15
    volatile uint32_t ANA_A2D_RSVD                  : 8; // bit 16~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union CMN_SYSCFG_REG_ANA_RSVD {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_ANA_RSVD_BITS             bit;
};

struct CMN_SYSCFG_REG_MCU_CFG_BITS
{
    volatile uint32_t STOP_ON_RESET                 : 1; // bit 0~0
    volatile uint32_t OVERRIDE_DM_SLEEP             : 1; // bit 1~1
    volatile uint32_t DBG_STOP                      : 1; // bit 2~2
    volatile uint32_t DBG_STOP_AT_BOOT              : 1; // bit 3~3
    volatile uint32_t JTAG_DWBYPASS                 : 1; // bit 4~4
    volatile uint32_t JTAG_BK_ENABLE                : 1; // bit 5~5
    volatile uint32_t DBG_STOPTIME                  : 1; // bit 6~6
    volatile uint32_t RESV_7_31                     : 25; // bit 7~31
};

union CMN_SYSCFG_REG_MCU_CFG {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_MCU_CFG_BITS              bit;
};

struct CMN_SYSCFG_REG_MCU_RST_ADDR_BITS
{
    volatile uint32_t RESET_VECTOR                  : 32; // bit 0~31
};

union CMN_SYSCFG_REG_MCU_RST_ADDR {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_MCU_RST_ADDR_BITS         bit;
};

struct CMN_SYSCFG_REG_VIO_OK_IMR_BITS
{
    volatile uint32_t VIO_OK_RISE_IMR               : 1; // bit 0~0
    volatile uint32_t VIO_OK_FALL_IMR               : 1; // bit 1~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union CMN_SYSCFG_REG_VIO_OK_IMR {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_VIO_OK_IMR_BITS           bit;
};

struct CMN_SYSCFG_REG_VIO_OK_IRSR_BITS
{
    volatile uint32_t VIO_OK_RISE_IRSR              : 1; // bit 0~0
    volatile uint32_t VIO_OK_FALL_IRSR              : 1; // bit 1~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union CMN_SYSCFG_REG_VIO_OK_IRSR {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_VIO_OK_IRSR_BITS          bit;
};

struct CMN_SYSCFG_REG_VIO_OK_ISR_BITS
{
    volatile uint32_t VIO_OK_RISE_ISR               : 1; // bit 0~0
    volatile uint32_t VIO_OK_FALL_ISR               : 1; // bit 1~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union CMN_SYSCFG_REG_VIO_OK_ISR {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_VIO_OK_ISR_BITS           bit;
};

struct CMN_SYSCFG_REG_HIT_COUNT_BITS
{
    volatile uint32_t E1_HIT_CNT                    : 32; // bit 0~31
};

union CMN_SYSCFG_REG_HIT_COUNT {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_HIT_COUNT_BITS            bit;
};

struct CMN_SYSCFG_REG_MISS_COUNT_BITS
{
    volatile uint32_t E1_MISS_CNT                   : 32; // bit 0~31
};

union CMN_SYSCFG_REG_MISS_COUNT {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_MISS_COUNT_BITS           bit;
};

struct CMN_SYSCFG_REG_BYP_COUNT_BITS
{
    volatile uint32_t E1_BYP_CNT                    : 32; // bit 0~31
};

union CMN_SYSCFG_REG_BYP_COUNT {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_BYP_COUNT_BITS            bit;
};

struct CMN_SYSCFG_REG_CACHE_CNT_CLR_BITS
{
    volatile uint32_t E1_HIT_CNT_CLR                : 1; // bit 0~0
    volatile uint32_t E1_MISS_CNT_CLR               : 1; // bit 1~1
    volatile uint32_t E1_BYP_CNT_CLR                : 1; // bit 2~2
    volatile uint32_t RESV_3_31                     : 29; // bit 3~31
};

union CMN_SYSCFG_REG_CACHE_CNT_CLR {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_CACHE_CNT_CLR_BITS        bit;
};

struct CMN_SYSCFG_REG_CMN_RSVD_BITS
{
    volatile uint32_t CMN_CFG_RSVD                  : 32; // bit 0~31
};

union CMN_SYSCFG_REG_CMN_RSVD {
    volatile uint32_t                               all;
    struct CMN_SYSCFG_REG_CMN_RSVD_BITS             bit;
};

typedef struct
{
    union CMN_SYSCFG_REG_TEST_CTRL                  REG_TEST_CTRL; // 0x000
    union CMN_SYSCFG_REG_RST_CTRL0                  REG_RST_CTRL0; // 0x004
    union CMN_SYSCFG_REG_CLK_EN_CTRL0               REG_CLK_EN_CTRL0; // 0x008
    union CMN_SYSCFG_REG_PERI_CLK_CFG0              REG_PERI_CLK_CFG0; // 0x00C
    union CMN_SYSCFG_REG_PERI_CLK_CFG1              REG_PERI_CLK_CFG1; // 0x010
    union CMN_SYSCFG_REG_PERI_CLK_CFG2              REG_PERI_CLK_CFG2; // 0x014
    union CMN_SYSCFG_REG_PERI_CLK_CFG3              REG_PERI_CLK_CFG3; // 0x018
    volatile uint32_t                               REG_RESV_0X1C_0X1C[1];
    union CMN_SYSCFG_REG_PERI_CLK_CFG4              REG_PERI_CLK_CFG4; // 0x020
    volatile uint32_t                               REG_RESV_0X24_0X28[2];
    union CMN_SYSCFG_REG_SW_RESET_AP                REG_SW_RESET_AP; // 0x02C
    union CMN_SYSCFG_REG_DMA_HS_SEL                 REG_DMA_HS_SEL; // 0x030
    union CMN_SYSCFG_REG_ANA_RSVD                   REG_ANA_RSVD; // 0x034
    union CMN_SYSCFG_REG_MCU_CFG                    REG_MCU_CFG; // 0x038
    union CMN_SYSCFG_REG_MCU_RST_ADDR               REG_MCU_RST_ADDR; // 0x03C
    union CMN_SYSCFG_REG_VIO_OK_IMR                 REG_VIO_OK_IMR; // 0x040
    union CMN_SYSCFG_REG_VIO_OK_IRSR                REG_VIO_OK_IRSR; // 0x044
    union CMN_SYSCFG_REG_VIO_OK_ISR                 REG_VIO_OK_ISR; // 0x048
    union CMN_SYSCFG_REG_HIT_COUNT                  REG_HIT_COUNT; // 0x04C
    union CMN_SYSCFG_REG_MISS_COUNT                 REG_MISS_COUNT; // 0x050
    union CMN_SYSCFG_REG_BYP_COUNT                  REG_BYP_COUNT; // 0x054
    union CMN_SYSCFG_REG_CACHE_CNT_CLR              REG_CACHE_CNT_CLR; // 0x058
    union CMN_SYSCFG_REG_CMN_RSVD                   REG_CMN_RSVD; // 0x05C
} CMN_SYSCFG_RegDef;


#endif // __CMN_SYSCFG_REGFILE_H__

