//  ----------------------------------------------------------------------
//  File Name   : GenCFold/flash_ctrl_reg_mars.h
//  Description : C header file generated by Python script.
//  Script Ver  : LS.AUTO_REG.2024.03.01
//  Create Time : 2024-03-20 14:46:55
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __FLASH_CTRL_REGFILE_H__
#define __FLASH_CTRL_REGFILE_H__

#include <stdint.h>

#define FLASH_CTRL_IDREV_OFFSET                     0x000
#define FLASH_CTRL_IDREV_ID_Pos                     12
#define FLASH_CTRL_IDREV_ID_Msk                     0xfffff000
#define FLASH_CTRL_IDREV_REVMAJOR_Pos               4
#define FLASH_CTRL_IDREV_REVMAJOR_Msk               0xff0
#define FLASH_CTRL_IDREV_REVMINOR_Pos               0
#define FLASH_CTRL_IDREV_REVMINOR_Msk               0xf

#define FLASH_CTRL_TRANSFMT_OFFSET                  0x010
#define FLASH_CTRL_TRANSFMT_ADDRLEN_Pos             16
#define FLASH_CTRL_TRANSFMT_ADDRLEN_Msk             0x30000
#define FLASH_CTRL_TRANSFMT_DATALEN_Pos             8
#define FLASH_CTRL_TRANSFMT_DATALEN_Msk             0x1f00
#define FLASH_CTRL_TRANSFMT_DATAMERGE_Pos           7
#define FLASH_CTRL_TRANSFMT_DATAMERGE_Msk           0x80
#define FLASH_CTRL_TRANSFMT_MOSIBIDIR_Pos           4
#define FLASH_CTRL_TRANSFMT_MOSIBIDIR_Msk           0x10
#define FLASH_CTRL_TRANSFMT_LSB_Pos                 3
#define FLASH_CTRL_TRANSFMT_LSB_Msk                 0x8
#define FLASH_CTRL_TRANSFMT_SLVMODE_Pos             2
#define FLASH_CTRL_TRANSFMT_SLVMODE_Msk             0x4
#define FLASH_CTRL_TRANSFMT_CPOL_Pos                1
#define FLASH_CTRL_TRANSFMT_CPOL_Msk                0x2
#define FLASH_CTRL_TRANSFMT_CPHA_Pos                0
#define FLASH_CTRL_TRANSFMT_CPHA_Msk                0x1

#define FLASH_CTRL_DIRECTIO_OFFSET                  0x014
#define FLASH_CTRL_DIRECTIO_DIRECTIOEN_Pos          24
#define FLASH_CTRL_DIRECTIO_DIRECTIOEN_Msk          0x1000000
#define FLASH_CTRL_DIRECTIO_HOLD_OE_Pos             21
#define FLASH_CTRL_DIRECTIO_HOLD_OE_Msk             0x200000
#define FLASH_CTRL_DIRECTIO_WP_OE_Pos               20
#define FLASH_CTRL_DIRECTIO_WP_OE_Msk               0x100000
#define FLASH_CTRL_DIRECTIO_MISO_OE_Pos             19
#define FLASH_CTRL_DIRECTIO_MISO_OE_Msk             0x80000
#define FLASH_CTRL_DIRECTIO_MOSI_OE_Pos             18
#define FLASH_CTRL_DIRECTIO_MOSI_OE_Msk             0x40000
#define FLASH_CTRL_DIRECTIO_SCLK_OE_Pos             17
#define FLASH_CTRL_DIRECTIO_SCLK_OE_Msk             0x20000
#define FLASH_CTRL_DIRECTIO_CS_OE_Pos               16
#define FLASH_CTRL_DIRECTIO_CS_OE_Msk               0x10000
#define FLASH_CTRL_DIRECTIO_HOLD_O_Pos              13
#define FLASH_CTRL_DIRECTIO_HOLD_O_Msk              0x2000
#define FLASH_CTRL_DIRECTIO_WP_O_Pos                12
#define FLASH_CTRL_DIRECTIO_WP_O_Msk                0x1000
#define FLASH_CTRL_DIRECTIO_MISO_O_Pos              11
#define FLASH_CTRL_DIRECTIO_MISO_O_Msk              0x800
#define FLASH_CTRL_DIRECTIO_MOSI_O_Pos              10
#define FLASH_CTRL_DIRECTIO_MOSI_O_Msk              0x400
#define FLASH_CTRL_DIRECTIO_SCLK_O_Pos              9
#define FLASH_CTRL_DIRECTIO_SCLK_O_Msk              0x200
#define FLASH_CTRL_DIRECTIO_CS_O_Pos                8
#define FLASH_CTRL_DIRECTIO_CS_O_Msk                0x100
#define FLASH_CTRL_DIRECTIO_HOLD_I_Pos              5
#define FLASH_CTRL_DIRECTIO_HOLD_I_Msk              0x20
#define FLASH_CTRL_DIRECTIO_WP_I_Pos                4
#define FLASH_CTRL_DIRECTIO_WP_I_Msk                0x10
#define FLASH_CTRL_DIRECTIO_MISO_I_Pos              3
#define FLASH_CTRL_DIRECTIO_MISO_I_Msk              0x8
#define FLASH_CTRL_DIRECTIO_MOSI_I_Pos              2
#define FLASH_CTRL_DIRECTIO_MOSI_I_Msk              0x4
#define FLASH_CTRL_DIRECTIO_SCLK_I_Pos              1
#define FLASH_CTRL_DIRECTIO_SCLK_I_Msk              0x2
#define FLASH_CTRL_DIRECTIO_CS_I_Pos                0
#define FLASH_CTRL_DIRECTIO_CS_I_Msk                0x1

#define FLASH_CTRL_TRANSCTRL_OFFSET                 0x020
#define FLASH_CTRL_TRANSCTRL_CMDEN_Pos              30
#define FLASH_CTRL_TRANSCTRL_CMDEN_Msk              0x40000000
#define FLASH_CTRL_TRANSCTRL_ADDREN_Pos             29
#define FLASH_CTRL_TRANSCTRL_ADDREN_Msk             0x20000000
#define FLASH_CTRL_TRANSCTRL_ADDRFMT_Pos            28
#define FLASH_CTRL_TRANSCTRL_ADDRFMT_Msk            0x10000000
#define FLASH_CTRL_TRANSCTRL_TRANSMODE_Pos          24
#define FLASH_CTRL_TRANSCTRL_TRANSMODE_Msk          0xf000000
#define FLASH_CTRL_TRANSCTRL_DUALQUAD_Pos           22
#define FLASH_CTRL_TRANSCTRL_DUALQUAD_Msk           0xc00000
#define FLASH_CTRL_TRANSCTRL_TOKENEN_Pos            21
#define FLASH_CTRL_TRANSCTRL_TOKENEN_Msk            0x200000
#define FLASH_CTRL_TRANSCTRL_WRTRANCNT_Pos          12
#define FLASH_CTRL_TRANSCTRL_WRTRANCNT_Msk          0x1ff000
#define FLASH_CTRL_TRANSCTRL_TOKENVALUE_Pos         11
#define FLASH_CTRL_TRANSCTRL_TOKENVALUE_Msk         0x800
#define FLASH_CTRL_TRANSCTRL_DUMMYCNT_Pos           9
#define FLASH_CTRL_TRANSCTRL_DUMMYCNT_Msk           0x600
#define FLASH_CTRL_TRANSCTRL_RDTRANCNT_Pos          0
#define FLASH_CTRL_TRANSCTRL_RDTRANCNT_Msk          0x1ff

#define FLASH_CTRL_CMD_OFFSET                       0x024
#define FLASH_CTRL_CMD_CMD_Pos                      0
#define FLASH_CTRL_CMD_CMD_Msk                      0xff

#define FLASH_CTRL_ADDR_OFFSET                      0x028
#define FLASH_CTRL_ADDR_ADDR_Pos                    0
#define FLASH_CTRL_ADDR_ADDR_Msk                    0xffffffff

#define FLASH_CTRL_DATA_OFFSET                      0x02C
#define FLASH_CTRL_DATA_DATA_Pos                    0
#define FLASH_CTRL_DATA_DATA_Msk                    0xffffffff

#define FLASH_CTRL_CTRL_OFFSET                      0x030
#define FLASH_CTRL_CTRL_TXTHRES_Pos                 16
#define FLASH_CTRL_CTRL_TXTHRES_Msk                 0x1f0000
#define FLASH_CTRL_CTRL_RXTHRES_Pos                 8
#define FLASH_CTRL_CTRL_RXTHRES_Msk                 0x1f00
#define FLASH_CTRL_CTRL_TXDMAEN_Pos                 4
#define FLASH_CTRL_CTRL_TXDMAEN_Msk                 0x10
#define FLASH_CTRL_CTRL_RXDMAEN_Pos                 3
#define FLASH_CTRL_CTRL_RXDMAEN_Msk                 0x8
#define FLASH_CTRL_CTRL_TXFIFORST_Pos               2
#define FLASH_CTRL_CTRL_TXFIFORST_Msk               0x4
#define FLASH_CTRL_CTRL_RXFIFORST_Pos               1
#define FLASH_CTRL_CTRL_RXFIFORST_Msk               0x2
#define FLASH_CTRL_CTRL_SPIRST_Pos                  0
#define FLASH_CTRL_CTRL_SPIRST_Msk                  0x1

#define FLASH_CTRL_STATUS_OFFSET                    0x034
#define FLASH_CTRL_STATUS_TXFULL_Pos                23
#define FLASH_CTRL_STATUS_TXFULL_Msk                0x800000
#define FLASH_CTRL_STATUS_TXEMPTY_Pos               22
#define FLASH_CTRL_STATUS_TXEMPTY_Msk               0x400000
#define FLASH_CTRL_STATUS_TXNUM_Pos                 16
#define FLASH_CTRL_STATUS_TXNUM_Msk                 0x1f0000
#define FLASH_CTRL_STATUS_RXFULL_Pos                15
#define FLASH_CTRL_STATUS_RXFULL_Msk                0x8000
#define FLASH_CTRL_STATUS_RXEMPTY_Pos               14
#define FLASH_CTRL_STATUS_RXEMPTY_Msk               0x4000
#define FLASH_CTRL_STATUS_RXNUM_Pos                 8
#define FLASH_CTRL_STATUS_RXNUM_Msk                 0x1f00
#define FLASH_CTRL_STATUS_SPIACTIVE_Pos             0
#define FLASH_CTRL_STATUS_SPIACTIVE_Msk             0x1

#define FLASH_CTRL_INTREN_OFFSET                    0x038
#define FLASH_CTRL_INTREN_SLVCMDEN_Pos              5
#define FLASH_CTRL_INTREN_SLVCMDEN_Msk              0x20
#define FLASH_CTRL_INTREN_ENDINTEN_Pos              4
#define FLASH_CTRL_INTREN_ENDINTEN_Msk              0x10
#define FLASH_CTRL_INTREN_TXFIFOINTEN_Pos           3
#define FLASH_CTRL_INTREN_TXFIFOINTEN_Msk           0x8
#define FLASH_CTRL_INTREN_RXFIFOINTEN_Pos           2
#define FLASH_CTRL_INTREN_RXFIFOINTEN_Msk           0x4
#define FLASH_CTRL_INTREN_TXFIFOURINTEN_Pos         1
#define FLASH_CTRL_INTREN_TXFIFOURINTEN_Msk         0x2
#define FLASH_CTRL_INTREN_RXFIFOORINTEN_Pos         0
#define FLASH_CTRL_INTREN_RXFIFOORINTEN_Msk         0x1

#define FLASH_CTRL_INTRST_OFFSET                    0x03C
#define FLASH_CTRL_INTRST_SLVCMDINT_Pos             5
#define FLASH_CTRL_INTRST_SLVCMDINT_Msk             0x20
#define FLASH_CTRL_INTRST_ENDINT_Pos                4
#define FLASH_CTRL_INTRST_ENDINT_Msk                0x10
#define FLASH_CTRL_INTRST_TXFIFOINT_Pos             3
#define FLASH_CTRL_INTRST_TXFIFOINT_Msk             0x8
#define FLASH_CTRL_INTRST_RXFIFOINT_Pos             2
#define FLASH_CTRL_INTRST_RXFIFOINT_Msk             0x4
#define FLASH_CTRL_INTRST_TXFIFOURINT_Pos           1
#define FLASH_CTRL_INTRST_TXFIFOURINT_Msk           0x2
#define FLASH_CTRL_INTRST_RXFIFOORINT_Pos           0
#define FLASH_CTRL_INTRST_RXFIFOORINT_Msk           0x1

#define FLASH_CTRL_TIMING_OFFSET                    0x040
#define FLASH_CTRL_TIMING_CS2SCLK_Pos               12
#define FLASH_CTRL_TIMING_CS2SCLK_Msk               0x7000
#define FLASH_CTRL_TIMING_CSHT_Pos                  8
#define FLASH_CTRL_TIMING_CSHT_Msk                  0xf00
#define FLASH_CTRL_TIMING_SCLK_DIV_Pos              0
#define FLASH_CTRL_TIMING_SCLK_DIV_Msk              0xff

#define FLASH_CTRL_MEMCTRL_OFFSET                   0x050
#define FLASH_CTRL_MEMCTRL_MEMCTRLCHG_Pos           8
#define FLASH_CTRL_MEMCTRL_MEMCTRLCHG_Msk           0x100
#define FLASH_CTRL_MEMCTRL_MEMRDCMD_Pos             0
#define FLASH_CTRL_MEMCTRL_MEMRDCMD_Msk             0xf

#define FLASH_CTRL_CS_ADDR_OFFSET                   0x054
#define FLASH_CTRL_CS_ADDR_CS0_MEM_ADDR_H_Pos       16
#define FLASH_CTRL_CS_ADDR_CS0_MEM_ADDR_H_Msk       0xffff0000
#define FLASH_CTRL_CS_ADDR_CS0_MEM_ADDR_L_Pos       0
#define FLASH_CTRL_CS_ADDR_CS0_MEM_ADDR_L_Msk       0xffff

#define FLASH_CTRL_CS_2_CTRL_OFFSET                 0x058
#define FLASH_CTRL_CS_2_CTRL_ADDR_RANGE_ENALBE_Pos    16
#define FLASH_CTRL_CS_2_CTRL_ADDR_RANGE_ENALBE_Msk    0xffff0000
#define FLASH_CTRL_CS_2_CTRL_CS1_MODE_SEL_Pos       2
#define FLASH_CTRL_CS_2_CTRL_CS1_MODE_SEL_Msk       0xc
#define FLASH_CTRL_CS_2_CTRL_CS0_MODE_SEL_Pos       0
#define FLASH_CTRL_CS_2_CTRL_CS0_MODE_SEL_Msk       0x3

#define FLASH_CTRL_CONFIG_OFFSET                    0x07C
#define FLASH_CTRL_CONFIG_SLAVE_Pos                 14
#define FLASH_CTRL_CONFIG_SLAVE_Msk                 0x4000
#define FLASH_CTRL_CONFIG_EILMMEM_Pos               13
#define FLASH_CTRL_CONFIG_EILMMEM_Msk               0x2000
#define FLASH_CTRL_CONFIG_AHBMEM_Pos                12
#define FLASH_CTRL_CONFIG_AHBMEM_Msk                0x1000
#define FLASH_CTRL_CONFIG_DIRECTIO_Pos              11
#define FLASH_CTRL_CONFIG_DIRECTIO_Msk              0x800
#define FLASH_CTRL_CONFIG_QUADSPI_Pos               9
#define FLASH_CTRL_CONFIG_QUADSPI_Msk               0x200
#define FLASH_CTRL_CONFIG_DUALSPI_Pos               8
#define FLASH_CTRL_CONFIG_DUALSPI_Msk               0x100
#define FLASH_CTRL_CONFIG_TXFIFOSIZE_Pos            4
#define FLASH_CTRL_CONFIG_TXFIFOSIZE_Msk            0x30
#define FLASH_CTRL_CONFIG_RXFIFOSIZE_Pos            0
#define FLASH_CTRL_CONFIG_RXFIFOSIZE_Msk            0x3

#define FLASH_CTRL_USER_CONFIG_OFFSET               0x080
#define FLASH_CTRL_USER_CONFIG_KEY_PROTECTION_Pos    24
#define FLASH_CTRL_USER_CONFIG_KEY_PROTECTION_Msk    0xff000000
#define FLASH_CTRL_USER_CONFIG_CRYPTO_EN_Pos        9
#define FLASH_CTRL_USER_CONFIG_CRYPTO_EN_Msk        0x200
#define FLASH_CTRL_USER_CONFIG_APPCLK_EN_Pos        8
#define FLASH_CTRL_USER_CONFIG_APPCLK_EN_Msk        0x100
#define FLASH_CTRL_USER_CONFIG_MEM_DM_EN_Pos        5
#define FLASH_CTRL_USER_CONFIG_MEM_DM_EN_Msk        0x20
#define FLASH_CTRL_USER_CONFIG_REG_DM_EN_Pos        4
#define FLASH_CTRL_USER_CONFIG_REG_DM_EN_Msk        0x10
#define FLASH_CTRL_USER_CONFIG_MEM_DTR_EN_Pos       3
#define FLASH_CTRL_USER_CONFIG_MEM_DTR_EN_Msk       0x8
#define FLASH_CTRL_USER_CONFIG_INV_CLK_SEL_Pos      2
#define FLASH_CTRL_USER_CONFIG_INV_CLK_SEL_Msk      0x4
#define FLASH_CTRL_USER_CONFIG_QPI_EN_Pos           1
#define FLASH_CTRL_USER_CONFIG_QPI_EN_Msk           0x2
#define FLASH_CTRL_USER_CONFIG_TOKEN_EN_Pos         0
#define FLASH_CTRL_USER_CONFIG_TOKEN_EN_Msk         0x1

#define FLASH_CTRL_USER_TOKEN_OFFSET                0x084
#define FLASH_CTRL_USER_TOKEN_TOKEN_VALUE_Pos       0
#define FLASH_CTRL_USER_TOKEN_TOKEN_VALUE_Msk       0xff

#define FLASH_CTRL_USER_MEM_READ_OP_OFFSET          0x088
#define FLASH_CTRL_USER_MEM_READ_OP_MEM_LEN_Pos     16
#define FLASH_CTRL_USER_MEM_READ_OP_MEM_LEN_Msk     0x30000
#define FLASH_CTRL_USER_MEM_READ_OP_MEM_OP_Pos      0
#define FLASH_CTRL_USER_MEM_READ_OP_MEM_OP_Msk      0xff

#define FLASH_CTRL_USER_MEM_READ_TRANS_OFFSET       0x08C
#define FLASH_CTRL_USER_MEM_READ_TRANS_MEM_TRANS_Pos    0
#define FLASH_CTRL_USER_MEM_READ_TRANS_MEM_TRANS_Msk    0x7fffffff

#define FLASH_CTRL_USER_DUMMY_COUNT_OFFSET          0x090
#define FLASH_CTRL_USER_DUMMY_COUNT_MEM_DM_CNT_Pos    8
#define FLASH_CTRL_USER_DUMMY_COUNT_MEM_DM_CNT_Msk    0xf00
#define FLASH_CTRL_USER_DUMMY_COUNT_REG_DM_CNT_Pos    0
#define FLASH_CTRL_USER_DUMMY_COUNT_REG_DM_CNT_Msk    0xf

#define FLASH_CTRL_USER_APPEND_CLOCK_PATTERN_OFFSET    0x094
#define FLASH_CTRL_USER_APPEND_CLOCK_PATTERN_APPCLK_PAT_Pos    0
#define FLASH_CTRL_USER_APPEND_CLOCK_PATTERN_APPCLK_PAT_Msk    0xffff

struct FLASH_CTRL_REG_IDREV_BITS
{
    volatile uint32_t REVMINOR                      : 4; // bit 0~3
    volatile uint32_t REVMAJOR                      : 8; // bit 4~11
    volatile uint32_t ID                            : 20; // bit 12~31
};

union FLASH_CTRL_REG_IDREV {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_IDREV_BITS                bit;
};

struct FLASH_CTRL_REG_TRANSFMT_BITS
{
    volatile uint32_t CPHA                          : 1; // bit 0~0
    volatile uint32_t CPOL                          : 1; // bit 1~1
    volatile uint32_t SLVMODE                       : 1; // bit 2~2
    volatile uint32_t LSB                           : 1; // bit 3~3
    volatile uint32_t MOSIBIDIR                     : 1; // bit 4~4
    volatile uint32_t RESV_5_6                      : 2; // bit 5~6
    volatile uint32_t DATAMERGE                     : 1; // bit 7~7
    volatile uint32_t DATALEN                       : 5; // bit 8~12
    volatile uint32_t RESV_13_15                    : 3; // bit 13~15
    volatile uint32_t ADDRLEN                       : 2; // bit 16~17
    volatile uint32_t RESV_18_30                    : 13; // bit 18~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union FLASH_CTRL_REG_TRANSFMT {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_TRANSFMT_BITS             bit;
};

struct FLASH_CTRL_REG_DIRECTIO_BITS
{
    volatile uint32_t CS_I                          : 1; // bit 0~0
    volatile uint32_t SCLK_I                        : 1; // bit 1~1
    volatile uint32_t MOSI_I                        : 1; // bit 2~2
    volatile uint32_t MISO_I                        : 1; // bit 3~3
    volatile uint32_t WP_I                          : 1; // bit 4~4
    volatile uint32_t HOLD_I                        : 1; // bit 5~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t CS_O                          : 1; // bit 8~8
    volatile uint32_t SCLK_O                        : 1; // bit 9~9
    volatile uint32_t MOSI_O                        : 1; // bit 10~10
    volatile uint32_t MISO_O                        : 1; // bit 11~11
    volatile uint32_t WP_O                          : 1; // bit 12~12
    volatile uint32_t HOLD_O                        : 1; // bit 13~13
    volatile uint32_t RESV_14_15                    : 2; // bit 14~15
    volatile uint32_t CS_OE                         : 1; // bit 16~16
    volatile uint32_t SCLK_OE                       : 1; // bit 17~17
    volatile uint32_t MOSI_OE                       : 1; // bit 18~18
    volatile uint32_t MISO_OE                       : 1; // bit 19~19
    volatile uint32_t WP_OE                         : 1; // bit 20~20
    volatile uint32_t HOLD_OE                       : 1; // bit 21~21
    volatile uint32_t RESV_22_23                    : 2; // bit 22~23
    volatile uint32_t DIRECTIOEN                    : 1; // bit 24~24
    volatile uint32_t RESV_25_31                    : 7; // bit 25~31
};

union FLASH_CTRL_REG_DIRECTIO {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_DIRECTIO_BITS             bit;
};

struct FLASH_CTRL_REG_TRANSCTRL_BITS
{
    volatile uint32_t RDTRANCNT                     : 9; // bit 0~8
    volatile uint32_t DUMMYCNT                      : 2; // bit 9~10
    volatile uint32_t TOKENVALUE                    : 1; // bit 11~11
    volatile uint32_t WRTRANCNT                     : 9; // bit 12~20
    volatile uint32_t TOKENEN                       : 1; // bit 21~21
    volatile uint32_t DUALQUAD                      : 2; // bit 22~23
    volatile uint32_t TRANSMODE                     : 4; // bit 24~27
    volatile uint32_t ADDRFMT                       : 1; // bit 28~28
    volatile uint32_t ADDREN                        : 1; // bit 29~29
    volatile uint32_t CMDEN                         : 1; // bit 30~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union FLASH_CTRL_REG_TRANSCTRL {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_TRANSCTRL_BITS            bit;
};

struct FLASH_CTRL_REG_CMD_BITS
{
    volatile uint32_t CMD                           : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union FLASH_CTRL_REG_CMD {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_CMD_BITS                  bit;
};

struct FLASH_CTRL_REG_ADDR_BITS
{
    volatile uint32_t ADDR                          : 32; // bit 0~31
};

union FLASH_CTRL_REG_ADDR {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_ADDR_BITS                 bit;
};

struct FLASH_CTRL_REG_DATA_BITS
{
    volatile uint32_t DATA                          : 32; // bit 0~31
};

union FLASH_CTRL_REG_DATA {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_DATA_BITS                 bit;
};

struct FLASH_CTRL_REG_CTRL_BITS
{
    volatile uint32_t SPIRST                        : 1; // bit 0~0
    volatile uint32_t RXFIFORST                     : 1; // bit 1~1
    volatile uint32_t TXFIFORST                     : 1; // bit 2~2
    volatile uint32_t RXDMAEN                       : 1; // bit 3~3
    volatile uint32_t TXDMAEN                       : 1; // bit 4~4
    volatile uint32_t RESV_5_7                      : 3; // bit 5~7
    volatile uint32_t RXTHRES                       : 5; // bit 8~12
    volatile uint32_t RESV_13_15                    : 3; // bit 13~15
    volatile uint32_t TXTHRES                       : 5; // bit 16~20
    volatile uint32_t RESV_21_31                    : 11; // bit 21~31
};

union FLASH_CTRL_REG_CTRL {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_CTRL_BITS                 bit;
};

struct FLASH_CTRL_REG_STATUS_BITS
{
    volatile uint32_t SPIACTIVE                     : 1; // bit 0~0
    volatile uint32_t RESV_1_7                      : 7; // bit 1~7
    volatile uint32_t RXNUM                         : 5; // bit 8~12
    volatile uint32_t RESV_13_13                    : 1; // bit 13~13
    volatile uint32_t RXEMPTY                       : 1; // bit 14~14
    volatile uint32_t RXFULL                        : 1; // bit 15~15
    volatile uint32_t TXNUM                         : 5; // bit 16~20
    volatile uint32_t RESV_21_21                    : 1; // bit 21~21
    volatile uint32_t TXEMPTY                       : 1; // bit 22~22
    volatile uint32_t TXFULL                        : 1; // bit 23~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union FLASH_CTRL_REG_STATUS {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_STATUS_BITS               bit;
};

struct FLASH_CTRL_REG_INTREN_BITS
{
    volatile uint32_t RXFIFOORINTEN                 : 1; // bit 0~0
    volatile uint32_t TXFIFOURINTEN                 : 1; // bit 1~1
    volatile uint32_t RXFIFOINTEN                   : 1; // bit 2~2
    volatile uint32_t TXFIFOINTEN                   : 1; // bit 3~3
    volatile uint32_t ENDINTEN                      : 1; // bit 4~4
    volatile uint32_t SLVCMDEN                      : 1; // bit 5~5
    volatile uint32_t RESV_6_31                     : 26; // bit 6~31
};

union FLASH_CTRL_REG_INTREN {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_INTREN_BITS               bit;
};

struct FLASH_CTRL_REG_INTRST_BITS
{
    volatile uint32_t RXFIFOORINT                   : 1; // bit 0~0
    volatile uint32_t TXFIFOURINT                   : 1; // bit 1~1
    volatile uint32_t RXFIFOINT                     : 1; // bit 2~2
    volatile uint32_t TXFIFOINT                     : 1; // bit 3~3
    volatile uint32_t ENDINT                        : 1; // bit 4~4
    volatile uint32_t SLVCMDINT                     : 1; // bit 5~5
    volatile uint32_t RESV_6_31                     : 26; // bit 6~31
};

union FLASH_CTRL_REG_INTRST {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_INTRST_BITS               bit;
};

struct FLASH_CTRL_REG_TIMING_BITS
{
    volatile uint32_t SCLK_DIV                      : 8; // bit 0~7
    volatile uint32_t CSHT                          : 4; // bit 8~11
    volatile uint32_t CS2SCLK                       : 3; // bit 12~14
    volatile uint32_t RESV_15_31                    : 17; // bit 15~31
};

union FLASH_CTRL_REG_TIMING {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_TIMING_BITS               bit;
};

struct FLASH_CTRL_REG_MEMCTRL_BITS
{
    volatile uint32_t MEMRDCMD                      : 4; // bit 0~3
    volatile uint32_t RESV_4_7                      : 4; // bit 4~7
    volatile uint32_t MEMCTRLCHG                    : 1; // bit 8~8
    volatile uint32_t RESV_9_31                     : 23; // bit 9~31
};

union FLASH_CTRL_REG_MEMCTRL {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_MEMCTRL_BITS              bit;
};

struct FLASH_CTRL_REG_CS_ADDR_BITS
{
    volatile uint32_t CS0_MEM_ADDR_L                : 16; // bit 0~15
    volatile uint32_t CS0_MEM_ADDR_H                : 16; // bit 16~31
};

union FLASH_CTRL_REG_CS_ADDR {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_CS_ADDR_BITS              bit;
};

struct FLASH_CTRL_REG_CS_2_CTRL_BITS
{
    volatile uint32_t CS0_MODE_SEL                  : 2; // bit 0~1
    volatile uint32_t CS1_MODE_SEL                  : 2; // bit 2~3
    volatile uint32_t RESV_4_15                     : 12; // bit 4~15
    volatile uint32_t ADDR_RANGE_ENALBE             : 16; // bit 16~31
};

union FLASH_CTRL_REG_CS_2_CTRL {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_CS_2_CTRL_BITS            bit;
};

struct FLASH_CTRL_REG_CONFIG_BITS
{
    volatile uint32_t RXFIFOSIZE                    : 2; // bit 0~1
    volatile uint32_t RESV_2_3                      : 2; // bit 2~3
    volatile uint32_t TXFIFOSIZE                    : 2; // bit 4~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t DUALSPI                       : 1; // bit 8~8
    volatile uint32_t QUADSPI                       : 1; // bit 9~9
    volatile uint32_t RESV_10_10                    : 1; // bit 10~10
    volatile uint32_t DIRECTIO                      : 1; // bit 11~11
    volatile uint32_t AHBMEM                        : 1; // bit 12~12
    volatile uint32_t EILMMEM                       : 1; // bit 13~13
    volatile uint32_t SLAVE                         : 1; // bit 14~14
    volatile uint32_t RESV_15_31                    : 17; // bit 15~31
};

union FLASH_CTRL_REG_CONFIG {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_CONFIG_BITS               bit;
};

struct FLASH_CTRL_REG_USER_CONFIG_BITS
{
    volatile uint32_t TOKEN_EN                      : 1; // bit 0~0
    volatile uint32_t QPI_EN                        : 1; // bit 1~1
    volatile uint32_t INV_CLK_SEL                   : 1; // bit 2~2
    volatile uint32_t MEM_DTR_EN                    : 1; // bit 3~3
    volatile uint32_t REG_DM_EN                     : 1; // bit 4~4
    volatile uint32_t MEM_DM_EN                     : 1; // bit 5~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t APPCLK_EN                     : 1; // bit 8~8
    volatile uint32_t CRYPTO_EN                     : 1; // bit 9~9
    volatile uint32_t RESV_10_23                    : 14; // bit 10~23
    volatile uint32_t KEY_PROTECTION                : 8; // bit 24~31
};

union FLASH_CTRL_REG_USER_CONFIG {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_USER_CONFIG_BITS          bit;
};

struct FLASH_CTRL_REG_USER_TOKEN_BITS
{
    volatile uint32_t TOKEN_VALUE                   : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union FLASH_CTRL_REG_USER_TOKEN {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_USER_TOKEN_BITS           bit;
};

struct FLASH_CTRL_REG_USER_MEM_READ_OP_BITS
{
    volatile uint32_t MEM_OP                        : 8; // bit 0~7
    volatile uint32_t RESV_8_15                     : 8; // bit 8~15
    volatile uint32_t MEM_LEN                       : 2; // bit 16~17
    volatile uint32_t RESV_18_31                    : 14; // bit 18~31
};

union FLASH_CTRL_REG_USER_MEM_READ_OP {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_USER_MEM_READ_OP_BITS     bit;
};

struct FLASH_CTRL_REG_USER_MEM_READ_TRANS_BITS
{
    volatile uint32_t MEM_TRANS                     : 31; // bit 0~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union FLASH_CTRL_REG_USER_MEM_READ_TRANS {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_USER_MEM_READ_TRANS_BITS    bit;
};

struct FLASH_CTRL_REG_USER_DUMMY_COUNT_BITS
{
    volatile uint32_t REG_DM_CNT                    : 4; // bit 0~3
    volatile uint32_t RESV_4_7                      : 4; // bit 4~7
    volatile uint32_t MEM_DM_CNT                    : 4; // bit 8~11
    volatile uint32_t RESV_12_31                    : 20; // bit 12~31
};

union FLASH_CTRL_REG_USER_DUMMY_COUNT {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_USER_DUMMY_COUNT_BITS     bit;
};

struct FLASH_CTRL_REG_USER_APPEND_CLOCK_PATTERN_BITS
{
    volatile uint32_t APPCLK_PAT                    : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union FLASH_CTRL_REG_USER_APPEND_CLOCK_PATTERN {
    volatile uint32_t                               all;
    struct FLASH_CTRL_REG_USER_APPEND_CLOCK_PATTERN_BITS    bit;
};

typedef struct
{
    union FLASH_CTRL_REG_IDREV                      REG_IDREV;   // 0x000
    volatile uint32_t                               REG_RESV_0X4_0XC[3];
    union FLASH_CTRL_REG_TRANSFMT                   REG_TRANSFMT; // 0x010
    union FLASH_CTRL_REG_DIRECTIO                   REG_DIRECTIO; // 0x014
    volatile uint32_t                               REG_RESV_0X18_0X1C[2];
    union FLASH_CTRL_REG_TRANSCTRL                  REG_TRANSCTRL; // 0x020
    union FLASH_CTRL_REG_CMD                        REG_CMD;     // 0x024
    union FLASH_CTRL_REG_ADDR                       REG_ADDR;    // 0x028
    union FLASH_CTRL_REG_DATA                       REG_DATA;    // 0x02C
    union FLASH_CTRL_REG_CTRL                       REG_CTRL;    // 0x030
    union FLASH_CTRL_REG_STATUS                     REG_STATUS;  // 0x034
    union FLASH_CTRL_REG_INTREN                     REG_INTREN;  // 0x038
    union FLASH_CTRL_REG_INTRST                     REG_INTRST;  // 0x03C
    union FLASH_CTRL_REG_TIMING                     REG_TIMING;  // 0x040
    volatile uint32_t                               REG_RESV_0X44_0X4C[3];
    union FLASH_CTRL_REG_MEMCTRL                    REG_MEMCTRL; // 0x050
    union FLASH_CTRL_REG_CS_ADDR                    REG_CS_ADDR; // 0x054
    union FLASH_CTRL_REG_CS_2_CTRL                  REG_CS_2_CTRL; // 0x058
    volatile uint32_t                               REG_RESV_0X5C_0X78[8];
    union FLASH_CTRL_REG_CONFIG                     REG_CONFIG;  // 0x07C
    union FLASH_CTRL_REG_USER_CONFIG                REG_USER_CONFIG; // 0x080
    union FLASH_CTRL_REG_USER_TOKEN                 REG_USER_TOKEN; // 0x084
    union FLASH_CTRL_REG_USER_MEM_READ_OP           REG_USER_MEM_READ_OP; // 0x088
    union FLASH_CTRL_REG_USER_MEM_READ_TRANS        REG_USER_MEM_READ_TRANS; // 0x08C
    union FLASH_CTRL_REG_USER_DUMMY_COUNT           REG_USER_DUMMY_COUNT; // 0x090
    union FLASH_CTRL_REG_USER_APPEND_CLOCK_PATTERN    REG_USER_APPEND_CLOCK_PATTERN; // 0x094
} FLASH_CTRL_RegDef;


#endif // __FLASH_CTRL_REGFILE_H__

